pulp/pulp_rpm

plugins/types/rpm_support.json
This is because the title index is not used for internal pulp queries and is causing errors during syncing for erratum with long titles.
=> 1175616 - Remove the index on the title field from erratum units

plugins/pulp_rpm/plugins/distributors/yum/metadata/filelists.py, plugins/pulp_rpm/plugins/distributors/yum/metadata/other.py, plugins/pulp_rpm/plugins/distributors/yum/metadata/primary.py
https://bugzilla.redhat.com/show_bug.cgi?id=1176698
=> Fix Python 2.6 compatibility for unicode encoded rpm metadata

plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/test/unit/plugins/importers/yum/model_factory.py, plugins/test/unit/plugins/importers/yum/test_sync.py
Errata are typically published via updateinfo.xml in the feed repository.
However, an erratum may span across multiple repos. For example, the POODLE
erratum was for both RHEL6 and RHEL7.
Errata that span repos contain the same ID (and thus unit_key), but may have
different pkglist sets. Upstream reposotiries will typically prune the pkglist
to only contain packages in that repo. This causes issues when the same erratum
is in two or more repositories, each containing different package sets.
This patch adds a new `additive_type` flag to `save_fileless_units()`.  If the
flag is enabled, `save_fileless_units()` will detect if an existing unit
exists, and will call `_concatenate_units()` to combine the existing unit with
the new unit. The behavior of `_concatenate_units()` is dependant on the …
=> 1171278 - update erratum when a new packagelist is encountered

plugins/pulp_rpm/plugins/importers/yum/repomd/metadata.py, plugins/pulp_rpm/plugins/importers/yum/repomd/packages.py, plugins/test/unit/plugins/importers/yum/repomd/test_metadata.py
https://bugzilla.redhat.com/show_bug.cgi?id=1172887
=> 1172887 - Support bz2 compression of repo metadata files

extensions_admin/pulp_rpm/extensions/admin/status.py, extensions_admin/test/unit/extensions/admin/test_status.py
[bz - 1147078](https://bugzilla.redhat.com/show_bug.cgi?id=1147078)
If a treeinfo file pointed to nonexistent files, pulp-admin failed.
This is addressed in two ways. First, I put the needed information in "error_details". Secondly, I made the error message and error code more flexible by using .get() to prevent similar issues from breaking pulp-admin.
Now against 2.6 rather than [master](https://github.com/pulp/pulp_rpm/pull/621)
=> 1147078 - fix error reporting for treeinfo files

extensions_admin/pulp_rpm/extensions/admin/contents.py, extensions_admin/test/unit/extensions/admin/test_contents.py
pulp-admin was previously only looking at the first package list returned by
platform when printing package lists. Instead, it should loop over all package
lists in the erratum.
=> 1171278 - allow pulp-admin to print all packages associated with errata

.gitignore
Flake8 raised a lot of problems related to .ropeproject directory, so I missed a legitimate PEP-8 violation. This tells flake8 to ignore dotfiles and fixes that PEP-8 violation. Also adds .ropeproject  to the gitignore.
=> add ropeproject to gitignore

docs/tech-reference/yum-plugins.rst, docs/user-guide/release-notes/2.6.x.rst, plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py, plugins/pulp_rpm/plugins/migrations/0019_add_timestamp_to_distribution.py, plugins/test/data/test_dot_treeinfo/.treeinfo, plugins/test/data/test_treeinfo/treeinfo, plugins/test/unit/plugins/importers/yum/parse/test_treeinfo.py, plugins/test/unit/plugins/importers/yum/test_sync.py, plugins/test/unit/plugins/migrations/test_0019_add_timestamp_to_distribution.py
https://bugzilla.redhat.com/show_bug.cgi?id=1147073
Since this is needed downstream, I think it should be included in 2.6.0.
=> 1147073 - when a distribution hasn't changed, sync no longer re-donwnloads its files

plugins/pulp_rpm/plugins/importers/iso/importer.py, plugins/pulp_rpm/plugins/importers/iso/sync.py, plugins/pulp_rpm/plugins/profilers/yum.py, plugins/test/unit/plugins/importers/iso/test_sync.py
Platform had some silly imports in pulp.plugins that were only there so
that plugins don't import pulp.server. These imports were angering
flake8 (for good reason). This commit fixes pulp_rpm's imports so
they import from the real place that the code lived.
=> Respond to PEP-8 changes in platform.

plugins/pulp_rpm/plugins/importers/yum/associate.py, plugins/pulp_rpm/plugins/importers/yum/depsolve.py, plugins/test/unit/plugins/importers/yum/test_depsolve.py
Previously, calling `copy_rpms()` with dep solving  enabled would result in a
large number of new dictionaries. For example, copying a single erratum from
RHEL 6.6 to 6.1 would result in 1.3 million new dicts. This ate a large amount
of memory.
Instead, flatten the "provides" metadata on the unit when doing dep solving
since we only need the name of the provide, not the full dict. This reduces the
number of created dicts to 81K for the scenario mentioned above, and results in
a ~70% memory savings.
Credit for this fix goes to @mhrivnak.
=> 1185868 - create fewer dictionaries when depsolving

plugins/pulp_rpm/plugins/distributors/yum/distributor.py, plugins/pulp_rpm/plugins/migrations/0021_clean_http_directories.py, plugins/test/unit/plugins/distributors/yum/test_distributor.py, plugins/test/unit/plugins/migrations/test_0021_clean_http_directories.py
When repos are deleted, the simple hosting directory structure that matches their relative url is not cleaned up, which leaves the opportunity to conflict with sub-urls of deleted repos.
[BZ-1183784](https://bugzilla.redhat.com/show_bug.cgi?id=1183784)
This patch cleans up this directory structure when a repo is deleted. There is also a migration to clean already existing orphaned directories.
=> 1183784 - clean hosting directories on repo distributor delete

extensions_admin/pulp_rpm/extensions/admin/repo_create_update.py, extensions_admin/test/unit/extensions/admin/test_repo_create_update.py
If the --serve-http flag is set to true the default value of --serve-https was
improperly being set to false.  This fixes it to maintain the default
value even if the --serve-http flag is set.
closes #577 
https://pulp.plan.io/issues/577
=> 577 - Fix the the --serve-https to observe defaults.

plugins/pulp_rpm/plugins/importers/yum/upload.py, plugins/test/unit/plugins/importers/yum/test_upload.py
The build_time & time values for uploaded rpms have not been
saved on the model and they are being saved for synced rpms.
Update the processing code to calculate these values upon upload.
closes #638
=> 638 - Process build_time & time values for uploaded RPMs

extensions_consumer/pulp_rpm/extensions/consumer/pulp_cli.py, extensions_consumer/test/unit/extensions/consumer/test_pulp_cli.py
closes [617] (https://pulp.plan.io/issues/617)
=> 617 - pulp-consumer rpm repo unbind non-existent repo fails with unexpected error

plugins/pulp_rpm/plugins/profilers/yum.py, plugins/test/data/test_errata_install/updateinfo.xml, plugins/test/unit/plugins/profilers/test_yum.py
Previously, if an erratum contained packages with the same name but different
versions, Pulp would attempt to install the latest version of said package when
applying an erratum to a system. This behavior is incorrect since an erratum
might contain multiple packages across repos.
Instead, we need to filter out any packages that we do not have access to
before applying the erratum.
re #770
=> 770: Only apply packages in errata when they are actually available

handlers/pulp_rpm/handlers/rpmtools.py, handlers/test/unit/handlers/mock_yum.py
https://pulp.plan.io/issues/767
=> Fix: Issue 767 - unicode description of InstallError

plugins/pulp_rpm/plugins/profilers/yum.py
A previous commit I made (1704c9ff0) had a dict comprehension. This commit
rewrites it to be 2.6-compat.
=> Remove a py2.7-ism

plugins/pulp_rpm/plugins/profilers/yum.py, plugins/test/data/test_errata_install/updateinfo.xml, plugins/test/unit/plugins/profilers/test_yum.py
Some updateinfo.xml metadata does not contain the `epoch` field in package
records. In these cases, Pulp will not be able to find the appropriate RPM.
In these cases, we can assume that the epoch should be '0'. This allows Pulp to
find the RPM when applying packages to a system.
fixes #833
=> treat 'epoch' as '0' when it does not exist or is null

plugins/pulp_rpm/plugins/error_codes.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/test/unit/plugins/importers/yum/test_sync.py
This depends on changes in pulp that better-handle PulpCodedException
reporting.
refs #702
refs #652 
https://pulp.plan.io/issues/652
https://pulp.plan.io/issues/702
https://github.com/pulp/pulp/pull/1772
=> sync errors now use PulpCodedException for better error reporting

devel/pulp_rpm/devel/rpm_support_base.py
Reviewed on https://github.com/pulp/pulp_rpm/pull/669 and reopened here to merge to 2.6-testing.
=> Ensure that logging is shutdown on test teardown.

docs/user-guide/release-notes/2.6.x.rst, plugins/pulp_rpm/plugins/profilers/yum.py, plugins/test/unit/plugins/profilers/test_yum.py
https://pulp.plan.io/issues/820
When the consumer does not have an RPM unit profile, the profiler will fail to translate the ERRATA unit into RPM units.
Example using the CLI:
```
[jortel@localhost pulp]$ pulp-admin rpm consumer errata install run --consumer-id=jeff -e foo
Consumer has no RPM unit profile
```
=> Refs: #820 - raise coded exception when no RPM profiles exist.

common/pulp_rpm/common/constants.py, docs/user-guide/release-notes/2.6.x.rst, plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py, plugins/pulp_rpm/plugins/importers/yum/repomd/metadata.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/test/unit/plugins/importers/yum/repomd/test_metadata.py, plugins/test/unit/plugins/importers/yum/test_sync.py
closes #2 
https://pulp.plan.io/issues/2
=> Sync now skips most steps if the feed metadata has not changed.

docs/tech-reference/yum-plugins.rst, docs/user-guide/recipes.rst, docs/user-guide/release-notes/2.7.x.rst, extensions_admin/pulp_rpm/extensions/admin/repo_create_update.py, extensions_admin/test/unit/extensions/admin/test_repo_create_update.py, plugins/test/unit/plugins/distributors/yum/test_publish.py
This requires https://github.com/pulp/pulp/pull/1821.
fixes #163
=> Enable basic auth as an option when syncing repos

devel/pulp_rpm/devel/rpm_support_base.py, plugins/pulp_rpm/plugins/distributors/yum/distributor.py, plugins/test/unit/__init__.py, plugins/test/unit/plugins/distributors/yum/test_distributor.py
Use the test package to start the database connection, rather than
relying on test superclasses to do it. This way, only one database
connection will happen during the unit tests rather than one per test
class.
https://pulp.plan.io/issues/131
re #131
=> Initialize the DB connection in the test package.

pulp-rpm.spec
Python-pulp-repoauth now supplies the repo auth framework but does not supply
any authenticatiors. The OID validation RPM supplies the actual cert check now.
This depends on https://github.com/pulp/pulp/pull/1869/.
fixes #975
https://pulp.plan.io/issues/975
=> Depend on python-pulp-oid_validation instead of python-pulp-repoauth

docs/user-guide/isos.rst, docs/user-guide/recipes.rst, extensions_admin/pulp_rpm/extensions/admin/iso/status.py, extensions_admin/pulp_rpm/extensions/admin/status.py, extensions_admin/test/unit/extensions/admin/iso/test_extension_admin_iso_status.py
I also changed all the docs and messages not to confuse the users. I did not touch any variables' or methods' name.
closes #966
https://pulp.plan.io/issues/966
=> Fixing discrepancy "canceled" vs. "cancelled

plugins/pulp_rpm/plugins/distributors/yum/configuration.py, plugins/test/unit/plugins/distributors/yum/test_configuration.py
closes #1042
https://pulp.plan.io/issues/1042
It turns out that pulp complains not only for relative_url collision of
another relative_url repo, but also for relative_url collision with repo id
of existing repo.
Due to this behaviour pulp renders incorrect and false message.
Current logic has this output http://fpaste.org/236550/35238325/. Look at lines 100-101 - they are false.
I added two different messages to fix this.
=> Exception raised when building error message on relative_url collision

devel/pulp_rpm/devel/rpm_support_base.py, plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/pulp_rpm/plugins/migrations/0003_custom_metadata_on_scratchpad.py, plugins/pulp_rpm/plugins/migrations/0004_pkg_group_category_repoid.py, plugins/pulp_rpm/plugins/migrations/0007_inventoried_custom_metadata.py, plugins/pulp_rpm/plugins/migrations/0016_new_yum_distributor.py, plugins/test/unit/plugins/distributors/yum/test_publish.py, plugins/test/unit/plugins/migrations/test_0004_migrate.py, plugins/test/unit/plugins/migrations/test_0016_new_yum_distributor.py
This PR uses mongoengine to access repos rather than using the db directly. It also removes the use of code that was removed in https://github.com/pulp/pulp/pull/1931.
This cannot be merged until 1931 has been merged, but this code is necessary to test core if you have rpm installed.
=> Use mongoengine repo model

plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py, plugins/test/unit/plugins/importers/yum/test_sync.py
=> Removing shutil.move and copytree where /var/chache/pulp is involved

plugins/test/unit/plugins/migrations/test_0004_migrate.py
These tests were broken by this core change: 
https://github.com/pulp/pulp/pull/2099
=> fix tests that relied on deprecated core code

plugins/test/unit/plugins/importers/yum/test_sync.py
This change in pulp caused two unit tests to break in pulp_rpm:
https://github.com/pulp/pulp/pull/2037/files#diff-8613e089ba042e02761c8527b3c58905L221
In these tests using the old path, `types_db.type_definition(type_id)` returned `None`, which would cause problems except that there are no units, and iteration below never happened. This is fixed by mocking the whole function since it wasn't really being tested anyway.
=> patch an internal function that is not tested

plugins/pulp_rpm/plugins/importers/yum/repomd/metadata.py
The NSA SIMP 5.1.X repodata contains a <revision /> tag which busts sync
with the following splat:
Downloading metadata from https://dl.bintray.com/simp/5.1.X/.
Starting new HTTPS connection (1): dl.bintray.com
Parsing metadata.
sync failed
Traceback (most recent call last):
File ".../sync.py", line 142, in run
metadata_files = self.get_metadata()
File ".../sync.py", line 226, in get_metadata
metadata_files.parse_repomd()
File ".../metadata.py", line 165, in parse_repomd
self.revision = int(element.text)
TypeError: int() argument must be a string or a number, not 'NoneType'
=> Fix repomd.xml parsing with an empty revision tag

plugins/pulp_rpm/plugins/migrations/0007_inventoried_custom_metadata.py, plugins/test/unit/plugins/migrations/test_0004_migrate.py
Remove the use of a model that no longer exists in master.
=> RepoImporter model was removed in mongoengine switch

plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/test/unit/plugins/importers/yum/test_sync.py
fixes #1348
This is built on some hefty changes made for 2.7, and (for the moment)
isn't wanted by anyone but me (re #928), but can find its way as far
back as pulp_rpm 2.4 if needed.
=> Add trailing slash to URL path, not the entire URL

plugins/pulp_rpm/plugins/importers/yum/repomd/alternate.py, plugins/test/unit/plugins/importers/yum/repomd/test_alternate.py, plugins/test/unit/plugins/importers/yum/test_sync.py
This was removed as part of making alternate content sources
thread-safe.
=> Remove cancel from the alternate content source usage.

plugins/pulp_rpm/plugins/importers/yum/listener.py, plugins/pulp_rpm/plugins/importers/yum/purge.py, plugins/pulp_rpm/plugins/importers/yum/upload.py, plugins/test/unit/plugins/importers/yum/test_listener.py, plugins/test/unit/plugins/importers/yum/test_purge.py, plugins/test/unit/plugins/importers/yum/test_upload.py
closes#494
https://pulp.plan.io/issues/494
Units with duplicate nevra are removed from the repo in case of sync or upload.
=> Handle repositories with duplicate NEVRA

common/pulp_rpm/common/ids.py, docs/tech-reference/yum-plugins.rst, plugins/pulp_rpm/plugins/importers/yum/repomd/alternate.py, plugins/pulp_rpm/plugins/importers/yum/repomd/metadata.py, plugins/pulp_rpm/plugins/importers/yum/repomd/packages.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/pulp_rpm/plugins/importers/yum/utils.py, plugins/test/unit/plugins/distributors/yum/test_publish.py, plugins/test/unit/plugins/importers/yum/repomd/test_alternate.py, plugins/test/unit/plugins/importers/yum/repomd/test_metadata.py, plugins/test/unit/plugins/importers/yum/test_sync.py, plugins/test/unit/test_util.py
Added the ability to support query-string-based authorization to repos
that support it, such as a SLES 12 repo
fixes #1358
https://pulp.plan.io/issues/1358
=> query_auth_token support

pulp-rpm.spec
* The types directory was deleted
* The json files in the types directory no longer exist
I was able to reproduce the error prior to this commit. After this commit I was able to successfully build pulp_rpm locally.
=> Removing vestiges left in spec file from mongoengine conversion

handlers/pulp_rpm/handlers/repolib.py, handlers/test/unit/handlers/test_repolib.py, plugins/pulp_rpm/plugins/distributors/yum/distributor.py, plugins/test/unit/plugins/distributors/yum/test_distributor.py
This addresses two separate issues. The first is the the Pulp server
config was used incorrectly when creating the consumer bind payload. The
second is that it was previously impossible to find a repository if it
did not have a 'name', which is not a requirement for creating a
repository in Pulp.
closes #1426
=> Fix consumer binding to RPM repositories.

plugins/pulp_rpm/plugins/distributors/iso_distributor/distributor.py, plugins/test/unit/plugins/distributors/iso_distributor/test_iso_distributor_distributor.py
ISO will be broken by this change: https://github.com/pulp/pulp/pull/2276
=> core passes a repo tranfer unit, not a repo_obj

extensions_admin/pulp_rpm/extensions/admin/iso/create_update.py, extensions_admin/pulp_rpm/extensions/admin/repo_create_update.py, extensions_admin/test/unit/extensions/admin/iso/test_create_update.py, plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/importers/iso/importer.py, plugins/pulp_rpm/plugins/importers/iso/sync.py, plugins/pulp_rpm/plugins/importers/yum/associate.py, plugins/pulp_rpm/plugins/importers/yum/existing.py, plugins/pulp_rpm/plugins/importers/yum/listener.py, plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py, plugins/pulp_rpm/plugins/importers/yum/purge.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/pulp_rpm/plugins/importers/yum/upload.py, plugins/pulp_rpm/plugins/migrations/0015_fix_distributor_units.py, plugins/test/unit/plugins/importers/yum/parse/test_treeinfo.py, plugins/test/unit/plugins/importers/yum/test_listener.py, plugins/test/unit/plugins/importers/yum/test_sync.py, plugins/test/unit/plugins/migrations/test_0015_fix_distributor_units.py
https://pulp.plan.io/issues/1425
To start: I tried not to get sucked into making general improvements.  But, in some cases, I could not help myself.  The refactor of treeinfo.py is a good example.  I decided to make that an object *mostly* to be consistent with the package sync object; and to simply things by not passing so many parameters everywhere.  So, most of the large blocks of code removed/added is git's way of dealing with the indentation change so when reviewing - keep in mind that *I did not write most of this code*.
Some other refactoring was necessary to split (but reuse) downloading and unit creation.  It was important to preserve the practice of only adding a unit after files were successfully downloaded.  When downloading is deferred (lazy), the downloading is skipped.
In …
=> ref #1373 - support deferred (Lazy) downloading.

plugins/pulp_rpm/plugins/migrations/0023_fix_translated_fields_type.py, plugins/test/unit/plugins/migrations/test_0022_rename_unit_id_fields.py, plugins/test/unit/plugins/migrations/test_0023_fix_translated_fields_type.py
Also adds test coverage for migration 22 and 23
https://pulp.plan.io/issues/1430
closes #1430
=> Adds migration 23 for mongoengine Validation errors

docs/user-guide/release-notes/2.8.x.rst, extensions_admin/pulp_rpm/extensions/admin/upload/errata.py, extensions_admin/test/unit/extensions/admin/upload/test_errata.py, plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/migrations/0024_errata_pushcount_string.py, plugins/test/unit/plugins/migrations/test_0024_errata_pushcount_string.py
* Reverts units_erratum.pushcount to be an StringField
* Adds migration 24 which converts all int or float
units_erratum.pushcount values to a string
* Adds tests for migration 24
* Adds release notes about field data quality changes
* Adjusts pulp-admin to have it submit pushcount as a string
https://pulp.plan.io/issues/1455
closes #1455
=> Fixes related to units_erratum.pushcount field

plugins/pulp_rpm/plugins/importers/yum/sync.py
RPMs are not necessarily located at baseurl/filename. The primary.xml
file may contain a relative path (from the baseurl) to the RPM itself.
=> Fix catalog entries to use the relativepath attribute.

plugins/pulp_rpm/plugins/importers/yum/sync.py
This will be added back once its performance problems have been
addressed. This effort is tracked in issue 1461.
=> Temporarily remove the call to remove_unit_duplicate_nevra.

plugins/test/unit/__init__.py
This is potentially the first of many, since at a minimum anything that uses celery triggers a load of server.conf, and everything celery, so we'll need this addition to be made to every plugin's tests.
I'll fire off the PRs for all the other plugins if this looks good, but it seemed prudent to do this one as a test PR before opening one for every plugin.
=> Block attempts to load server.conf when running unittests

plugins/pulp_rpm/plugins/db/models.py
I wrote out my reasoning here: https://pulp.plan.io/issues/1435#note-3
closes #1435
https://pulp.plan.io/issues/1435
=> Removes scary TODO about __cmp__ usage on NonMetadataPackage

plugins/pulp_rpm/plugins/importers/iso/importer.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/pulp_rpm/plugins/importers/yum/upload.py
Updating repository units from platform, due to them
not being reliably updated by plugins.  The code to do
this lives in platform, so we should be able to utilize it
from there
https://pulp.plan.io/issues/1467
re #1467
=> Update repository units from platform

plugins/pulp_rpm/plugins/distributors/iso_distributor/distributor.py, plugins/test/unit/plugins/distributors/iso_distributor/test_iso_distributor_distributor.py
This is the remaining work outside platform to fix #1480. The conversion from
old to new style repository was apparently not complete. It was simplest and
safest to go back to passing around the old style object, especially since the
workflow passes back and forth between the parent and child classes, in
platform and this plugin respectively.
re #1480
https://pulp.plan.io/issues/1480
=> iso distributor no longer fails with wrong type of Repository object

plugins/pulp_rpm/plugins/db/models.py
The _ns and _content_type_id fields are required to be defined
on the concrete class so they make no sense to be defined on the
abstract class.
=> Removes unecessary fields from RpmBase model

plugins/pulp_rpm/plugins/importers/yum/sync.py
Previously in 2.8 development code, when a group or category existed as an
orphan, the sync would incorrectly create the association so that the unit_id
was not unit_id of the existing unit in the DB. This caused search to break for
those units in that repo, which in turn caused copy to break.
https://pulp.plan.io/issues/1489
fixes #1489
=> existing group and category units get associated correctly during sync

docs/tech-reference/export-distributor.rst, extensions_admin/pulp_rpm/extensions/admin/export.py, extensions_admin/test/unit/extensions/admin/test_export.py
Also fixes a tiny doc bug that slipped through in a previous commit
https://pulp.plan.io/issues/1419
fixes #1419
This continues the discussion from https://github.com/pulp/pulp_rpm/pull/743#issuecomment-170027885
=> Add export distributer relative URL support to pulp-admin

extensions_admin/pulp_rpm/extensions/admin/contents.py
These fields were removed when pulp_rpm implemented lazy downloading,
but pulp-admin was still trying to use them.
https://pulp.plan.io/issues/1505
fixes #1505
=> pulp-admin updated to reflect removed distribution fields

extensions_admin/pulp_rpm/extensions/admin/export.py, extensions_admin/test/unit/extensions/admin/test_export.py
Right now both serve http/https are set to False during addition of distributor.
This prevents to export repo group if you do not explicitly specify those options.
And even if specifying options they will affect only current publish(i.e. override_config)
=> Enable publish over https by default in repo_groups export distributor.

plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py
The pulp_distribution.xml is missing checksum and checksum_type fields,
among other things. We have to allow these fields to be None for the
present.
=> Allow the catalog checksum and checksum_type to be None.

plugins/pulp_rpm/plugins/db/models.py
The parent class implements `list_files` as a method. This made it impossible to lazy download distributions.
=> remove `property` decorate for `list_files` in the distribution.

plugins/pulp_rpm/plugins/db/models.py
It is an error in pymongo >= 3 to create two indices with different
parameters and the same id. This commit eliminates a redundant
index in the Errata unit.
https://pulp.plan.io/issues/1528
re #1528
=> Do not index the errata id twice.

plugins/pulp_rpm/plugins/importers/iso/importer.py, plugins/pulp_rpm/plugins/importers/iso/sync.py, plugins/pulp_rpm/plugins/importers/yum/associate.py, plugins/pulp_rpm/plugins/importers/yum/listener.py, plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/pulp_rpm/plugins/importers/yum/upload.py
Call save_and_import_content().
Utilize cleanup pattern instead where usage doesn't
fit.
re #[1457](https://pulp.plan.io/issues/1457)
https://pulp.plan.io/issues/1457
=> Ensure file objects are cleaned up on error

plugins/pulp_rpm/plugins/importers/yum/utils.py, plugins/test/unit/test_util.py
In addition to explicitly declaring the kwargs to `__init__` and
`__call__`, I took a step back and considered if there was any value
to storing `path_append` and `ensure_trailing_slash` as stateful defaults.
Based on the current usage and my best judgement, there was no value in
that, and in fact having the same signature for both methods only made
things more confusing. Hopefully the stateful nature of of this class is
more clear, so in addition to being IDE-friendly, it's much easier for
humans to grok.
https://pulp.plan.io/issues/1442
fixes #1442
=> RepoURLModifier is more IDE- and user-friendly

plugins/pulp_rpm/plugins/profilers/yum.py, plugins/test/unit/plugins/profilers/profiler_mocks.py, plugins/test/unit/plugins/profilers/test_yum.py
This only really affects installing kernel packages, since that is the
only package I know of that allows installing multiple versions, but
without this fix pulp consumers will install all packages referenced by
errata that are being installed, even if one errata references a newer
version of a package than another errata.
https://pulp.plan.io/issues/1464
fixes #1464
=> When installing units referenced by errata, only install the latest unit

plugins/pulp_rpm/plugins/profilers/yum.py
fieldname `id` was changed to `errata_id` in the mongoengine conversion but these hard coded retrievals of the old field remain
https://pulp.plan.io/issues/1604
=> use errata_id rather than id

plugins/pulp_rpm/plugins/importers/yum/repomd/alternate.py
@bmbouter, This reverses a change done by the mongoengine conversion. I am very hesitant to merge this without review from someone who is intimately aware of the RPM conversion because it looks like this change was made deliberately to go along with many other related changes:
https://github.com/pulp/pulp_rpm/commit/944a05f7c131893a3fd46f1a67a53e4a618d95d6#diff-9a6038d8178eb03c0cbe334761cf67f4R79
This change does fix the case of https://pulp.plan.io/issues/1608 though.
=> use download path rather than file name

plugins/pulp_rpm/plugins/migrations/0025_export_relative_url.py, plugins/test/unit/plugins/migrations/test_0025_export_relative_url.py
This migration ensures that existing data gets updated
for PR #776
re #[1520](https://pulp.plan.io/issues/1520)
https://pulp.plan.io/issues/1520
=> Migration for relative_url

docs/tech-reference/yum-plugins.rst
It appears that "purge_orphaned" may have been a valid setting a long time ago
when we used grinder. Behaviorally, its use case is covered by the
remove_missing option.
fixes #1350
https://pulp.plan.io/issues/1350
=> removing an option from docs that is not actually present in code.

extensions_admin/pulp_rpm/extensions/admin/status.py, plugins/pulp_rpm/plugins/importers/yum/purge.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/test/unit/plugins/importers/yum/test_purge.py
https://pulp.plan.io/issues/1461
fixes #1461
See the redmine issues for a rude but effective way to generate a few dozen thousand duplicate packages to stress-test the duplicate nevra generator.
=> Re-institute purging duplicate NEVRA after an rpm repo sync

plugins/pulp_rpm/plugins/db/models.py
This uniqueness contstraint is now enforced by the platform for all content units.
https://pulp.plan.io/issues/1477
re: 1477
=> Removes uniqueness constraint on unit key

plugins/pulp_rpm/plugins/importers/yum/upload.py
https://pulp.plan.io/issues/1623
Should not be storing files for uploaded groups and categories.  This was unintentionally introduced during mongoengine conversion and Lazy work.
=> Fix package group/catagory upload.

plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py
Use os.path.relpath instead of str.lstrip when determining the relative
path of a distribution file during content import.
The Python method `str.lstrip` takes a list of chars, but this is
treated as a set of characters to strip from the left side of the
string, *not* as a substring to remove[0]. This was problematic for many
reasons, but would (rather entertainingly) determine the relative path
for distribution files based on the hostname of the worker and the
psuedo-random number generator used by tempdir and uuid.
to '/var/cache/pulp/\<worker\>@\<host\>/\<task-uuid\>/\<temp-dir\>/'
[0] https://docs.python.org/2/library/stdtypes.html#str.lstrip
closes #1654
=> Distribution storage path no longer dependant on hostname and PRNG.

plugins/test/unit/plugins/importers/iso/test_configuration.py
This commit fixes this error from flake8:
./plugins/test/unit/plugins/importers/iso/test_configuration.py:55:1: W293 blank line contains whitespace
=> Fix a flake8 error.

docs/user-guide/release-notes/2.8.x.rst, plugins/pulp_rpm/plugins/importers/iso/importer.py, plugins/pulp_rpm/plugins/importers/iso/sync.py, plugins/pulp_rpm/plugins/importers/yum/importer.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/test/unit/plugins/importers/iso/test_configuration.py, plugins/test/unit/plugins/importers/iso/test_importer.py, plugins/test/unit/plugins/importers/iso/test_sync.py, plugins/test/unit/plugins/importers/yum/test_sync.py
closes #1626
https://pulp.plan.io/issues/1626
1)This commit fixes the yum repo sync cancellation.
Now cancel_repo_sync() base class cancels the yum repo sync via calling sys.exit()
2)Some dead code is also removed.
3)Since DownloadConfig.finalize() is not called anymore, nectar config was changed
to use temporary space that tasks use and not use the /tmp for writing temporary files.
=> 1626 - Fix yum repo sync cancellation.

docs/tech-reference/yum-plugins.rst
By default if not specifying retain-old-count all versions available will be downloaded.
the remove-missing flag set to True seems like that does not affect its behaviour.
Proof : http://fpaste.org/327905/24613814/
=> Updating outated docs

common/pulp_rpm/common/constants.py, plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py, plugins/pulp_rpm/plugins/migrations/0026_remove_distribution_field.py, plugins/test/unit/plugins/importers/yum/parse/test_treeinfo.py, plugins/test/unit/plugins/migrations/test_0026_remove_distribution_field.py
The pulp_distribution_xml_file was present in earlier versions
of Pulp but is no longer used. It's not included in the
mongoengine Distribution model so it fails to hydrate when it is
present in the database.
closes #1742
https://pulp.plan.io/issues/1743
=> Adds migration 0026 which removes a field from Distribution units

plugins/pulp_rpm/plugins/migrations/0027_remove_checksum_type_field.py, plugins/test/unit/plugins/migrations/test_0027_unset_checksum_type.py
After migrating from 2.6 to 2.8, users could have database records that contain
'checksum_type' attribute that is set to null. This migration removes this field
from the documents.
https://pulp.plan.io/issues/1754
closes #1754
=> Removes checksum_type field from RPM unit documents in Mongo

handlers/pulp_rpm/handlers/rpmtools.py, handlers/test/unit/handlers/mock_yum.py, handlers/test/unit/handlers/test_rpmtools.py
When installing or updating packages in a consumer, pulp inspects the
yum transaction report to decide how to report its actions in the task
result. pulp was excluding the "TS_TRUEINSTALL" state, which yum uses as
the state of a transaction that updated or installed one of the special
packages that can be installed multiple times, such as the kernel.
Including (or rather, not excluding) that state in pulp's transaction
reporting lets those packages be included in pulp's task results.
https://pulp.plan.io/issues/1138
fixes #1138
=> Include "TS_TRUEINSTALL" as a valid package state

plugins/pulp_rpm/plugins/distributors/yum/metadata/updateinfo.py, plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/test/unit/plugins/distributors/yum/metadata/test_metadata.py
Errata units in Pulp contain all units in all repos that are linked to
errata with the same id, which was resulting in published errata
referencing packages that weren't actually available in the published
repo. This limits packages in published errata updateinfo XML to only
the packages that are contained in the published repo.
fixes #1366
https://pulp.plan.io/issues/1366
fixes #1548
https://pulp.plan.io/issues/1548
=> published updateinfo only contains units in repo

plugins/pulp_rpm/plugins/db/models.py, plugins/test/unit/plugins/db/test_models.py
https://pulp.plan.io/issues/1792
fixes #1792
=> Fixed bug in handling errata package lists that don't include a checksum

plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py, plugins/test/unit/plugins/importers/yum/parse/test_treeinfo.py
The PULP_DISTRIBUTION.xml file used to be saved from an upstream
repository and republished without modification. This is problematic
because files referenced by that file are filtered out during a publish.
This commit is a short-term work-around to that problematic workflow.
Without it, Pulp (or anything else using PULP_DISTRIBUTION.xml) will
attempt to download files that don't exist in the published repository.
fixes #1843
=> Regenerate PULP_DISTRIBUTION.xml on publish if necessary

extensions_admin/pulp_rpm/extensions/admin/upload/package.py, extensions_admin/test/unit/extensions/admin/upload/test_package.py, plugins/pulp_rpm/plugins/importers/yum/upload.py
https://pulp.plan.io/issues/1802
Looks like in 2.8 the metadata `checksum_type` property passed using the RPM upload API got changed to `checksumtype`.  Best I can tell, the issue was reopened to revert this backwards incomparable change.
=> Restore upload checksum type property.

docs/tech-reference/yum-plugins.rst, docs/user-guide/release-notes/2.9.x.rst, docs/user-guide/release-notes/index.rst, plugins/pulp_rpm/plugins/distributors/yum/configuration.py, plugins/pulp_rpm/plugins/distributors/yum/publish.py
If specified the full publication of the RPMs will be done even
when it is possible to make an incremental one.
closes #1158
https://pulp.plan.io/issues/1158
=> Add --force-full flag to publish command

plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/test/data/PULP_DISTRIBUTION.xml, plugins/test/unit/plugins/distributors/yum/test_publish.py
https://pulp.plan.io/issues/1856
re #1856
I'm hoping to see a test failure on el6, which is already fixed by https://github.com/pulp/pulp_rpm/pull/850
=> adding a unit test for _write_pulp_distribution_file

plugins/pulp_rpm/plugins/distributors/yum/publish.py
Element.getiterator() is depricated in Python 2.7, but still available. However, Element.iter()
is not available in Python 2.6.
=> Fixes incompatibility with Python 2.6

plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/test/unit/plugins/distributors/yum/test_publish.py
fixes #1869
https://pulp.plan.io/issues/1869
=> Removes symlink/file PULP_DISTRIBUTION.xml before writing a new file

docs/user-guide/recipes.rst, plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/pulp_rpm/plugins/importers/yum/upload.py, plugins/pulp_rpm/yum_plugin/util.py, plugins/test/unit/plugins/db/test_models.py, plugins/test/unit/plugins/importers/yum/test_upload.py
Handle pkglist for the same errata in different repositories.
Update errata metadata based on `updated` field.
closes #858
https://pulp.plan.io/issues/858
=> Fix sync and upload of the same erratum

common/pulp_rpm/common/ids.py, docs/user-guide/recipes.rst, docs/user-guide/release-notes/2.9.x.rst, extensions_admin/pulp_rpm/extensions/admin/contents.py, extensions_admin/pulp_rpm/extensions/admin/copy_commands.py, extensions_admin/pulp_rpm/extensions/admin/remove.py, extensions_admin/pulp_rpm/extensions/admin/rpm_repo/pulp_cli.py, extensions_admin/pulp_rpm/extensions/admin/units_display.py, extensions_admin/pulp_rpm/extensions/admin/upload/langpacks.py, plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/distributors/yum/metadata/package.py, plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/pulp_rpm/plugins/importers/yum/associate.py, plugins/pulp_rpm/plugins/importers/yum/importer.py, plugins/pulp_rpm/plugins/importers/yum/repomd/group.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/pulp_rpm/plugins/importers/yum/upload.py, plugins/pulp_rpm/plugins/serializers.py, plugins/setup.py
- PackageLangpacks model is done
- yum importer is extended to parse and save PackageLangpacks
- yum distributor is extended to write out PackageLangpacks
- adds create, copy, search, and remove capabilities for pulp-admin
- upload as part of a comps.xml upload via pulp-admin also works
- documentation for create, copy, search, and remove added to recipes
- release note added
I also fixed a few small, existing docs errors on the recipes page.
I want pulp-smash to do the actual upload/sync/publish testing, but that is blocked currently on the availability of `<langpacks>` tags in the demo repos on fedorapeople. As such, you should manually sync from a [repo that contains langpacks](https://pulp.plan.io/issues/1367#note-14) and verify that when published it is included in the published …
=> Adds <langpacks> support in the comps file

common/pulp_rpm/common/constants.py, extensions_admin/pulp_rpm/extensions/admin/export.py, extensions_admin/test/unit/extensions/admin/test_export.py, plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/test/unit/plugins/distributors/yum/test_publish.py, plugins/test/unit/plugins/importers/yum/test_sync.py
Previously, incremental exports were in a custom format where each erratum and
RPM were written to disk, along with a set of JSON files with unit metadata.
This required special handling of incremental imports that was significantly
different a "regular" repo sync.
This patch adds a new `incremental_export_repomd` distributor option. When this
is set, the incremental repo export generates metadata so that the on-disk
files can be synced via the typical yum sync process. Note that you would not
want to remove old units when doing this, since it would remove any units not
in the incremental :koala:.
Fixes #1543
https://pulp.plan.io/issues/1543
=> Allow for new `incremental_export_repomd` exporter distributor config option

plugins/pulp_rpm/plugins/importers/yum/sync.py
closes #1775
https://pulp.plan.io/issues/1775
=> Do not skip sync if units were removed from the repository.

plugins/pulp_rpm/plugins/importers/yum/listener.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/test/unit/plugins/importers/yum/test_listener.py
The class was identical in every way to the RPMListener, except it called
sync.add_drpm instead of sync.add_rpm. As it turns out, sync.add_drpm was
just a direct reference to sync.add_rpm, so the two classes were 100%
equivalent.
=> removed DRPMListener, which was redundant

docs/tech-reference/index.rst, docs/tech-reference/rpm.rst
This adds an explanation of the various types of RPM content to our
technical documenation. It should give new contributors a good overview
of what RPM content is, where it comes from, and where else to read
documentation for a more in-depth understanding.
=> Add documentation on RPM content to the technical docs

plugins/pulp_rpm/plugins/db/models.py, plugins/test/unit/plugins/db/test_models.py
It is needed because mongoengine does not allow to modify items in
the list and to add a new ones to the list at the same time.
And sometimes we are in this situation during the update of the erratum.
closes #1910
https://pulp.plan.io/issues/1910
=> Save modifications to the erratum pkglist before adding new collections.

plugins/pulp_rpm/plugins/migrations/0029_remove_rpm_unused_fields.py, plugins/test/unit/plugins/migrations/test_0029_remove_rpm_unused_fields.py
closes #1952
https://pulp.plan.io/issues/1952
The `filelist` and `_erratum_references` were present in earlier versions
of Pulp but are no longer used. They are not included in the mongoengine
RPM model anymore.
=> Remove unused fields from units_rpm collection.

plugins/pulp_rpm/plugins/migrations/0030_remove_errata_unused_fields.py, plugins/test/unit/plugins/migrations/test_0030_remove_errata_unused_fields.py
closes #1931
https://pulp.plan.io/issues/1931
The `_rpm_references` field was present in earlier versions of Pulp
but is no longer used. It is not included in the mongoengine
Errata model anymore.
=> Remove unused fields from units_erratum collection

plugins/pulp_rpm/plugins/migrations/0028_standard_storage_path.py, plugins/test/unit/plugins/migrations/test_0028_standard_storage_path.py
https://pulp.plan.io/issues/1945
Some of the plugins released with early 2.8 had been updated (incorrectly) to use the new platform storage model (introduced in 2.8) for unit files. This resulted in a period of time when units were created with storage paths that should have ended with the file names but did not. Apparently the ISO importer was one of these plugins but was fixed in later 2.8 releases. The ISO storage-path migration just needs to be updated to detect these units and correct the storage path.
Also handles distribution units that don't contain a `variant` in the document.  Defaults to empty string `''` which matches what the model object will do.
=> Fix migration #28

plugins/pulp_rpm/plugins/importers/iso/sync.py, plugins/pulp_rpm/plugins/importers/yum/existing.py, plugins/pulp_rpm/plugins/importers/yum/sync.py
https://pulp.plan.io/issues/1897
To start with, these changes are a hack.  The importer code is tightly coupled to downloading and a mixture of procedural and object-based (not object oriented) programming.  To fix this correctly, a significant amount of the importer would need to be rewritten (and should be anyway).  To minimize changes this late in the release cycle, I just fixed this as best I could within current design.
Instead of creating catalog entries for unit that would downloaded, I passed the initialized catalog object everywhere that did unit association.  I added fixed unit tests as best I could but most of them have been disabled.
=> Add catalog entries when units already exist.

plugins/pulp_rpm/plugins/db/models.py, plugins/test/unit/plugins/db/test_models.py, plugins/test/unit/plugins/importers/yum/parse/test_treeinfo.py
Unit keys cannot be null or missing, since MongoEngine will just leave
them off the document. In particular, this broke migration 28.
Note this is the same as https://github.com/pulp/pulp_rpm/pull/883, just reopened against 2.8-dev
=> Change ``variant`` to default to an empty string

plugins/pulp_rpm/plugins/distributors/yum/metadata/metadata.py
https://pulp.plan.io/issues/1288
fixes #1288
=> Log overwriting metadata at debug instead of warn.

plugins/pulp_rpm/plugins/distributors/yum/metadata/updateinfo.py, plugins/test/unit/plugins/distributors/yum/metadata/test_updateinfo.py
close #1783
https://pulp.plan.io/issues/1783
=> Eliminate duplicated pkglists during XML generation.

common/pulp_rpm/common/constants.py, docs/tech-reference/export-distributor.rst, docs/user-guide/release-notes/2.9.x.rst, extensions_admin/pulp_rpm/extensions/admin/export.py, extensions_admin/pulp_rpm/extensions/admin/repo_create_update.py, extensions_admin/test/unit/extensions/admin/test_export.py, extensions_admin/test/unit/extensions/admin/test_repo_create_update.py
This adds two behaviors that are closely related. 1619 actually depended on doing part of 1969 first. I think it makes sense to review them together, hence the two commits in one PR.
https://pulp.plan.io/issues/1969
https://pulp.plan.io/issues/1619
=> checksum_type setting for repo and group export distributor

plugins/pulp_rpm/plugins/importers/yum/associate.py, plugins/pulp_rpm/plugins/migrations/0031_regenerate_repo_unit_counts.py, plugins/test/unit/plugins/migrations/test_0031_regenerate_repo_unit_counts.py
The metadata units have an overwrite functionaity whereby newer
units overwrite older units if they have the same unit key. The
unit being overwritten is deleted and the new one is added. The
unit being deleted did not have disassociate called so the
unit count would be wrong for these unit types after multiple
copies.
This comes with a migration which regenerates the unit counts
for all repos fixing any incorrect data as a result of the bug.
HEAD of pulp-smash passes and all unit tests pass
https://pulp.plan.io/issues/1979
fixes #1979
=> Overwriting a metadata unit during copy disassociates first

plugins/pulp_rpm/plugins/migrations/0032_ensure_variant_field.py, plugins/test/unit/plugins/migrations/test_0032_ensure_variant_field.py
https://pulp.plan.io/issues/1955
Ensure `variant` is set on distribution documents.  Intended to match the default value `''` set by the model object.
Related to: https://github.com/pulp/pulp_rpm/pull/883
=> Ensure variant is set on distribution units.

docs/user-guide/release-notes/2.9.x.rst
The last note had a couple of typos.
The note I removed about checksum type is a duplicate of one above, and probably made its way in via a merge conflict resolution.
=> Fixes mistakes in 2.9 release notes.

docs/user-guide/recipes.rst
Given a langpack where "name" is `myapp` and "install" is `myapp-%s`, when the `myapp` package is installed, an additional package named `myapp-en`, `myapp-fr`, etc. may be installed. Make the documentation in `docs/user-guide/recipes.rst` match this work flow.
=> Fix typo in langpacks documentation

plugins/pulp_rpm/plugins/distributors/yum/metadata/updateinfo.py, plugins/test/unit/plugins/distributors/yum/metadata/test_metadata.py, plugins/test/unit/plugins/distributors/yum/metadata/test_updateinfo.py
closes #2020
https://pulp.plan.io/issues/2020
=> Handle multiple checksums in the erratum package list during publish.

docs/Makefile, docs/conf.py, docs/user-guide/installation.rst
Intersphinx was preventing the strict mode from being enabled
due to docs being built in a network isolated mock environment.
Intersphinx was also going to break because it is tied
to URLs from ReadTheDocs. Now intersphinx is removed, and
usage of it was dropped from the content. Strict Sphinx
mode is now enabled.
https://pulp.plan.io/issues/2034
re #2034
=> Remove intersphinx and enable Strict mode

plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/distributors/yum/metadata/updateinfo.py, plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/test/unit/plugins/distributors/yum/metadata/test_metadata.py, plugins/test/unit/plugins/distributors/yum/metadata/test_updateinfo.py, plugins/test/unit/plugins/distributors/yum/test_publish.py
The Errata publish performance became a problem recently
due to lots of db calls being made as Errata metadata is filtered
to only refer to packages in this specific repo.
This PR causes all the repo's NEVRA to be stored in memory once
and all filtering to work out of that data structure. This avoids
searching the db everytime for the NEVRA specified by the erratum
so it does much less work than before.
https://pulp.plan.io/issues/1949
fixes #1949
=> Erratum publish reads repo nevra into memory

docs/conf.py, docs/user-guide/configuration.rst, docs/user-guide/release-notes/2.1.x.rst, docs/user-guide/release-notes/2.2.x.rst, docs/user-guide/release-notes/2.4.x.rst, docs/user-guide/release-notes/2.5.x.rst
The RTD links are replaced with new links pointing to
https://docs.pulpproject.org/
https://pulp.plan.io/issues/2034
re #2034
=> Removes all RTD references

plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/migrations/0033_checksums_and_templates.py, plugins/test/unit/plugins/db/test_models.py, plugins/test/unit/plugins/migrations/test_0033_checksums_and_templates.py
These snippets were mistakenly being sent through the "remove_fake_element"
function, which would slice them incorrectly and shave off a single character.
This was ok most of the time, because it would be a white space character. But
occasionally it was the final ">" of the XML.
fixes #2037
https://pulp.plan.io/issues/2037
=> "other" and "filelists" XML snippet processing fixed to not do slicing

docs/user-guide/release-notes/2.8.x.rst, plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/distributors/yum/metadata/updateinfo.py, plugins/test/unit/plugins/db/test_models.py, plugins/test/unit/plugins/distributors/yum/metadata/test_updateinfo.py
Additionally, this enables sync to fix any values of reboot_suggested that are
incorrect due to having previously sync'd from a pulp that had published with
the previous behavior.
fixes #2032
https://pulp.plan.io/issues/2032
=> Fixes publish of Errata with reboot_suggested == False

plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/error_codes.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/pulp_rpm/yum_plugin/util.py, plugins/test/unit/plugins/db/test_models.py
The original PR is here:  https://github.com/pulp/pulp_rpm/pull/925/files
This PR contains the [three recommended fixes](https://github.com/pulp/pulp_rpm/pull/925#issuecomment-230866214).
- Brings back RPM1007
- Causes update_needed() to return False in the case that either
`updated` field is an empty string
- Adjust the logging to cause 1 line to be logged for all errata
with non-empty and not recognized values for the `updated`
field.
=> 2048 american stout

extensions_admin/pulp_rpm/extensions/admin/repo_create_update.py, plugins/pulp_rpm/plugins/distributors/yum/configuration.py, plugins/pulp_rpm/plugins/distributors/yum/publish.py
Revert "added packages_directory option for yum_distributor"
This reverts commit ac76ec18f3662dc6c95e34f70565240265b6fa2d.
This feature is being pulled so that it can be re-introduced
later when it is working.
The docs portain is being negative commited separately so there
are no 2.9.x.rst changes in this negative commit.
https://pulp.plan.io/issues/1976
re #1976
=> Revert "added packages_directory option for yum_distributor"

plugins/pulp_rpm/plugins/migrations/0028_standard_storage_path.py
Migration 28 can take a long time. This outputs a banner to
the logs and the foreground of pulp-manage-db warning the user
that it could take a long time.
https://pulp.plan.io/issues/2060
re #2060
=> Adds banner warning about migration runtime

docs/user-guide/release-notes/2.9.x.rst
This feature is being pulled from 2.9.0.
https://pulp.plan.io/issues/1976
re #1976
=> Removes packages_directory release note

docs/tech-reference/iso-rsync-distributor.rst, plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/distributors/iso_rsync_distributor/distributor.py, plugins/pulp_rpm/plugins/distributors/iso_rsync_distributor/publish.py, plugins/pulp_rpm/plugins/error_codes.py, plugins/setup.py
closes #1963
https://pulp.plan.io/issues/1963
=> Adds ISO rsync distributor

plugins/pulp_rpm/plugins/distributors/iso_rsync_distributor/distributor.py, plugins/pulp_rpm/plugins/distributors/rsync/distributor.py
The platform code performs the cancel. The methods on the distributor are not necesary.
=> Removes cancel_publish_repo methods from the rsync distributors

plugins/pulp_rpm/plugins/db/models.py, plugins/test/unit/plugins/db/test_models.py
closes #2135
https://pulp.plan.io/issues/2135
=> Use `templatetag` to escape Django syntax characters in templates

docs/tech-reference/iso-rsync-distributor.rst, docs/tech-reference/rsync-distributor.rst
According to the JSON specification, objects and arrays must not have
trailing commas. The following are invalid:
{"foo": "bar",}
[1, 2, 3,]
Make the sample JSON code in the rsync distributor documentation pages
valid. Also, reformat the JSON code samples with `json_reformat`, so
that indentation is consistent, instead of using a mixture of one, three
and four spaces.
=> Make sample JSON code valid & pretty

common/pulp_rpm/common/constants.py, docs/tech-reference/yum-plugins.rst, docs/user-guide/features.rst, docs/user-guide/recipes.rst, docs/user-guide/release-notes/2.10.x.rst, extensions_admin/pulp_rpm/extensions/admin/status.py, extensions_admin/test/unit/extensions/admin/test_status.py, plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/error_codes.py, plugins/pulp_rpm/plugins/importers/yum/associate.py, plugins/pulp_rpm/plugins/importers/yum/config_validate.py, plugins/pulp_rpm/plugins/importers/yum/existing.py, plugins/pulp_rpm/plugins/importers/yum/parse/rpm.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/pulp_rpm/plugins/importers/yum/upload.py, plugins/test/unit/plugins/importers/yum/parse/test_rpm.py, plugins/test/unit/plugins/importers/yum/test_sync.py
The features introduced in #1991 (https://pulp.plan.io/issues/1991) only act
as filters based on whether or not a package is signed, and the short key ID
of the key used to generate that signature. This changes any reference to
"verification" introduced with those changes to "GPG Key ID filtering", and
in general attempted to clarify that this is not a security feature, while
still leaving it possible to (hopefully) do GPG package signature verification
in a future version.
fixes #2188
https://pulp.plan.io/issues/2188
=> Reclassify signature verification as signature and key ID filtering

docs/tech-reference/rsync-distributor.rst
The RPM rsync distributor uses SSH keys for authentication, and it must
be told where to find a private key for authentication. This key must
have certain permissions, or else SSH will refuse to use it. Update the
documentation accordingly.
=> Clarify needed permissions for ssh_identity_file

docs/user-guide/release-notes/2.11.x.rst, plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/test/unit/plugins/importers/yum/test_sync.py
This was prompted by the need to sync kickstart trees related to Project
Atomic, which do not have yum repository metadata in the kickstart directory.
fixes #2211
https://pulp.plan.io/issues/2211
=> yum_importer can sync a distribution that does not also have yum repo metadata

plugins/test/unit/plugins/importers/yum/test_sync.py
Unit association is no longer performed in `RepoSync.add_rpm_unit`.
=> Fix signature tests

docs/tech-reference/export-distributor.rst
The extra blank line caused a single definition list entry to appear as
two definition list entries.
=> Drop spurious blank line from docs

plugins/pulp_rpm/plugins/importers/yum/listener.py
re #2190
https://pulp.plan.io/issues/2190
=> Fix unit association if unit was downloaded for the second time

plugins/test/unit/__init__.py
Some unit tests failed under django 1.9 without this setup call.
https://pulp.plan.io/issues/2257
fixes #2257
=> Adds a required django.setup() call to unit tests.

common/pulp_rpm/common/constants.py, docs/tech-reference/iso-plugins.rst, docs/tech-reference/iso-rsync-distributor.rst, docs/user-guide/release-notes/2.11.x.rst, extensions_admin/pulp_rpm/extensions/admin/iso/create_update.py, extensions_admin/test/unit/extensions/admin/iso/test_create_update.py, plugins/pulp_rpm/plugins/distributors/iso_distributor/configuration.py, plugins/pulp_rpm/plugins/distributors/iso_distributor/distributor.py, plugins/pulp_rpm/plugins/distributors/iso_rsync_distributor/publish.py, plugins/test/unit/plugins/distributors/iso_distributor/test_iso_distributor_configuration.py, plugins/test/unit/plugins/distributors/iso_distributor/test_iso_distributor_distributor.py
The relative url works in the same way it does for the Yum distributor. When then ISO distributor is
used as predistributor, the ISO rsync distributor uses the relative url of the predistributor when
publishing.
re: 2132
https://pulp.plan.io/issues/2132
=> Updates API and pulp-admin to accept relative url configuration for ISO distributor.

plugins/pulp_rpm/plugins/migrations/0036_remove_srpm_drpm_checksum_type_field.py, plugins/test/unit/plugins/migrations/test_0036_remove_srpm_drpm_checksum_type_field.py
closes #2278
https://pulp.plan.io/issues/2278
=> Remove no longer used checksum_type field from srpm/drpm collections.

plugins/pulp_rpm/plugins/importers/yum/existing.py, plugins/pulp_rpm/plugins/importers/yum/sync.py
https://pulp.plan.io/issues/2354
Adding catalog entries in 2.8 really just got shoehorned in as best we could but the code organization and procedural flows made it very difficult.  This patch is not pretty but resolves the issue.
=> Fix URL in catalog entry created for existing package.

plugins/pulp_rpm/plugins/importers/iso/sync.py
Added check to sync.add_catalog_entries to ignore units not coming from
Pulp ISO manifest.
closes #2195
https://pulp.plan.io/issues/2195
After this commit no exceptions are begin raised anymore. But I would like to know what @jortel thinks about this because I think this arises from fix https://pulp.plan.io/issues/1897 and I'm not sure how it should work and if it does work correctly now.
=> Fix ISO sync of already existing units

plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/importers/yum/existing.py, plugins/test/unit/plugins/db/test_models.py
This commit eliminates the following unnecessary operations:
- addition of  RPM/SRPM/DRPM to PackageCatalog when unit is already
associated with the repository
- re-association of RPM/SRPM/DRPM with repository when such
association already exists
- additional `save()` to errata model even when no new collections
were added
closes #2457
https://pulp.plan.io/issues/2457
=> Reduce number of writes to db during sync

plugins/pulp_rpm/plugins/error_codes.py, plugins/pulp_rpm/plugins/importers/yum/repomd/metadata.py, plugins/pulp_rpm/plugins/importers/yum/sync.py
Sync task will fail when:
- any required metadata files, like filelists.xml, are missing
- filelists.xml or other.xml does not contain metadata for all
the packages in the repository
closes #1287
https://pulp.plan.io/issues/1287
=> Fail sync and report early in case of inconsistency in metadata

common/pulp_rpm/common/progress.py, common/test/unit/common/server/test_progress.py
Solution: When some downloads fail, raise an exception with the list of all
errors collected during the sync.
closes #2006
https://pulp.plan.io/issues/2006
=> Problem: ISO Importer reports a vague failure message

common/pulp_rpm/common/constants.py, common/pulp_rpm/common/file_utils.py, common/test/unit/common/test_file_utils.py, docs/user-guide/release-notes/2.12.x.rst, docs/user-guide/release-notes/index.rst, plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/pulp_rpm/plugins/importers/yum/parse/rpm.py, plugins/pulp_rpm/plugins/importers/yum/repomd/primary.py, plugins/pulp_rpm/plugins/migrations/0037_rpm_primary_repodata_new_location.py, plugins/test/unit/plugins/db/test_models.py, plugins/test/unit/plugins/migrations/test_0037_rpm_primary_repodata_new_location.py
closes #1976
https://pulp.plan.io/issues/1976
=> Change publish layout to Packages/[a-z]/*

plugins/pulp_rpm/plugins/importers/iso/sync.py, plugins/pulp_rpm/plugins/importers/yum/purge.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/test/unit/plugins/importers/yum/test_purge.py
https://pulp.plan.io/issues/2503
Looks like only RPM, DRPM and ISO units are removed as part of the _purge_ logic.  This means the distributions and YUM metadata files are not removed which may be intentional but not sure.  In any case this patch is only concerned with ensuring that when `--remove-missing` logic is applied, it removes catalog entries as well.  Catalog entries need to be cleaned up regardless of the current download policy.
=> Delete catalog entries for units no longer in the remote repository.

plugins/pulp_rpm/plugins/importers/yum/purge.py
I couldn't actually reproduce the cursor timeout using a variety of
configurations for my VM but using a batch size here didn't seem to slow
down syncs significantly when I benchmarked this change.
fixes #2502
https://pulp.plan.io/issues/2502
=> Prevent a cursor timeout when syncing rpm repos

plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/migrations/0038_errata_pkglist_duplicates_cleanup.py, plugins/test/unit/plugins/db/test_models.py, plugins/test/unit/plugins/migrations/test_0038_errata_pkglist_duplicates_cleanup.py
Pkglists should no longer be extended with the collections for the same repository.
Migration is introduced to clean up duplicates in the affected pkglists.
closes #2568
https://pulp.plan.io/issues/2568
=> Fix the errata merge logic

plugins/pulp_rpm/plugins/distributors/yum/metadata/updateinfo.py, plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/test/unit/plugins/distributors/yum/metadata/test_metadata.py, plugins/test/unit/plugins/distributors/yum/metadata/test_updateinfo.py, plugins/test/unit/plugins/distributors/yum/test_publish.py
Stop publishing errata with empty pkglist.
If an erratum has multiple pkglists, publish only non-empty ones.
closes #2559
https://pulp.plan.io/issues/2559
=> Filter out empty errata pkglists during publish

plugins/pulp_rpm/plugins/importers/yum/parse/rpm.py, plugins/pulp_rpm/yum_plugin/util.py, plugins/test/unit/plugins/importers/yum/parse/test_rpm.py, plugins/test/unit/yum_plugin/test_util.py
https://pulp.plan.io/issues/1903
Seemed to make more sense to decode entire primary XML fragment instead of doing it element-by-element.  This approach is simpler and more comprehensive.
=> Fix non-utf8 when found in uploaded RPMs.

plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/distributors/yum/metadata/updateinfo.py, plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/test/unit/plugins/db/test_models.py, plugins/test/unit/plugins/distributors/yum/metadata/test_metadata.py, plugins/test/unit/plugins/distributors/yum/metadata/test_updateinfo.py, plugins/test/unit/plugins/distributors/yum/test_publish.py
Published errata collection names are unique per-repo
This ended up being a pain because of how much filtering work we were
doing in the updateinfo XML context. I was able to make it work as-is,
and just about had a PR up, but then Tanya posted this PR: 
https://github.com/pulp/pulp_rpm/pull/1024
That PR opened up a possibility that I hasn't seriously considered,
which was to move the unit/repo filtering logic out of the XML 
generation context. Now, the UpdatinfoXMLFileContext writes *whatever
you tell it to write* in the add_unit_metadata step, and the filtering
takes place in calling Publish steps. Since the PublishErrataStep
knows what repo it's publishing (er, "distributing"), all of the 
business of trying to pull a repo_id off the conduit can go away.
Buried deep in all of this is …
=> Ensure unique errata collection names on publish

plugins/pulp_rpm/plugins/importers/iso/importer.py
This addresses a regression introduced in 2.8.0. Prior to this release
of Pulp, uploading an ISO that Pulp already had stored would use the
existing ISO in the upload step and succeed. This change restores the
prior behavior, removing this regression.
https://pulp.plan.io/issues/2274
closes #2274
=> Allow ISOs to be re-uploaded

plugins/pulp_rpm/plugins/importers/yum/parse/rpm.py, plugins/pulp_rpm/plugins/importers/yum/repomd/metadata.py, plugins/test/unit/plugins/importers/yum/parse/test_rpm.py
closes #2622
https://pulp.plan.io/issues/2622
=> Fix sync for the case when primary.xml contains non-ASCII characters

pulp-rpm.spec
Add provides for python2-* packages.  Fedora downstream packages are
named python2-* and provide python-*.  Upstream needs to mirror this for
dependency resolution to work properly
re #2687
=> Add provides for python2-* packages

plugins/pulp_rpm/plugins/importers/iso/sync.py, plugins/pulp_rpm/plugins/importers/yum/sync.py
https://pulp.plan.io/issues/2704
A better fix would be to call `set_storage_path()` when _new_ models are instantiated.  Since models are created in multiple places, I don't want to take the chance of missing something and causing a regression.  This fix less than ideal but lower risk.
=> Ensure path in catalog entry matches storage path for existing units.

plugins/pulp_rpm/plugins/importers/yum/sync.py
Catch NotUniqueError exception rather than explicitly check
the existence of the erratum unit.
closes #2721
https://pulp.plan.io/issues/2721
=> Eliminate race condition during errata sync

plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/test/unit/plugins/importers/yum/test_sync.py
We can now sync from repository which have the same package more than
once enlisted in the metadata.
closes #2605
https://pulp.plan.io/issues/2605
=> Ignore duplicate packages in metadata

pulp-rpm.spec
The Source0 currently does not lead to the correct source file.
This updates the spec file and renames the source to what would be
the expected source name.
ref #2784
https://pulp.plan.io/issues/2784
=> Update spec files Source0

plugins/pulp_rpm/plugins/distributors/iso_rsync_distributor/publish.py, plugins/pulp_rpm/plugins/distributors/rsync/publish.py
Corrects the rsync distributor fast-forward logic so that it
uses the proper date range to determine which units to include.
This fixes an issue where units were not being published if the
association, predistributor publish and rsync publish occurred
in a certain order.
closes #2532
https://pulp.plan.io/issues/2532
=> Fix rsync distributor skipping units

plugins/pulp_rpm/plugins/importers/iso/importer.py, plugins/pulp_rpm/plugins/importers/iso/sync.py
Fixing a bug whereby an ISO or file gets updated and then reimported into
pulp by sync or upload. We're now disassociating the original content
unit and replacing it with the new one. Matching on the name of the
unit.
fixes #2773
https://pulp.plan.io/issues/2773
=> Fixing dupe ISO units after file update

plugins/pulp_rpm/plugins/importers/iso/sync.py
Forgot to update the code in #2773 when associating existing content with an iso repo. This fixes that.
fixes #3047
https://pulp.plan.io/issues/3047
=> Calling method to remove old isos by name before associating them

docs/tech-reference/yum-plugins.rst, plugins/pulp_rpm/plugins/distributors/yum/metadata/repomd.py
See https://github.com/pulp/pulp_rpm/pull/1065#issuecomment-339140847
=> Additional changes related to #1065

plugins/pulp_rpm/plugins/importers/iso/sync.py
The repo_units value was emptying after iterating through it because it
was a generator and not a list.
fixes #3100
https://pulp.plan.io/issues/3100
=> Changing the type of repo_units to list from generator

plugins/pulp_rpm/plugins/error_codes.py, plugins/pulp_rpm/plugins/importers/yum/upload.py
Raise coded exception.  Removed the logging here because exceptions are caught and logged in `upload()`.
https://pulp.plan.io/issues/3090
Requires: https://github.com/pulp/pulp/pull/3212
=> Raise coded exception for invalid package header.

plugins/pulp_rpm/plugins/migrations/0040_errata_pkglist_collection.py
This is needed for the case when migration is re-run after interruption.
closes #3130
https://pulp.plan.io/issues/3130
=> Ensure indexes are created before erratum pkglists are getting migrated

docs/tech-reference/iso-rsync-distributor.rst, docs/tech-reference/rsync-distributor.rst
F27+ changed the behavior of semanage to set a selinux boolean by
default, but not change its current state. Update docs to advise users
of this to avoid confusion when rsync distributors fail to run with
selinux in F27.
closes #3347
https://pulp.plan.io/issues/3347
=> Advise users on using setsebool to set pulp_manage_rsync selinux boolean

plugins/pulp_rpm/plugins/importers/yum/upload.py
None was a valid value for unit_key until a commit began requiring it.
This fixes the backward incompatible change.
fixes #3307
https://pulp.plan.io/issues/3307
=> Making unit_key a non-required field

docs/user-guide/features.rst
Pulp_rpm supports the modularity content to the repo mirroring extent.
Fixes: #3353
https://pulp.plan.io/issues/3353
=> Document modularity support

docs/user-guide/features.rst
Pulp has some limited boolean dependencies support.
This patch updates the documentation to reflect it.
Fixes: #3339
https://pulp.plan.io/issues/3339
=> Document boolean dependencies support

common/pulp_rpm/common/ids.py, docs/tech-reference/yum-plugins.rst, docs/user-guide/release-notes/2.16.x.rst, extensions_admin/pulp_rpm/extensions/admin/upload/errata.py, extensions_admin/test/unit/extensions/admin/upload/test_errata.py, plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/distributors/yum/metadata/updateinfo.py, plugins/pulp_rpm/plugins/importers/yum/repomd/updateinfo.py, plugins/pulp_rpm/plugins/migrations/0042_add_suse_fields_to_errata.py, plugins/pulp_rpm/yum_plugin/util.py, plugins/test/unit/plugins/db/test_models.py, plugins/test/unit/plugins/migrations/test_0042_add_suse_fields_to_errata.py
Metadata sync currently works with `query_auth_token`. Removing
`TYPE_ID_ERRATA` from `QUERY_AUTH_TOKEN_UNSUPPORTED` allows pulp to sync
`updateinfo.xml` from SLES, and generate errata content.
Add relogin_suggested, restart_suggested to errata model since these
fields are available on SUSE metadata.
Add migrations to create relogin_suggested and restart_suggested fields
to pulp's errata models in database
fixes #3377
https://pulp.plan.io/issues/3377
=> Add support for suse errata

common/pulp_rpm/common/constants.py, docs/tech-reference/yum-plugins.rst, docs/user-guide/release-notes/2.16.x.rst, plugins/pulp_rpm/plugins/distributors/yum/configuration.py, plugins/pulp_rpm/plugins/distributors/yum/metadata/repomd.py, plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/pulp_rpm/yum_plugin/util.py, plugins/test/unit/plugins/distributors/yum/metadata/test_metadata.py, plugins/test/unit/plugins/distributors/yum/test_configuration.py, plugins/test/unit/plugins/distributors/yum/test_publish.py, plugins/test/unit/yum_plugin/test_util.py
In certain environments, GPG private keys are secured in an HSM,
instead of being in a keyring, unprotected by a passphrase.
This allows one to change the signing command, and passes
repository ID information as an envronment variable into
the signing command, in case different keys need to be used.
Fixes: #3444
https://pulp.plan.io/issues/3444
=> Extensible way to GPG-sign repository metadata.

docs/tech-reference/yum-plugins.rst, plugins/pulp_rpm/plugins/distributors/yum/configuration.py, plugins/test/unit/plugins/distributors/yum/test_configuration.py
Since the command configured with gpg_cmd executes remotely as user apache,
a user should not be allowed to change it via a distributor config or
an override at publish time.
Fixes #3474
https://pulp.plan.io/issues/3474
=> gpg_cmd is not allowed as plugin or override configuration

plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/profilers/yum.py, plugins/pulp_rpm/plugins/serializers.py, plugins/test/unit/plugins/db/test_models.py, plugins/test/unit/plugins/profilers/test_yum.py
To improve both performance and memory consumption of celery
workers during applicability regeneration.
Serializer for Errata now deals wit unique pkglists as well.
closes #3172
https://pulp.plan.io/issues/3172
=> Use aggregation to identify unique errata pkglists

.travis.yml, pulp_rpm/app/constants.py, pulp_rpm/app/models.py
closes #3199
https://pulp.plan.io/issues/3199
=> Add model fields for Package type

plugins/pulp_rpm/plugins/db/models.py
The diff below causes the selection of input to be sanitized to be
greedy instead of non-greedy. This causes it work sanitize more
data in the cases of invalid entries such as Changelogs with too
many <changelog></changelog> sections in one rpm.
This fix is very safe for several reasons:
1. Escaping all data for the template layer should be safe. This is
essentially user-provided data given that we got it from the
internet, so it probably all should be escaped. Since this fixes
this issue I'm not going to rewrite the sanitizer now to keep it
low-risk.
2. The extra-greedyness added is still limited by the end tag
matched
https://pulp.plan.io/issues/3535
closes #3535
=> Sanitize Invalid Changelogs Too

docs/tech-reference/yum-plugins.rst, docs/user-guide/release-notes/2.17.x.rst, docs/user-guide/release-notes/index.rst, plugins/pulp_rpm/plugins/distributors/yum/configuration.py, plugins/pulp_rpm/yum_plugin/util.py, plugins/test/unit/plugins/distributors/yum/test_configuration.py, plugins/test/unit/plugins/distributors/yum/test_publish.py, plugins/test/unit/yum_plugin/test_util.py
https://github.com/pulp/pulp_rpm/pull/1093 introduced new `gpg_cmd` and `gpg_key_id` configuration options, but only used `gpg_key_id` when `gpg_cmd` is specified.  Some users may want to specify a `gpg_key_id` when using the default gpg command (when `gpg_cmd` is not specified).  This PR adds support for that.
@mibanescu
=> Use gpg_key_id even when gpg_cmd is not configured

docs/tech-reference/yum-plugins.rst
The default GPG digest algorithm (SHA1) is weak and best practices recommend it should be changed.  The documentation related to GPG key creation should include an appropriate configuration example.
=> Document GPG cipher/digest algorithm configuration

docs/tech-reference/export-distributor.rst, docs/user-guide/recipes.rst, docs/user-guide/release-notes/2.17.x.rst, plugins/pulp_rpm/plugins/distributors/export_distributor/generate_iso.py, plugins/test/unit/plugins/distributors/export_distributor/test_generate_iso.py
When we export a .iso file,  we must also export a checksum file with it.
=> Create checksum for exported iso file

docs/tech-reference/yum-plugins.rst, docs/user-guide/release-notes/2.17.x.rst, plugins/pulp_rpm/plugins/importers/yum/associate.py, plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py
Please note this requires a libsolv version exposing  [Python bindings necessary to support `fileprovides` deps](https://github.com/openSUSE/libsolv/pull/271). @ignatenkobrain made an [F26 build](https://copr-be.cloud.fedoraproject.org/results/ignatenkobrain/garbage/fedora-26-x86_64/00767394-libsolv/) with which I was able to [test this PR manually](https://paste.fedoraproject.org/paste/AG4-WcmcQ9OYeEe~-YfH1w).
Without it will just blow-up O:-)
=> Resolve rpm (rich) dependencies via libsolv

extensions_admin/pulp_rpm/extensions/admin/status.py, plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/importers/yum/importer.py, plugins/pulp_rpm/plugins/importers/yum/modularity.py, plugins/pulp_rpm/plugins/importers/yum/repomd/metadata.py, plugins/pulp_rpm/plugins/importers/yum/repomd/modules.py, plugins/pulp_rpm/plugins/importers/yum/sync.py
https://pulp.plan.io/issues/3862
https://pulp.plan.io/issues/3863
Add just the synchronization support for modulemd and modulemd-defaults.
It is anticipated that the **upload** functionality will use the `add_modulemds()` and `add_defaults()` provided by the _modularity_ to do the heavy lifting.
Does not include unit tests.
=> Add modularity synchronization

plugins/pulp_rpm/plugins/importers/yum/modularity.py, plugins/pulp_rpm/plugins/importers/yum/sync.py
https://pulp.plan.io/issues/3874
Add --validate option support when syncing modularity content.  Provides a remedy for when stored files are corrupted or deleted.
Does not include unit tests.
=> Add --validate option support for modularity sync.

plugins/pulp_rpm/plugins/migrations/0043_add_modulemd_modulemd-defaults.py
Solution: add a migration that will convert YumMetadataFile objects with data_type of 'modules'
into Modulemd and Modulemd-defaults objects.
closes #3659
https://pulp.plan.io/issues/3659
=> Problem: modulemd are stored as YumMetadataFiles

common/pulp_rpm/common/ids.py, extensions_admin/pulp_rpm/extensions/admin/units_display.py, plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/importers/yum/associate.py
fixes #3864
https://pulp.plan.io/issues/3864
Example calls to test recursive copy:
```
pulp-admin rpm repo update --repo-id zoo --feed "https://repos.fedorapeople.org/repos/pulp/pulp/fixtures/rpm-with-modules/"
pulp-admin rpm repo sync run --repo-id zoo
pulp-admin rpm repo create --repo-id zoo2
phttp https://localhost/pulp/api/v2/repositories/zoo2/actions/associate/ source_repo_id=zoo criteria:='{"type_ids": ["modulemd"]}' override_config:='{"recursive": true}'
```
=> As a user I can copy modulemd units

.travis/script.sh, pulp_rpm/app/models.py
closes #3201
https://pulp.plan.io/issues/3201
=> Add modelling for "Errata" content

plugins/pulp_rpm/plugins/importers/iso/sync.py
The DownloadEventListener interface defines download_failed(self,
report) and this restores the arity.
fixes #3899
https://pulp.plan.io/issues/3899
=> Fixing arity problem in iso's DownloadEventListener

plugins/pulp_rpm/plugins/importers/yum/associate.py
Currently each associate call in a recursive tree of calls instantiates
and loads its own instance of a solver. This is both CPU and RAM
expensive.
The fix avoids subsequent instantiation of the solver thru passing it as
an argument of the associate function.
Fixes: #3903
=> Share solver between recursive associate calls

plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py
The rich dep branch of the code was actually never accessed.
=> Fix indentation in the solver to parse rich deps

pulp_rpm/tests/functional/api/test_crd_publications.py, pulp_rpm/tests/functional/api/test_crud_content_unit.py, pulp_rpm/tests/functional/api/test_crud_publishers.py, pulp_rpm/tests/functional/api/test_crud_remotes.py, pulp_rpm/tests/functional/api/test_download_content.py, pulp_rpm/tests/functional/api/test_publish.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/functional/utils.py
Add boilerplate for all the smash tests but leave them disabled for now.
CRUD smash tests are enabled but not the sync/publish/content download ones.
=> Add full set of smash tests

pulp_rpm/app/models.py, pulp_rpm/app/serializers.py, pulp_rpm/app/viewsets.py
In createrepo, rpm packages are called packages and not rpms. Updating the model names to be consistent.
=> Renaming model names to be consistent with createrepo

.travis/script.sh, pulp_rpm/app/constants.py, pulp_rpm/app/models.py, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/app/viewsets.py
This handles creating packages and update records from an RPM remote.
UpdateCollections and their packages are not included.
ref #3202
https://pulp.plan.io/issues/3202
=> Initial pass at syncing rpm and erratum content

pulp_rpm/app/models.py, pulp_rpm/app/serializers.py, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/app/viewsets.py, pulp_rpm/tests/functional/constants.py
- Adds a new custom stage that saves UpdateCollection and
UpdateCollectionPackage objects in bulk
- Uses a new custom pipeline instead of DeclarativeVersion. This is
temporary until a new feature is added to DeclarativeVersion to
allow for stage injection.
- Adds a viewset and serializer for Erratum. It required one or it would
raise an exception that it couldn't serialize the output.
- updates the smash count since 4 Erratum units are now being correctly
included
- refactors closure style coroutines in favor of classmethods
https://pulp.plan.io/issues/3933
closes #3933
=> Get Sync Working with Erratum!

extensions_admin/pulp_rpm/extensions/admin/contents.py, extensions_admin/test/unit/extensions/admin/test_contents.py
The RPM data model already tracks the recommends field but the Pulp CLI
isn't displaying it. This patch enables the field display by enumerating
it and formatting it the same way as the provides and requires fields are
formatted.
Fixes: #3929
https://pulp.plan.io/issues/3929
=> Show the recommends field in pulp-admin

pulp_rpm/tests/functional/api/test_crud_content_unit.py, pulp_rpm/tests/functional/api/test_crud_remotes.py, pulp_rpm/tests/functional/api/test_download_content.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/functional/utils.py
Add a new smash test which checks that UpdateRecords (Errata) are updated,
not duplicated, when syncing in new UpdateRecord with the same ID but
different metadata.
This test is currently disabled, because it will fail until this is fixed in Pulp.
Also:
* Remove fixture data we aren't using yet
* Replace usages of RPM_FIXTURE_URL with RPM_SIGNED_FIXTURE_URL
* Compare content summaries instead of taking the len() of get_content()
* RPM has multiple content types which get mixed together otherwise
=> Add a test for mutated errata

pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py
Test that when packages with the same NEVRA but different pkgId are
synced into the repository, we end up with only one copy of them in the
final repository version.
=> Add a new smash test for duplicate NEVRA removal

pulp_rpm/app/constants.py, pulp_rpm/app/models.py, pulp_rpm/app/tasks/synchronizing.py
- Create an UpdateReference model to store reference info for errata.
- Store it during sync
re #3998
https://pulp.plan.io/issues/3998
=> Store UpdateReference

README.rst, pulp_rpm/app/tasks/publishing.py, pulp_rpm/tests/functional/api/test_publish.py
closes #3204
https://pulp.plan.io/issues/3204
The code that maps fields from our models to createrepo_c is not very optimal. There's two problems. First, not all the field names match up (although they will in the future), and second, we have to convert a few field types. I propose we refactor this once we fix the `id` and `type` fields. Doing so will let us just iterate through the lists of fields (e.g. CREATEREPO_PACKAGE_ATTRS, etc).
=> As a user, I can publish rpms and errata

pulp_rpm/tests/functional/api/test_consume_content.py, pulp_rpm/tests/functional/api/test_publish.py, pulp_rpm/tests/functional/utils.py
Add a test to verify whether package manger, dnf/yum, can consume content from pulp.
Add an utils function `gen_yum_config_file`.
See: https://pulp.plan.io/issues/3204
=> Add test to package manager consume content from Pulp

pulp_rpm/app/tasks/publishing.py
We could still end up with "Unknown checksum" values but I think that's ok and it should be less likely that checksum is set but sum_type is not.
fixes #4033
https://pulp.plan.io/issues/4033
=> Only show checksum if it's not blank

README.rst, pulp_rpm/app/models.py, pulp_rpm/app/serializers.py, pulp_rpm/app/viewsets.py, pulp_rpm/tests/functional/api/test_crud_content_unit.py, pulp_rpm/tests/functional/api/test_download_content.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/functional/utils.py
Implement upload support.  Content units are now created by providing the artifact href and a filename -- all additional information is parsed directly from the RPM file instead of being user-provided.
Implement some content-specific bits of the smash test boilerplate for
RPM Packages, and enable CRUD content tests for PackageContent.
=> Add upload support, enable CRUD PackageContent tests

pulp_rpm/tests/functional/api/test_consume_content.py
Pulp-smash offers a new attribute for Package managers. Explore this new
feature
See: https://github.com/PulpQE/pulp-smash/pull/1141
`[noissue]`
=> Update package manager handling

pulp_rpm/tests/functional/api/test_publish.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/functional/utils.py
Add test to sync/publish a RPM repository with `updateinfo.xml` with
references.
Introduce new constant RPM_REFERENCES_UPDATEINFO_URL
See: https://repos.fedorapeople.org/pulp/pulp/fixtures/rpm-references-updateinfo/
=> Add test to sync/publish update references

docs/tech-reference/yum-plugins.rst
The correct attribute that defines when repodata is considered "old"
is in fact remove_old_repodata_threshold. Change it to this.
=> correct minor mistake in remove_old_repodata entry

pulp_rpm/tests/functional/api/test_download_content.py, pulp_rpm/tests/functional/utils.py
Enable test download content, and modify the function `get_rpm_package_paths`.
This function will return just RPM packages names with this change.
Remove function `gen_rpm_filename`.
'[noissue]'
=> Enable test download content

pulp_rpm/tests/functional/constants.py
Update RPM constant to avoid harcode definitions. Use only one defintion and
use as the base for the others.
'[noissue]'
=> Update RPM constant definition

plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py
We discovered an issue where on some versions of python2-solv, there was
no create kwarg for str2dir. So we're removing it from this call since by
default it's True anyway.
Note that this is not really a fix for #3876
https://pulp.plan.io/issues/3876
ref #3876
=> Remove create kwarg since by default it's true

plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/importers/yum/listener.py, plugins/pulp_rpm/plugins/importers/yum/modularity.py, plugins/pulp_rpm/plugins/importers/yum/parse/rpm.py, plugins/pulp_rpm/plugins/importers/yum/upload.py, plugins/pulp_rpm/plugins/migrations/0046_add_is_modular_field.py
* Add new field `is_modular` for Rpm model
* Inspect headers to mark RPMs as modular during upload
* Mark RPMs as modular during sync based on artifacts info in modules.yaml
* Inspect headers to mark RPMs as modular ones upon successful download
* Migrate all RPMs, set `is_modular` to True based on data in Modulemd units
closes #4049
https://pulp.plan.io/issues/4049
=> Mark modular RPMs during sync and upload

plugins/pulp_rpm/plugins/importers/yum/parse/rpm.py
closes #4130
https://pulp.plan.io/issues/4130
Rpm header object does not have get() attribute.
=> Not able to upload RPMs.

pulp_rpm/tests/functional/api/test_crud_content_unit.py, pulp_rpm/tests/functional/api/test_publish.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/functional/utils.py
Add tests to sync/publish with different types of RPMs repositories.
* Long updateinfo
* Alternative repo layout
* RPM with sha512
ref: #4134
https://pulp.plan.io/issues/4134
=> Add test to sync/publish different types of RPMs

.travis/install.sh, docs/installation.rst, setup.py
This dependency is now available on PyPI.
https://pulp.plan.io/issues/4217
closes #4217
=> Remove createrepo_c build docs

pulp_rpm/tests/functional/api/test_character_encoding.py, pulp_rpm/tests/functional/constants.py
Add test for non-ascii RPM metadata. Upload non-ascii RPM to pulp and assert
that no error was raised.
https://pulp.plan.io/issues/4210
ref #4210
=> Add test for non-ascii RPM metadata encoding

pulp_rpm/tests/functional/api/test_crud_content_unit.py
For a brief period Pulp would allow you to delete a content unit as long
as it wasn't used by a repository version. That is no longer the case -
content unit deletion should be disallowed in all circumstances. Fix the
tests likewise, and test that the response is HTTP 405 'method not allowed', specifically.
re #4216
https://pulp.plan.io/issues/4216
=> Simplify content unit deletion test

pulp_rpm/tests/functional/api/test_sync.py
re #4073
https://pulp.plan.io/issues/4073
=> Add test to make sure files are not being left open after sync tasks

pulp_rpm/app/models.py, pulp_rpm/app/serializers.py, pulp_rpm/app/tasks/publishing.py, pulp_rpm/app/viewsets.py, pulp_rpm/tests/functional/api/test_sync.py
Update errata_id and update_type now that id and type have been renamed
on Content. Also, fix a couple places that reference _artifacts.
fixes #4207
https://pulp.plan.io/issues/4207
=> Changes for the new field names on Content

plugins/pulp_rpm/plugins/distributors/yum/metadata/modules.py, plugins/pulp_rpm/plugins/distributors/yum/publish.py
Ensure we don't publish module metadata files for repositories where the source repo had none.
Use the correct mechanism for determining the checksum used in the name
of the modules.yaml.gz metadata file.
Additionally, refactor the module publish step to be more similar to the
others.
closes #4252
https://pulp.plan.io/issues/4252
closes #4253
https://pulp.plan.io/issues/4253
=> Fix multiple bugs related to modularity

pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py
Modify assertions on `SyncMutatedPackagesTestCase` to use a constant
value.
'[noissue]'
=> Modify test assertion to use constant

extensions_admin/pulp_rpm/extensions/admin/copy_commands.py, extensions_admin/pulp_rpm/extensions/admin/rpm_repo/pulp_cli.py, plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py
https://pulp.plan.io/issues/3740
=> Modular content on top of issue 4152

plugins/pulp_rpm/plugins/importers/iso/importer.py, plugins/test/unit/plugins/importers/iso/test_importer.py
Now pulp will set/update the metadata during iso upload
Fix #2729
https://pulp.plan.io/issues/2729
=> Fix unit_metadata is ignore during iso import [DELIVERY-5965]

plugins/pulp_rpm/plugins/importers/yum/sync.py
The issue involved counting duplicate srpms when creating the package
count for primary.xml which led the check against filelists.xml to fail.
To create a unique package count, we're storing srpms we've seen thereby
not counting them if we've seen the NEVRA already.
fixes #4397
https://pulp.plan.io/issues/4397
=> Account for duplicate srpms in count when skipping srpms

pulp_rpm/tests/functional/api/test_download_policies.py
Add basic test to sync using different download policies.
ref:#4126
https://pulp.plan.io/issues/4126
closes:#4213
https://pulp.plan.io/issues/4213
=> Add test to sync using different download policies

pulp_rpm/tests/functional/api/test_consume_content.py, pulp_rpm/tests/functional/api/test_download_content.py, pulp_rpm/tests/functional/utils.py
Fix gen_yum_config_file function and reads content_host role.
1. gen_yum_config_file was generating repo file using `:` intead of `=`
and that was causing dnf errors.
2. Consume and Download test cases are now using the host defined in
the new `content` role if defined.
Required PR: https://github.com/PulpQE/pulp-smash/pull/1169
closes: #4320
https://pulp.plan.io/issues/4320
=> Fix gen_yum_config_file function and reads content_host role.

docs/workflows/upload.rst, pulp_rpm/app/serializers.py, pulp_rpm/app/shared_utils.py, pulp_rpm/app/upload.py, pulp_rpm/app/urls.py, pulp_rpm/app/viewsets.py
RFE to upload one RPM file and optionally create new
version of repository with this added package.
closes: #4087
https://pulp.plan.io/issues/4087
=> One shot RPM uploader

pulp_rpm/tests/functional/api/test_publish.py
Pulp 3 does not support DRPM packages yet. RPMs are synced/published
from that repo while DRPMs are not.
Test can be added again when this change.
'[noissue]'
=> Remove DRPM test sync/publish

plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/test/unit/plugins/distributors/yum/test_publish.py
When publish repos, the command createrepo_c could be used but the option
--keep-all-metadata for this command doesn't really keep all metadata --
moudlemd and product_id file will be thrown away.
Now make it keeps these file by running command sqliterepo_c
bug filed by Rohan Mcgovern:
https://bugzilla.redhat.com/show_bug.cgi?id=1670651
=> Publish modulemd/productid when generate_sqlite is set to true 

pulp_rpm/app/serializers.py, pulp_rpm/app/viewsets.py
Fixing package upload after changes from https://pulp.plan.io/issues/4394.
fixes #4472
https://pulp.plan.io/issues/4472
=> Fixing package upload

handlers/pulp_rpm/handlers/rpm.py
Fixes: https://pulp.plan.io/issues/4476
=> use platform.dist() on Python prior to 2.6

pulp_rpm/app/viewsets.py
When RPM file is not parsable return 406 (Not Acceptable)
as rpm cannot be accepted due to metadata parse failed.
closes: #4471
https://pulp.plan.io/issues/4471
=> Change return status

pulp_rpm/tests/functional/api/test_upload.py
Add test to single request upload. Assert that an artifact, content unit
and repository version were created using a single request upload.
https://pulp.plan.io/issues/4285
closes: #4285
=> Add test single request upload

pulp_rpm/app/upload.py
Check for package as already exists in pulp.
One line of doc string removed as not used/present.
closes: #4485
https://pulp.plan.io/issues/4485
=> Package duplicate check for oneshot uploader

pulp_rpm/tests/functional/api/test_download_content.py
Create, update, and delete for Distributions were made asynchronous in:
pulp/pulpcore#6
in response to issue 3044:
https://pulp.plan.io/issues/3044
Because of these changes, tests that create distributions previously expected
this action to return a distribution but now receive a task so additional steps
were needed to retrieve the distribution from the created_resources of the task
Required PR: pulp/pulpcore#6
ref #3044
https://pulp.plan.io/issues/3044
=> Updates test to handle changes to Distribution CUD operations

docs/workflows/upload.rst
As in the code create repository version from uploaded
rpm is optionally, it should reflect in the docs too.
closes: #4433
https://pulp.plan.io/issues/4433
=> Oneshot uploader doc adjust

docs/tech-reference/yum-plugins.rst, docs/user-guide/features.rst
closes #4371
https://pulp.plan.io/issues/4371
=> Add docs describing behavior of recursive flags

plugins/pulp_rpm/plugins/importers/yum/purge.py
This function, which is used whenever a new RPM is uploaded, was
slower than necessary.
The old implementation would first use find_repo_content_units,
which queries for all unit IDs of the required type in the repo
and then performs a unit query combining the relevant NEVRA with
the IDs.
In fact finding all those unit IDs is measurably slow for a large
repo, and it's much faster (while still correct) to simply search
for the RPMs to remove directly.  It's harmless if this finds
some RPMs with same NEVRA which are already not in the repo.
On our installation, for a repo with ~24000 RPMs, this reduced
the runtime of this method from ~8 seconds to <0.1 seconds.
fixes #4527
https://pulp.plan.io/issues/4527
=> Improve performance of remove_unit_duplicate_nevra

plugins/pulp_rpm/plugins/distributors/yum/publish.py
Solution: stop publishing Distributions in Packages directory
fixes: #4541
https://pulp.plan.io/issues/4541
=> Problem: RPMs from distribution published twice

pulp_rpm/app/upload.py
As one shot upload run in task it should
return some created resources.
As repository is optional the task now returns
package or package and repository version as
resource created.
closes: #4474
https://pulp.plan.io/issues/4474
=> Populate created resources

plugins/pulp_rpm/plugins/distributors/yum/publish.py
Solution: Copy YumMetadataFile to the publish directory
YumCloneDistributor and RPMRsyncDistributor both copy the content of repodata directory.
This results in broken symlinks for all YumMetadataFile content.
fixes: #4550
https://pulp.plan.io/issues/4550
fixes: #4560
https://pulp.plan.io/issues/4560
=> Problem: YumMetadataFile is a symlink

pulp_rpm/app/tasks/publishing.py
closes #4516
closes #4030
https://pulp.plan.io/issues/4516
https://pulp.plan.io/issues/4030
=> Compress sqlite repodata files.

plugins/pulp_rpm/plugins/distributors/yum/publish.py
Solution: use shutil.copy2() to copy YumMetadataFile content type
re: #4550
https://pulp.plan.io/issues/4550
=> Problem: YumMetadataFile attributes are not preserved

pulp_rpm/tests/functional/api/test_download_policies.py
Fix test `SyncPublishDownloadPolicyTestCase`. Add publish step.
https://pulp.plan.io/issues/4418
ref: #4418
=> Fix test SyncPublishDownloadPolicyTestCase

pulp_rpm/app/models.py, pulp_rpm/app/tasks/publishing.py
closes #4412
https://pulp.plan.io/issues/4412
=> Fix publish for the on_demand sync case

pulp_rpm/tests/functional/api/test_consume_content.py, pulp_rpm/tests/functional/api/test_download_content.py
Distribution creation it was modified to be an async task. A new
response_handler was added to pulp-smash to deal with those cases.
Update distribution creation to use this new response_handler.
'[noissue]'
=> Update distribution creation to use task_handler

docs/index.rst, docs/workflows/create_sync_publish.rst, docs/workflows/upload.rst
The homepage was not immediately clear with what features it is offering
pulp_rpm users. This tries to make that clearer and link users to that
section of the docs so they can see what to do.
https://pulp.plan.io/issues/4621
closes #4621
=> Adding features directly to homepage

plugins/pulp_rpm/plugins/distributors/yum/publish.py
Old way of publishing yum_repo_metadata_file content was to create a symlink.
Recently yum_repo_metadata_file content started to be copied at publish time.
This fix affects upgrade cases, when yum_repo_metadata_file was published
the old way, but incremental publish happened in a new way.
closes #4661
https://pulp.plan.io/issues/4661
=> Fix incremental publish for yum_repo_metadata_file content

pulp_rpm/app/upload.py, pulp_rpm/app/viewsets.py
Add right 'location_href' property (from artifact)                             
when creating content by one shot uploader.                                    
closes: #4656                                                                  
https://pulp.plan.io/issues/4656
=> Single upload filename fix

plugins/pulp_rpm/plugins/distributors/yum/publish.py
Solution: unlink all symlinked YumMetadataFiles before copying
re: #4692
https://pulp.plan.io/issues/4692
=> Problem: file could be copied into link location

docs/installation.rst
Add instruction how to install plugin with ansible-pulp.
closes: #4163
https://pulp.plan.io/issues/4163
=> Add ansible-pulp instructions

docs/conf.py, docs/index.rst, docs/quickstart.rst, docs/workflows/use_pulp_repo.rst
The quickstart page gets the user going with pulplift and helps them
check the status API. From there it links to the already great workflows
page.
This also fixed the readthedocs theme to be used which is important
because only that theme renders the left-panel in a way that you can see
this PR as it appears on the website. If you don't have the
sphinx_rtd_theme package installed you get the default theme as a
fallback.
https://github.com/rtfd/sphinx_rtd_theme
https://pulp.plan.io/issues/4620
closes #4620
=> Added quickstart page

docs/quickstart.rst
There were formatting errors and one term missing causing Sphinx build
errors. This PR fixes those issues.
https://pulp.plan.io/issues/4620
closes #4620
=> Quickstart page fixes

pulp_rpm/tests/functional/api/test_crud_remotes.py
Make assertions for `CreateRemoteNoURLTestCase` a bit more strict.
'[noissue]'
=> Tweak assertions for CreateRemoteNoURLTestCase

handlers/usr/lib/yum-plugins/pulp-profile-update.py
Adds support for anonymous proxy into the pulp-profile-update plugin.  Requires https://github.com/pulp/pulp/pull/3848
=> Add support for anonymous proxy (see https://pulp.plan.io/issues/3625)

docs/user-guide/release-notes/2.19.x.rst, plugins/pulp_rpm/plugins/migrations/0043_add_modulemd_modulemd-defaults.py
Some users might have old experimental modular content in Pulp.
Such content doesn't contain all the necessary info to be imported
in Pulp. E.g. no `context` which is a part of unit_key.
closes #4741
https://pulp.plan.io/issues/4741
=> Skip malformed modular content during migration

common/pulp_rpm/common/constants.py, plugins/pulp_rpm/plugins/importers/yum/repomd/metadata.py, plugins/pulp_rpm/plugins/importers/yum/sync.py, plugins/test/unit/plugins/importers/yum/test_sync.py
Some metadata changes don't bump revision number, so sync used
to be no-op in such cases. Now checksum of repomd.xml is also taken
into account.
closes #4627
https://pulp.plan.io/issues/4627
=> Perform sync even on metadata change only

docs/tech-reference/rpm.rst, plugins/pulp_rpm/plugins/importers/yum/sync.py
Pulp 2 doesn't support zchunk compression format.
Keeping mirrored zchunk metadata in a repository can cause
a repository to be in a broken state.
closes #4529
https://pulp.plan.io/issues/4529
=> Skip zchunk metadata at sync time

docs/quickstart.rst, docs/release-notes/3.0.z.rst, docs/workflows/copy.rst, docs/workflows/create_sync_publish.rst, docs/workflows/use_pulp_repo.rst, pulp_rpm/app/models.py, pulp_rpm/app/viewsets.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py
[noissue]
Justification: The name "UpdateRecord" is exclusively an implementation detail of createrepo_c, it doesn't seem like they are named as such anywhere else in the ecosystem.  We shouldn't expose such an implementation detail to end users.
=> Change the user-facing name of "update" to "errata"

extensions_admin/pulp_rpm/extensions/admin/contents.py, extensions_admin/pulp_rpm/extensions/admin/rpm_repo/pulp_cli.py
[noissue]
I did this during the debugging of https://pulp.plan.io/issues/4693 since it's really simple and much easier than looking in the database.
=> Make it possible to list modules via "pulp-admin rpm content ..."

pulp_rpm/app/tasks/copy.py, pulp_rpm/app/tasks/upload.py, pulp_rpm/app/viewsets.py
The copy and upload tasks were passing large objects instead of passing
pks. This switches those (and their corresponding dispatch code) to use
pks instead, and the objects are re-queried in the task. Some of the
tasks didn't need an update because they already used that form. All
tasks were checked.
https://pulp.plan.io/issues/4876
closes #4876
=> Switch tasks to use pks

pulp_rpm/app/serializers.py
As missing 'relative_path' can break publish, change
it for required everytime.
closes: #4835
https://pulp.plan.io/issues/4835
=> Require relative path

pulp_rpm/app/models.py
Solution: make database schema copmatible with MariaDB
This patch switches TestFields to CharFields where an index is needed on that field.
fixes: #4909
https://pulp.plan.io/issues/4909
=> Problem: plugin is not compatible with MariaDB

pulp_rpm/app/models.py
Solution: set shorter max_length for all appropriate fields
This patch reduces the max_length for epoch, arch, pkgId, and checksum_type.
fixes: #4916
https://pulp.plan.io/issues/4916
=> Problem: Package's unique together index key is too long

plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py
This code is very difficult to follow. Here are some improvements that
make it more comprehensible.
* Add docstrings
* Rename functions to have more descriptive names
* Turn methods that do not need to be methods into functions
* Separate the concerns of performing depsolving and loading data from
the database
This does not fix any depsolving issues, but it will really help with maintaining and debugging this code.
=> Refactoring depsolving code for clarity

docs/tech-reference/export-distributor.rst
Add missing space that was breaking the paragraph in two.
=> Fix relative_url paragraph in docs

common/pulp_rpm/common/constants.py, plugins/pulp_rpm/plugins/importers/yum/parse/rpm.py
Old RPMTAG_DISTTAG is still in the code for the old content
that might be still around.
closes #4869
https://pulp.plan.io/issues/4869
=> Use new RPMTAG_MODULARITYLABEL to identify modular RPMs

plugins/pulp_rpm/plugins/serializers.py
It didn't affect publish results, however it did affect applicability
calculations and erratum content which user queries via API.
Kudos to Hyu (reporter of the issue) for the patch.
closes #4880
https://pulp.plan.io/issues/4880
=> Fix serializer for erratum pkglists

.travis/publish_client_gem.sh, pulp_rpm/__init__.py, setup.py
A correct version would be shown for installations from the master branch.
Bindings will be generated with a proper version as well.
re #4936
https://pulp.plan.io/issues/4936
=> Set version to .dev for the master branch

pulp_rpm/app/models.py, pulp_rpm/app/tasks/synchronizing.py
Use extra_data attribute of DeclarativeContent instead.
closes #4117
https://pulp.plan.io/issues/4117
=> Stop using model attributes to carry related models to save later

pulp_rpm/app/constants.py, pulp_rpm/app/models.py
to better readability code package method to convert data
to createrepo_c using PULP namespace.
closes: #4567
https://pulp.plan.io/issues/4567
=> Refactor naming for pakcage attr

pulp_rpm/tests/functional/api/test_consume_content.py, pulp_rpm/tests/functional/api/test_crud_remotes.py
The names were updated to replace 'lazy' with 'on demand' and also
reflect the recently changed validation in pulpcore.
Required PR: pulp/pulpcore#199
Required PR: PulpQE/pulp-smash#1210
[noissue]
=> Update for pulp-smash constant name change

docs/tech-reference/export-distributor.rst
As stated in Pulp 2.10 Relase Notes, export distributors support
updateinfo_checksum_type but it was missing in the docs.
The paragraph is copied from Yum Plugins.
=> Add updateinfo_checksum_type option to export distributor docs

CHANGES/4987.bugfix, docs/workflows/upload.rst, pulp_rpm/app/serializers.py, pulp_rpm/app/viewsets.py, pulp_rpm/tests/functional/api/test_character_encoding.py, pulp_rpm/tests/functional/api/test_crud_content_unit.py
The field filename seems to be redundant. Therefore, it's usages were removed from
the corresponding view set. Now, relative_path is used as filename instead.
In this commit, the field relative_path is no longer nullable. Also, the field
cannot be initialized to an empty string because it is used for a package creation
where the path is stored as location_href.
closes #4987
https://pulp.plan.io/issues/4987
=> Use relative_path instead of filename

pulp_rpm/app/models.py, pulp_rpm/app/serializers.py
Add pre-requisities for modularity support.
Modulemd model, modulemd serializer.
Add boolean field to Package model if rpm is modular
and its serializer.
re: #4873
https://pulp.plan.io/issues/4873
=> Modulemd model and serializer

plugins/pulp_rpm/plugins/importers/yum/associate.py, plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py
This PR does not add the ability to provide Pulp with multiple source repositories, it only provides the ability to provide the solver with multiple source repositories.
* Add a new "additional_repos" kwarg to the Solver class
* Make provisions for loading all of the new additional repos
* Make all target repositories be loaded into one repo, since libsolv
only supports a single "installed" repo
* Make the "find_dependent_rpms" method return a dict of {'repo_id':
set(<unit_ids>)} so that the upper-level copy code knows where the units
came from, and hence, can determine where they need to go.
=> Add support for multiple input repositories to the solver

.travis.yml
Travis recently changed their default from Trusty to Xenial, which no
longer supports Python 2.6.
[noissue]
=> Fix travis distro to "trusty"

pulp_rpm/app/models.py, pulp_rpm/app/serializers.py
models for modulemd-deafults as prerequisity for modulemd support.
closes: #4873
https://pulp.plan.io/issues/4873
=> Modulemd Defaults models

plugins/pulp_rpm/yum_plugin/util.py, plugins/test/unit/plugins/db/test_models.py
closes #5308
https://pulp.plan.io/issues/5308
=> Allow versions in updateinfo to be non-numeric

.travis/before_script.sh, .travis/check_commit.sh, .travis/install.sh, .travis/publish_client_gem.sh, .travis/publish_client_pypi.sh, .travis/publish_plugin_pypi.sh, .travis/script.sh
"use-containers-for-CI"
Most significantly, unit test failures will now make travis fail.
[noissue]
re: 5064
migrate travis plugin-template to installing pulp in containers
https://pulp.plan.io/issues/5004
=> Misc fixes from the latest plugin_template branch

common/pulp_rpm/common/constants.py, docs/tech-reference/yum-plugins.rst, docs/user-guide/features.rst, plugins/pulp_rpm/plugins/db/models.py, plugins/pulp_rpm/plugins/importers/yum/associate.py, plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py
This PR has a companion here: https://github.com/pulp/pulp/pull/3947
This PR is best reviewed as a series of individual commits.
Create 4 repositories:
* 1 repository must contain modules or RPMs that depend on other RPMs in the second repo
* 1 repository must contain all of the RPM dependencies needed by the first repo
* 2 empty repositories
Personally, I used these two Fedora repositories:
* releases/30/Modular: https://dl.fedoraproject.org/pub/fedora/linux/releases/30/Modular/x86_64/
* releases/30/Everything: https://dl.fedoraproject.org/pub/fedora/linux/releases/30/Everything/x86_64/os/
The former repo depends on stuff in the latter repo.
Make a direct API request -- there is no ```pulp-admin``` support for this feature at the moment
```curl -k -u admin:admin  --cert …
```
=>  As a user, multiple source/target repositories can be used for recursive copy

CHANGES/5431.misc, pulp_rpm/app/constants.py, pulp_rpm/app/serializers.py, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/app/viewsets.py, pulp_rpm/tests/functional/constants.py
closes #5431
https://pulp.plan.io/issues/5431
Required PR: https://github.com/pulp/pulp_rpm/pull/1438
=> Syncing custom/unknown repository metadata

CHANGES/5432.feature, pulp_rpm/app/tasks/publishing.py
closes #5432
https://pulp.plan.io/issues/5432
Required PR: https://github.com/pulp/pulp_rpm/pull/1438
Required PR: https://github.com/pulp/pulp_rpm/pull/1439
=> Publish custom/unknown repository metadata

CHANGES/5172.misc, pulp_rpm/app/constants.py, pulp_rpm/app/models.py, pulp_rpm/app/modulemd.py, pulp_rpm/app/serializers.py, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/app/viewsets.py
Add sync support for modulemd and modulemd-defaults and create relations between modulemd and RPM packages.
And keep snippet from modules.yaml as an artifact for content (modulemd and modulemd-defaults).
Required PR: https://github.com/pulp/pulpcore-plugin/pull/130
re #5172
https://pulp.plan.io/issues/5172
=> Sync modulemd and modulemd-defaults

pulp_rpm/app/serializers.py
With new change for upload modular serializers didn't inherit news fields
so viewsets broke at missing fields.
[noissue]
=> Modular serialzers fix

CHANGES/5488.doc, docs/installation.rst
Update installation doc to use `pulp_use_system_wide_pkgs` in playbook
as needed for usage python binding for modularity (libmodulemd).
These binding can't be installed with `pip` only with RPM package.
closes #5488
https://pulp.plan.io/issues/5488
=> Update install doc

docs/installation.rst, docs/quickstart.rst
And to remove the no longer-used app-label.
re: #5518
Problem: Running include_roles with pulp-rpm-prerequisites causes it to fail
https://pulp.plan.io/issues/5518
[noissue]
=> Update docs for new prereq_role dictionary variable

CHANGES/5652.bugfix, pulp_rpm/app/tasks/synchronizing.py
Add inner transaction to properly handle exceptions inside outer transaction.
Django recommended way https://docs.djangoproject.com/en/2.2/topics/db/transactions/#django.db.transaction.atomic
closes #5652
https://pulp.plan.io/issues/5652
=> Fix sync of a repo which contains modules and advisories

CHANGES/5655.bugfix, pulp_rpm/app/tasks/synchronizing.py
https://pulp.plan.io/issues/5655
closes #5655
=> Fix 404: repo remote URL is without trailing slash

CHANGES/5663.misc, pulp_rpm/app/tasks/synchronizing.py
This allows for syncing of repos such as the CentOS 8 AppStream repo.  Fixes #5663
=> Add transaction.atomic for Modulemd content

pulp_rpm/tests/functional/api/test_consume_content.py
Fix test due to recent change to CONTENT_ORIGIN which now includes the
scheme.
[noissue]
=> Use distribution base_url as path for repos

CHANGES/5679.removal, pulp_rpm/app/serializers.py, pulp_rpm/app/viewsets.py
For consistency, now:
modulemd -> modulemds
packageenvironmwent -> packageenvironments
packagecategory -> packagecategories
packagegroup -> packagegroups
closes #5679
https://pulp.plan.io/issues/5679
=> Rename endpoints for content to be in plural form

CHANGES/5680.removal, pulp_rpm/app/viewsets.py
For consistency, now
module-defaults -> module_defaults
closes #5680
https://pulp.plan.io/issues/5680
=> Rename module-defaults content endpoint

CHANGES/5677.bugfix, pulp_rpm/app/tasks/utils.py
https://pulp.plan.io/issues/5677
closes #5677
=> Handle missing trailing slash on kickstart tree fetching

CHANGES/3308.misc, pulp_rpm/tests/functional/api/test_download_policies.py, pulp_rpm/tests/functional/api/test_publish.py, pulp_rpm/tests/functional/api/test_sync.py
Required PR: https://github.com/pulp/pulpcore/pull/380
re: #3308
https://pulp.plan.io/issues/3308
=> Update tests to not rely on version always incrementing

CHANGES/5699.bugfix, pulp_rpm/app/shared_utils.py
Data can be now stored as a JSON binary. Therefore, it is not requried to dump data back to the string format.
closes #5699
https://pulp.plan.io/issues/5699
=> Do not dump data back to a string

CHANGES/5746.bugfix, pulp_rpm/app/modulemd.py
The problem was use of values_list() which isn't meant for many-to-many
relationships. Instead, build a set of packages.
fixes #5746
https://pulp.plan.io/issues/5746
=> Fixed error on adding modular content to a repository

CHANGES/4424.bugfix, pulp_rpm/app/tasks/synchronizing.py
https://pulp.plan.io/issues/4424
closes #4424
=> Descriptive error for RPM with invalid metadata

setup.py
Right now, pulpcore master is at 3.1.x which means pulp_rpm won't work
with it.
[noissue]
=> Bump the pulpcore requirement

CHANGES/5564.doc, docs/installation.rst, docs/quickstart.rst
update ansible-pulp installation steps
add mention that usage of system-wide-packages must be enabled
add step how to check if it is enabled
update quickstart to use pulplift pulp3-sandbox-fedora30
closes #5564
https://pulp.plan.io/issues/5564
=> Installation docs update

CHANGES/5228.doc, docs/index.rst
Add 'Requirements' to the docs as rpm plugin can be installed only on
specific distributions.
closes #5228
https://pulp.plan.io/issues/5228
=> Specify installation methods of rpm plugin

CHANGES/5753.doc, docs/index.rst, docs/tech-preview.rst
Add Tech Preview section to the docs, reference it on main page as warning.
fixes #5753
https://pulp.plan.io/issues/5753
=> Specify features released as tech preview

CHANGES/5749.doc, docs/index.rst, docs/restapi.rst
Add REST API docs to the top-level menu
closes #5749
https://pulp.plan.io/issues/5749
=> Rest API link

CHANGES/5693.misc, pulp_rpm/app/models/advisory.py, pulp_rpm/app/models/distribution.py
pulpcore changed the name of `Model` to `BaseModel`. This PR updated
pulp_rpm to do the same.
Required PR: https://github.com/pulp/pulpcore/pull/421
https://pulp.plan.io/issues/5693
closes #5693
=> Use `BaseModel` instead of `Model`

CHANGES/5754.doc, docs/quickstart.rst
Removed broken link to pulplift quickstart, and made a few minor changes
including adding instructions to run the pulp environment.
Calling this WIP until I'm at a stopping point in my other work for
actually starting a new vagrant so I can walk through the steps.
fixes #5754
https://pulp.plan.io/issues/5754
=> [WIP] Bring Quickstart page up to date, including links

CHANGES/5853.doc, setup.py
Solution: Specify them with them in setup.py
Required PR: https://github.com/pulp/pulpcore/pull/437
Fixes: #5853
=> Problem: pulp_rpm does not declare its dependency on libcomps & PyGObject

CHANGES/5688.bugfix, pulp_rpm/app/tasks/synchronizing.py
https://pulp.plan.io/issues/5688
Required PR: https://github.com/pulp/pulpcore/pull/440
closes #5688
=> Improve memory performance on syncing

CHANGES/5689.bugfix, pulp_rpm/app/models/comps.py, pulp_rpm/app/tasks/publishing.py, pulp_rpm/tests/performance/test_publish.py
https://pulp.plan.io/issues/5689
closes #5689
=> Improve memory performance on publishing

pulp_rpm/app/tasks/synchronizing.py
Update ProgressReport for batches of content instead of individually.
ProgressReport updating took 30% of the runtime of syncs, now 1%.
Required PR: https://github.com/pulp/pulpcore/pull/441
[noissue]
=> Improve performance by cutting way down on ProgressReport updating

CHANGES/5857.bugfix, pulp_rpm/app/serializers.py
'pulp_href' and other fields beyond those in the comps types themselves
are now displayed.
fixes #5857
https://pulp.plan.io/issues/5857
=> Adds fields from inherited serializer to comps types display

CHANGES/5006.doc, docs/workflows/create_sync_publish.rst
Sync must complete before you can kick off a publish task,
now that is documented.
fixes #5006
https://pulp.plan.io/issues/5006
=> Document that sync must complete before attempting publish

CHANGES/5841.doc, docs/installation.rst
libcomps or createrepo_c on CentOS 7 / RHEL 7 (and most likely 8.)
Solution: Document python build dependencies that must be installed.
(I cannot find the exact bug, but when you use system-wide packages,
upgrading the venv pip will not suffice. It still tries to use the
system-wide old pip for some functions anyway, and auto-installing
build deps will fail.)
fixes: #5841
Document how to install libcomps and dependencies
https://pulp.plan.io/issues/5841
=> Problem: Users following docs cannot build

CHANGES/5900.misc, setup.py
Mark GA release as production/stable in setup.py classifiers.
fixes #5900
https://pulp.plan.io/issues/5900
=> Update classifiers in setup.py

CHANGES/6034.featrure, pulp_rpm/app/constants.py, pulp_rpm/app/tasks/synchronizing.py
To prevent broken repos, skip any unsupported repodata: all zchunked
metadata, gzipped comps.xml, and prestodelta.xml
fixes #6034
https://pulp.plan.io/issues/6034
=> Skip unsupported repodata

CHANGES/5737.feature, pulp_rpm/app/constants.py, pulp_rpm/app/models/advisory.py
Added reboot_suggested to methods which interacts with createrepo_c to
can be get and published with this info.
closes #5737
https://pulp.plan.io/issues/5737
=> Reboot suggested for advisory

CHANGES/5992.doc, docs/installation.rst, docs/quickstart.rst
during pulp_rpm install.
Solution: Remove it from the docs. We now set it in the
pulp_rpm_prerequisites role via include_vars on the vars/main.yml
re: #5992
https://pulp.plan.io/issues/5992
ansible-pulp rpm plugin: Failed building wheel for PyGObject Failed building wheel for pycairo
[noissue]
=> Problem: pulp_use_system_wide_pkgs is often overlooked

CHANGES/5854.feature, pulp_rpm/app/viewsets.py
fixes #5854
Required PR: https://github.com/pulp/pulpcore/pull/452
=> Adding some not equal filters

plugins/pulp_rpm/plugins/importers/yum/associate.py
into the destination breaks at publish-time due to missing
checksum on the resulting ModulemdDefaults unit.
Fixed by noticing and fixing the problem at associate-time.
closes #6096
https://pulp.plan.io/issues/6096
=> Using the /associate endpoint in a way that pulls modules

CHANGES/5924.bugfix, pulp_rpm/app/advisory.py
Advisory conflict resolution now check current version first if advisory
resolution is needed.
Required PR: https://github.com/pulp/pulp_rpm/pull/1568
closes: #5924
https://pulp.plan.io/issues/5924
=> Advisory conflict resolution

plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py
Doing one-per-solvable might be more robust, but leads to undesireable
and/or inconsistent behavior depending on the ordering of the
solvable-list. Reverting that specific piece of 39e310ab
closes #6151
https://pulp.plan.io/issues/6151
=> recursive-conservative needs to do one solve.transaction()

CHANGES/6019.feature, pulp_rpm/app/serializers.py, pulp_rpm/app/tasks/copy.py, pulp_rpm/app/viewsets.py, pulp_rpm/tests/functional/api/test_copy.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/functional/utils.py
fixes #6019
https://pulp.plan.io/issues/6019
=> Allow content to be copied by href

plugins/pulp_rpm/plugins/migrations/0048_correct_is_modular_field.py
units_rpm_collection is updated many times unnecessarily.
The update should be done only once for each modulemd to
set is_modular for all rpms in its artifacts.
=> Fix low performance on migration 0048

CHANGES/6297.misc, pulp_rpm/tests/performance/test_sync.py
closes #6297
https://pulp.plan.io/issues/6297
=> Add a test case for syncing centos7 with the immediate policy

CHANGES/6061.feature, flake8.cfg, pulp_rpm/tests/functional/api/test_crud_content_unit.py, pulp_rpm/tests/functional/api/test_crud_remotes.py, pulp_rpm/tests/functional/api/test_download_content.py, pulp_rpm/tests/functional/api/test_download_policies.py, pulp_rpm/tests/functional/api/test_publish.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/api/test_upload.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/functional/utils.py
Refactor funcional tests to use bindings.
- missing sync test
- SyncDiffChecksumPackagesTestCase
- SyncMutatedUpdateRecordTestCase
- SyncMutatedPackagesTestCase
- KickstartSyncTestCase
re: #6061
https://pulp.plan.io/issues/6061
=> RPM tests using bindings

pulp_rpm/app/tasks/publishing.py
This is a leftover artifact from a previous implementation. This change
nearly doubles publish performance (37 seconds -> 23 seconds; centos7)
[noissue]
=> Remove check for contentartifact relative path

CHANGES/6322.bugfix, pulp_rpm/app/kickstart/treeinfo.py
https://pulp.plan.io/issues/6322
closes #6322
=> Deserialize treeinfo files in a scpecific order

plugins/pulp_rpm/plugins/db/models.py
Based on Pavel tests, adding the repo_id index to the erratum_pkglists contributed 20% performance improvement to the regenerate applicability patch.
re #6334
https://pulp.plan.io/issues/6334
=> Speed up the erratum pkglists query by adding a repo_id index

CHANGES/4445.feature, CHANGES/6399.bugfix, docs/_scripts/download.sh, functest_requirements.txt, pulp_rpm/app/constants.py, pulp_rpm/app/tasks/publishing.py, pulp_rpm/tests/functional/api/test_download_content.py, pulp_rpm/tests/functional/utils.py
Publish repository with directory structure sorter by first letter under
'Packages' directory.
Adjust docs' scripts and tests to reflect the change.
```
/Packages/[a-z]/*.rpm
/repodata
```
closes: #4445
closes: #6399
https://pulp.plan.io/issues/4445
https://pulp.plan.io/issues/6399
=> Alphabetical directory structure by default

CHANGES/6473.feature, pulp_rpm/app/modelresource.py
=> Added ModelResource file for import/export support

pulp_rpm/app/tasks/publishing.py
https://pulp.plan.io/issues/6505
=> Fix publication checksum issue

pulp_rpm/app/tasks/synchronizing.py
Otherwise duplicated relations are created.
[noissue]
=> Avoid having the same advisories in one batch.

CHANGES/6442.misc, pulp_rpm/app/constants.py
Advisory package sum types is now shown in lower case for consistency.
re #6442
https://pulp.plan.io/issues/6442
=> Sum type in lower

CHANGES/5739.feature, pulp_rpm/app/advisory.py, pulp_rpm/app/shared_utils.py, pulp_rpm/app/tasks/synchronizing.py
during sync when updated_dates are the same Pulp will check
versions and if there is newer version it is added instead the old one.
closes #5739
https://pulp.plan.io/issues/5739
=> Advisory version is taken to consideration

CHANGES/6519.bug, pulp_rpm/app/depsolving.py, pulp_rpm/tests/functional/api/test_copy.py
=> Fixed copy to always include explicitly-requested packages.

CHANGES/5356.feature, docs/workflows/metadata_signing.rst, docs/workflows/use_pulp_repo.rst, pulp_rpm/app/models/repository.py, pulp_rpm/tests/functional/api/test_consume_content.py, pulp_rpm/tests/functional/content_handler/test_config_repo.py
Closes #5356
https://pulp.plan.io/issues/5356
Opened early for review, this needs tests and docs.
Basically, this PR makes the content server serve config.repo files at `$CONTENT_PATH_PREFIX/rpm/$BASE_PATH/config.repo` that look something like this:
```
[foo]
enabled=1
baseurl=http://localhost:24816/pulp/content/base_path
gpgcheck=0
gpgrepocheck=0
```
Or, when a metadata signing service is enabled:
```
[bar]
enabled=1
baseurl=http://localhost:24816/pulp/content/bar
gpgcheck=0
gpgrepocheck=1
gpgkey=http://localhost:24816/pulp/content/rpm/bar/public.key
```
Additionally, when the signing service is enabled, theres also a public key served at `$CONTENT_PATH_PREFIX/rpm/$BASE_PATH/public.key`.
@dkliban mentions in the issue:
> the new handler should handle a route that looks like this: …
=> Implement .repo file for RPM repositories

CHANGES/4142.misc, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py
Added test for advisories conflict resolution
- test merge of advisories
- test newer version of advisory
- newer added
- newer exists and preserved
- advisory with older update date is not added
- negative tests for wrong/incomplete advisories metadata
re: #4142
https://pulp.plan.io/issues/4142
=> Add test for advisories resolution

CHANGES/6743.bugfix, pulp_rpm/app/migrations/0005_optimize_sync.py, pulp_rpm/app/migrations/0010_revision_null_redo.py
closes: #6743
https://pulp.plan.io/issues/6743
=> Fix borked migration between 3.3.0 and 3.3.1+ schema.

.travis/pre_before_install.sh, CHANGES/6706.misc, coverage.md
Simple markdown table of pulp_rpm feature coverage.
Travis hook to check if this file is updated.
With `[nocoverage]` in commit message this check can be skipped.
closes: #6706
https://pulp.plan.io/issues/6706
=> Feature coverage list

CHANGES.rst, CHANGES/6693.bugfix, CHANGES/6743.bugfix
[noissue]
(cherry picked from commit 4106cfa714198553185f35d883273dcb9d3a20f8)
=> Changelog for 3.3.2

CHANGES/6604.bugfix, coverage.md, pulp_rpm/app/advisory.py, pulp_rpm/tests/functional/api/test_sync.py
There are cases when updated datetime or version are not updated but only some auxiliary fields are.
In this case we can't decide which one is newer and we just pick the incoming one.
closes #6604
https://pulp.plan.io/issues/6604
=> Fix duplicated advisory case when only its metadata changed.

docs/_scripts/docs_check_upload.sh
Removing reference to `copy.sh`
as it was removed on https://github.com/pulp/pulp_rpm/pull/1706
Just realized it after merging my PR:
https://travis-ci.com/github/pulp/pulp_rpm/jobs/338084356
=> Removing reference to copy.sh

CHANGES/6861.bugfix, pulp_rpm/app/migrations/0005_optimize_sync.py, pulp_rpm/app/migrations/0009_revision_null.py
closes: #6861
https://pulp.plan.io/issues/6861
=> Make 'last_sync_revision_number' nullable in all migrations

setup.py
=> Require jsonschema >= 3.0 to have Draft7 support

CHANGES/6820.bugfix, pulp_rpm/app/depsolving.py
closes: #6820
https://pulp.plan.io/issues/6820
=> Fix depsolving bug where not all dependencies are copied

CHANGES/6778.misc, pulp_rpm/tests/functional/api/test_character_encoding.py, pulp_rpm/tests/functional/api/test_consume_content.py, pulp_rpm/tests/functional/api/test_copy.py, pulp_rpm/tests/functional/api/test_crud_content_unit.py, pulp_rpm/tests/functional/api/test_crud_remotes.py, pulp_rpm/tests/functional/api/test_download_content.py, pulp_rpm/tests/functional/api/test_download_policies.py, pulp_rpm/tests/functional/api/test_publish.py, pulp_rpm/tests/functional/api/test_pulp_to_pulp.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/api/test_upload.py, pulp_rpm/tests/functional/content_handler/test_config_repo.py, pulp_rpm/tests/functional/utils.py
https://pulp.plan.io/issues/6778
closes #6778
=> Improving Content handler tests

CHANGES/6656.doc, docs/_scripts/artifact.sh, docs/_scripts/remote.sh, docs/workflows/create_sync_publish.rst
Reflect change of fixtures URL.
Tests base_url is inherited from pulp_smash so change will be reflected
after pulp_smash will be changed.
closes: #6656
https://pulp.plan.io/issues/6656
=> Fixtures URL fix

plugins/pulp_rpm/plugins/distributors/yum/distributor.py
closes #2826
https://pulp.plan.io/issues/2826
=> Ensure repo deletion doesn't fail due to the absence of listing files

docs/installation.rst, docs/quickstart.rst
and pulp_rpm_prerequisites being in the installer now.
Also remove an even older reference to pulp_use_system_wide_pkgs.
[noissue]
re: #6799
Merge the pulp_rpm_prerequisites role into pulp_installer
https://pulp.plan.io/issues/6799
re: #7005
As a user, I can run a single stably-named Ansible role to install Pulp
https://pulp.plan.io/issues/7005
=> Update the installation docs for the new single role

pulp_rpm/app/migrations/0013_RAW_rpm_evr_extension.py, pulp_rpm/app/models/package.py
To explicitly prefix functions, triggers and types with ```pulp_``` to avoid any possible conflict
[noissue]
[nocoverage]
=> Rewrite evr_t migration

CHANGES/6568.bugfix, functest_requirements.txt, pulp_rpm/app/kickstart/treeinfo.py, pulp_rpm/app/tasks/publishing.py, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/performance/test_publish.py
This patch fixes the layout of sub-repos in publications. This patch also generates a TreeInfo file that
contains repository and packages paths that represent the publish structure of an RPM Publication that
contains a DistributionTree.
This patch refactors the TreeInfoData object. The variants and addons properties have been converted from
List to Dict. This enables easier access to their properties when generating the new TreeInfo file.
fixes: #6568
https://pulp.plan.io/issues/6568
=> Fixes how DistributionTrees (kickstart repos) are published.

CHANGES/7134.misc, coverage.md, docs/workflows/create_sync_publish.rst, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/performance/test_sync.py
Test using certificates against CDN (as performance test).
Syncing baseos and appstream repositories.
Checking 'productid' as same repo metadata with different relative paths.
Brief update of docs about remote and using certificates.
closes: #7134
https://pulp.plan.io/issues/7134
=> Test against CDN

pulp_rpm/tests/performance/test_sync.py
Properly un-escape spaces from env variable.
[noissue]
[nocoverage]
=> CDN test space escape fix

CHANGES/7115.bugfix, pulp_rpm/app/exceptions.py, pulp_rpm/app/models/distribution.py, pulp_rpm/app/models/repository.py
closes #7115
https://pulp.plan.io/issues/7115
[nocoverage]
=> Allow only one distribution tree in a repo version at a time.

docs/_static/api.json, pulp_rpm/app/viewsets.py, pulp_rpm/tests/functional/api/test_retention_policy.py
Required PR: https://github.com/pulp/pulpcore/pull/785
[noissue]
=> OpenAPI v3 with drf-spectacular

pulp_rpm/tests/performance/test_sync.py
spaces don't need to be un-escaped by the test
[nocoverage]
[noissue]
=> CDN Performance test

CHANGES/7248.bugfix, pulp_rpm/app/tasks/copy.py
PkgEnv copy depsolving still used removed relations.
Now using group_ids and option_ids.
closes: #7248
https://pulp.plan.io/issues/7248
[nocoverage]
To test this new fixtures needed. Issue filled: https://pulp.plan.io/issues/7253
=> PkgEnv copy depsolving bugfix

CHANGES/5740.feature, pulp_rpm/app/advisory.py, pulp_rpm/tests/functional/api/test_retention_policy.py
Closes a hole in a very specific edge case in advisory-merge during
a copy operation. Requires two advisories that have:
* same id
* same update-date
* package-collections with the same name
* whose package-lists do NOT intersect
Changes one sych collection's name to insure name-uniqueness.
Also, fixed a test_retention test to stop failing due to postgres
non-determinism.
closes #5740
[nocoverage]
=> Teach advisory-merge to avoid package-collection name collisions.

.travis/install.sh, .travis/release.py, .travis/settings.py.j2, .travis/start_container.yaml, CHANGES/6815.feature, coverage.md, pulp_rpm/app/modelresource.py, pulp_rpm/tests/functional/api/test_pulpexport.py, pulp_rpm/tests/functional/api/test_pulpimport.py, template_config.yml
Includes UpdateReference, UpdateCollection, and UpdateCollectionPackage.
Added basic test-skeleton for import/export of pulp_rpm.
fixes #6815
=> Add remaining RPM-entities to import/export.

CHANGES.rst, CHANGES/7228.bugfix, CHANGES/7248.bugfix, CHANGES/7284.bugfix
[noissue]
(cherry picked from commit d0ccd33fc7ad82a615c5e605187646d9a4f609a9)
=> Building changelog for 3.5.1

CHANGES/7354.bugfix, coverage.md, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/performance/test_sync.py
fixes #7354
https://pulp.plan.io/issues/7354
The fedora mirrorlists have a comment at the top. For example:
https://mirrors.fedoraproject.org/mirrorlist?repo=epel-8&arch=x86_64&country=US
```
```
The `fetch_mirror` function's docstring says it skips  non-matching lines, but the task dies trying to access `.group(2)` on `None`.
```
"error": {
"description": "'NoneType' object has no attribute 'group'",
"traceback": "  File \"/usr/local/lib/pulp/lib64/python3.6/site-packages/rq/worker.py\", line 934, in perform_job\n    rv = job.perform()\n  File \"/usr/local/lib/pulp/lib64/python3.6/site-packages/rq/job.py\", line 686, in perform\n    self._result = self._execute()\n  File \"/usr/local/lib/pulp/lib64/python3.6/site-packages/rq/job.py\", line 692, in _execute\n    return …
```
=> Skip comment lines in mirrorlist

CHANGES/7202.bugfix, coverage.md, pulp_rpm/app/depsolving.py
Packages can depend on files e.g. /usr/bin/bash rather than "bash".
We're creating the file list metadata improperly in libsolv so this
wasn't being respected, and the problems would only be apparent in
debug log mode. During the period when we want to catch all these
bugs, "warning" would be more appropriate so that they are highly
visible.
closes: #7202
https://pulp.plan.io/issues/7202
=> Fix RPM copy w/ depsolving when packages depend on a particular file

.travis/before_install.sh, .travis/install.sh, template_config.yml
It would get the wrong pulpcore version and it would break the CI due to OpenAPI change.
We've updated the release guide:
https://pulp.plan.io/projects/pulp/wiki/Pulp3_Release_Guide#Preparing-a-Y-release
[noissue]
[nocoverage]
=> Assuring the right pulpcore version

.travis/before_install.sh, .travis/install.sh, template_config.yml
We've added the step 6:
https://pulp.plan.io/projects/pulp/wiki/Pulp3_Release_Guide#Preparing-a-Y-release
=> Assuring pulpcore 3.6.z

CHANGES/7321.bugfix, pulp_rpm/app/downloaders.py
Fix sync using proxy server.
Custom downloader doesn't passed proxy info.
[nocoverage]
closes: #7321
https://pulp.plan.io/issues/7321
=> Sync through proxy fix

pulp_rpm/tests/performance/test_sync.py
Epel repository doesn't contain distribution tree.
[noissue]
[nocoverage]
=> Fix epel performance test

plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/test/unit/plugins/distributors/yum/test_publish.py
This PR reverts commit ca24ae299 which has been introduced in https://pulp.plan.io/issues/1157 as internal (and no longer valid)
need for the former RCM team.
Currently, the _--local-sqlite_ causes _createrepo_c_ to write to _TMPDIR_ instead of its usual output directory, which causes huge sqlite files to be left under /tmp after cancelled or failed Pulp tasks. /tmp is oftentimes fairly small and this may cause the filesystem to fill up quickly. Pulp already has the concept of creating a temporary working directory for each task under /var/lib/pulp/working and cleaning it up at the end.
Redmine issue for this PR: https://pulp.plan.io/issues/7505
cc @midnightercz, @rohanpm, @ipanova, @goosemania
=> Drop --local-sqlite for createrepo_c to avoid thrashing /tmp

CHANGES/7519.misc, pulp_rpm/tests/functional/api/test_publish.py
=> Updated pulp_rpm tests to stop relying on md5 checksum.

handlers/pulp_rpm/handlers/repo_file.py, plugins/pulp_rpm/plugins/distributors/export_distributor/generate_iso.py, plugins/pulp_rpm/plugins/distributors/yum/metadata/metadata.py, plugins/pulp_rpm/plugins/distributors/yum/publish.py, plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py
Tracked down a lot of makedirs() calls and replaced them with misc.mkdir()
Note: required-PR is needed to fix the permission problem, but the code
will build/work without it.
fixes #7653
Required PR: https://github.com/pulp/pulp/pull/4000
=> Insure that makedirs() results in directories group can write to.

CHANGES/7431.bugfix, coverage.md, pulp_rpm/app/viewsets.py, pulp_rpm/tests/functional/api/test_copy.py, pulp_rpm/tests/functional/api/test_crud_content_unit.py, pulp_rpm/tests/functional/constants.py
User should not be able to remove distribution trees and comps if they are used in repository.
If they are not in repo they will be removed with orphan cleanup as other content.
closes: #7431
https://pulp.plan.io/issues/7431
=> Comps and dist_trees removal

plugins/pulp_rpm/plugins/importers/yum/repomd/primary.py
Happens with Amazon Linux repositories.
fixes #7660
=> Handled the case on sync where package.time or .buildtime are floats

CHANGES/7571.misc, pulp_rpm/tests/functional/api/test_distribution_tree.py, pulp_rpm/tests/functional/constants.py
Sync test:
update main repo of DT
update addon repo of DT
update variant repo DT
remove repository with DT, and orphan cleanup to remove DT
Copy test:
simple copy of DT
copy DT by content specified
closes: #7571
https://pulp.plan.io/issues/7571
=> Distribution tree tests

pulp_rpm/app/tasks/publishing.py
=> Make gpgpcheck options to be a non-required parameter

CHANGES/7691.bugfix, pulp_rpm/app/downloaders.py, pulp_rpm/app/kickstart/treeinfo.py
When .treeinfo file is missing, server returns HTTP 403 instead of HTTP 404 if the autoindex is disabled on the server.
closes: #7691
https://pulp.plan.io/issues/7691
[nocoverage]
=> treeinfo download fix

CHANGES/7807.misc, pulp_rpm/tests/performance/test_publish.py, pulp_rpm/tests/performance/test_sync.py
Distribution trees can't be removed directly with api call,
orphan_cleanup must be used
closes: #7807
https://pulp.plan.io/issues/7807
=> Performance test dist tree removal fix

CHANGES/7698.bugfix, pulp_rpm/app/tasks/synchronizing.py
few downloads or testing remote remomd.xml file happened outside a
working directory
closes: #7698
https://pulp.plan.io/issues/7698
[nocoverage]
[notest]
=> Sync to happen inside working directory

CHANGES/7844.bugfix, pulp_rpm/app/models/repository.py
Remove duplicated Repository.new_version() method
Required PR: https://github.com/pulp/pulpcore/pull/902/
[nocoverage]
related to #6463
https://pulp.plan.io/issues/6463
fixes #7844
(cherry picked from commit ef7033b640a0dc26cc20c7e341cac7b42c13a771)
=> Cherry pick of "Remove duplicated Repository.new_version() method"

plugins/pulp_rpm/plugins/importers/yum/associate.py
If we know there can be nothing copied, exit early rather than doing
useless work.
closes: #7898
https://pulp.plan.io/issues/7898
=> Add an optimization for empty copy operations

pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/performance/test_publish.py
The CentOS 6 repos have now only the readme file http://mirror.centos.org/centos-6/6/readme in them.
[noissue]
=> Stop testing CentOS 6 because it's no longer available.

CHANGES/8114.bugfix, pulp_rpm/app/depsolving.py
Mistake copied from Pulp 2.
re: #8110
https://pulp.plan.io/issues/8110
=> Fix a mistake when producing RPM dependencies.

plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py
Pulp solves wrong dependencies because wrong evr is parsed to
the solvable unit.
closes: #8110
https://pulp.plan.io/issues/8110
=> Fix pulp depsolv issue when copy rpms with recursive config

plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py
This completes the commit d62c61f where pulp solves wrong dependencies
because wrong evr is parsed to the solvable unit.
closes: #8110
https://pulp.plan.io/issues/8110
Signed-off-by: Pavel Moravec <pmoravec@redhat.com>
=> Fix pulp depsolv issue when copy rpms with recursive config 2/2

.ci/ansible/settings.py.j2, CHANGES/7855.feature, pulp_rpm/app/constants.py, pulp_rpm/app/serializers/repository.py, pulp_rpm/app/tasks/publishing.py, pulp_rpm/tests/functional/api/test_publish.py, pulp_rpm/tests/functional/constants.py
Check allowed checksum types when publish.
closes: #7855
https://pulp.plan.io/issues/7855
Required PR: https://github.com/pulp/pulp-smash/pull/1248
[nocoverage]
=> Checksum type check when publish

CHANGES/8223.misc, pulp_rpm/tests/functional/__init__.py, pulp_rpm/tests/functional/api/__init__.py, pulp_rpm/tests/functional/api/test_advisory_upload.py, pulp_rpm/tests/functional/api/test_character_encoding.py, pulp_rpm/tests/functional/api/test_consume_content.py, pulp_rpm/tests/functional/api/test_copy.py, pulp_rpm/tests/functional/api/test_crud_content_unit.py, pulp_rpm/tests/functional/api/test_crud_remotes.py, pulp_rpm/tests/functional/api/test_distribution_tree.py, pulp_rpm/tests/functional/api/test_download_content.py, pulp_rpm/tests/functional/api/test_download_policies.py, pulp_rpm/tests/functional/api/test_fips_workflow.py, pulp_rpm/tests/functional/api/test_publish.py, pulp_rpm/tests/functional/api/test_pulp_to_pulp.py, pulp_rpm/tests/functional/api/test_pulpexport.py, pulp_rpm/tests/functional/api/test_retention_policy.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/api/test_upload.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/functional/utils.py, pulp_rpm/tests/performance/test_publish.py, pulp_rpm/tests/performance/test_pulp_to_pulp.py, pulp_rpm/tests/performance/test_sync.py
=> Remove extraneous coding= from tests - Python3 is always UTF8.

.ci/ansible/settings.py.j2, .ci/ansible/start_container.yaml, .github/workflows/scripts/before_install.sh, .github/workflows/scripts/install.sh, .github/workflows/scripts/script.sh, template_config.yml
This accommodates for a change in pulpcore that will effect the CI.
https://github.com/pulp/pulpcore/pull/1102
[noissue]
=> Update plugin template

CHANGES/8249.bugfix, pulp_rpm/app/advisory.py, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/api/test_consume_content.py, pulp_rpm/tests/functional/api/test_sync.py
If incoming and existing advisories are 'the same', but one's pkglist is
a proper-subset of the other - choose the larger pkglist.
fixes #8249
=> Fixed another advisory-conflict edge case.

CHANGES/8278.misc, pulp_rpm/app/constants.py, pulp_rpm/app/tasks/publishing.py, pulp_rpm/tests/functional/api/test_publish.py
More detailed error message when user tries to publish package with
forbidden checksum type.
closes: #8278
https://pulp.plan.io/issues/8278
=> Verbose checksum publish error message

CHANGES/8392.misc, pulp_rpm/tests/performance/test_sync.py
=> Skipped centos7-immediate test.

CHANGES/7995.bugfix, pulp_rpm/app/downloaders.py, pulp_rpm/app/kickstart/treeinfo.py, pulp_rpm/app/models/repository.py, pulp_rpm/app/shared_utils.py, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/unit/test_shared_utils.py
* Added shared_utils.urlpath_sanitize() to fill the niche that urljoin()
was being (incorrectly) used for.
* Added unit-tests for shared_util.
* Fixed a problem with shared_utils.is_previous_version() that unit-tests exposed.
=> Teach pulp_rpm to only use urljoin() where it really needs urljoin().

CHANGES.rst
[noissue]
(cherry picked from commit b66b7b15cb60f5c20125b0d2a84ddead2b9ba5d6)
=> CP changelog for 3.9.1

CHANGES/8250.feature, docs/index.rst, docs/settings.rst, pulp_rpm/app/advisory.py, pulp_rpm/app/settings.py, pulp_rpm/tests/functional/api/test_sync.py
=> Added ALLOW_UNSAFE_ADVISORY_CONFLICT_RESOLUTION. Default is False.

pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/performance/test_sync.py
Also taught EPEL-mirror-test to not care about resync, different
returns from the mirrorlist could cause the test to fail if the
resync chose a new mirror that had different repodata.
[noissue]
=> Fixed tests that relied on now-unresponsive duke.edu site.

CHANGES/8467.bugfix, pulp_rpm/app/tasks/synchronizing.py
re: #8467
https://pulp.plan.io/issues/8467
=> Reduce memory consumption when syncing extremely large repositories

CHANGES/8623.bugfix, pulp_rpm/app/kickstart/treeinfo.py
=> properly call tree.get() for timestamp handling

CHANGES/7282.bugfix, pulp_rpm/app/advisory.py, pulp_rpm/app/serializers/advisory.py, pulp_rpm/tests/functional/api/test_advisory_upload.py
=> Taught advisory-upload to handle advisory-conflicts better.

docs/workflows/copy.rst
Before this patch, the note about `dependency_solving` and the preceding paragraph gave two different default values ('**enabled by default**' vs 'currently "false"').  The API docs and the [source][0] say the default is currently `True`, so this patch updates the note text to reflect that.
[0]: https://github.com/pulp/pulp_rpm/blob/9a91832a39c924a77413fa31960996f9b2d38556/pulp_rpm/app/serializers/repository.py#L301-L303
[noissue]
=> Resolve conflicting dependency_solving defaults

CHANGES/8764.misc, pulp_rpm/app/constants.py, pulp_rpm/app/tasks/synchronizing.py
The existing code makes it really difficult to manage all of the places where new logic needs to be inserted.  e.g. every type of metadata is downloaded in a separate function, and tons of data is being passed around unecessarily.  Converting some classes back into functions, and merging some functions that don't really serve any benefit in being separate.
[noissue]
=> Refactor to make metadata mirroring easier

CHANGES/8683.bugfix, pulp_rpm/app/serializers/advisory.py, pulp_rpm/tests/functional/api/test_advisory_upload.py
Prior to this fix, a failure in create() would result in being
unable to create() advisories again, ever, until the advisory
with a blank digest is removed "by hand".
fixes #8683
=> Handle temporary-blank-digest advisory in create() error path(s).

CHANGES/7904.bugfix, pulp_rpm/app/modelresource.py, pulp_rpm/tests/functional/api/test_pulpimport.py
Ordering-on-export insures we won't deadlock at import-time
when repo-versions have overlapping content.
Accepting this change without the referenced pulpcore fix
will result in fixing the deadlock, but generating unique-constraint
violations in the same place at import-time.
fixes #7904
Requires PR: https://github.com/pulp/pulpcore/pull/1278
=> Ordered querysets in ModelResources for export.

CHANGES.rst, CHANGES/8638.feature
[noissue]
(cherry picked from commit 6d61eb4a336493f1d0e3dcfa9fdfbe4c9aceab1e)
=> CP changelog for 3.11.0

CHANGES/8716.bugfix, pulp_rpm/app/models/advisory.py
If collections/references/packagelists aren't explicitly ordered,
you can end up with two identical advisories having different
digests (and therefore being different Artifacts).
Note: there is no test with this PR, because forcing the
undesireable behavior requires a heavy concurrent load on
postgres, and even then may not happen, depending on externals
like disk-speed and postgres-caching. See the referenced issue
for a manual reproducer.
fixes #8708
Required PR: https://github.com/pulp/pulp_rpm/pull/1981
[nocoverage]
=> Ensure sub-object ordering when computing an UpdateRecord's digest.

CHANGES/8807.bugfix, pulp_rpm/app/kickstart/treeinfo.py, requirements.txt
closes #8807
https://pulp.plan.io/issues/8807
=> Fix publication of a distribution tree for productmd 1.33+

CHANGES/8814.bugfix, pulp_rpm/app/serializers/modulemd.py
Since Django 2.1 BooleanField is required=True by default.
closes #8814
https://pulp.plan.io/issues/8814
=> Mark static_context as not required

CHANGES/8813.bugfix, coverage.md, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/api/test_sync.py
backports #8812
https://pulp.plan.io/issues/8812
fixes #8813
(cherry picked from commit 86ccfd419984cedb7c6c56ea2f88c16e8f0ed8dc)
=> CP srpm skip fix for 3.11

CHANGES.rst
[noissue]
(cherry picked from commit 57764c7d289d03d2f83dd2e216867ef58b2c77cc)
=> CP changelog for 3.11.1

CHANGES/8952.bugfix, pulp_rpm/app/tasks/synchronizing.py
=> Made modulemd-parsing come first, so package-parsing can be correct.

CHANGES/8944.bugfix, CHANGES/8955.bugfix, pulp_rpm/app/metadata_parsing.py, pulp_rpm/app/models/repository.py, pulp_rpm/app/tasks/synchronizing.py
Handle duplicate packages in upstream repos
Some repositories have some packages listed in the metadata twice. This
shouldn't happen (but it does). createrepo_c deduplicates by virtue of
parsing everything into a dict keyed by pkgid, but the iterative parser
does not. This eventually results in a mismatch once the iterative
parser comes across a package that the createrepo_c primary parser
already handled. So we keep a list of pkgid's we've already written out
in order to skip them once the iterative parser hits them a 2nd (or 3rd,
etc.) time.
closes: #8944
https://pulp.plan.io/issues/8944
Fix filelists and changelogs not being properly parsed
closes: #8955
https://pulp.plan.io/issues/8955
=> Fix sync issues w/ new iterative parser

pulp_rpm/tests/functional/api/test_pulpexport.py, pulp_rpm/tests/functional/api/test_pulpimport.py
To address pulpcore backward incompatible change.
[noissue]
=> Rename ExportersCoreExportsApi to ExportersPulpExportsApi.

CHANGES/7350.misc, coverage.md, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/api/test_sync.py
closes: #9021
https://pulp.plan.io/issues/9021
closes: #7350
https://pulp.plan.io/issues/7350
=> Fix syncs from file:// repos and add a test

CHANGES/8787.bugfix, pulp_rpm/app/tasks/synchronizing.py
If Pulp receives a ClientResponseError when attempting to download a
file, but the status code isn't 404, then we go down the wrong code
path.
closes: #8787
https://pulp.plan.io/issues/8787
=> Fix unbound local error when Pulp receives a non-404 ClientResponseError

CHANGES/9064.bugfix, pulp_rpm/app/downloaders.py
fixes: #9064
https://pulp.plan.io/issues/9064
=> Use proxy auth credentials of a Remote.

CHANGES/8275.bugfix, CHANGES/9096.bugfix, coverage.md, pulp_rpm/app/advisory.py, pulp_rpm/app/tasks/publishing.py
* Some metadata-files can have '-' in the filename
* Some advisory datetimes are just timestamps.
fixes #8275
[nocoverage]
=> Adapted to some (more) SUSE repo edge-cases.

CHANGES/9111.bugfix, pulp_rpm/app/tasks/synchronizing.py
[nocoverage'
closes: #9111
https://pulp.plan.io/issues/9111
=> Filter out disallowed checksums for files in extra_files.json

pulp_rpm/app/advisory.py
Needed for Django 3.2, it works both ways in Django 2.2.
[noissue]
=> Evaluate collection package queryset in the advisory merge explicitly.

CHANGES/9098.bugfix, pulp_rpm/app/tasks/synchronizing.py
Fix mirrored repositories for repos with distribution trees
Two problems:
* Mirrored repositories were creating one publication per
sub-repository, which is in contrast to the way that pulp normally
works. Standard publish puts the sub-repos into the same publication
in a direct sub-directory because this is the only way to have
everything distributed properly. Otherwise the other publications are
in-accessible.
* Even once we fix that, we still have the issue that the original
.treeinfo contains the original relative paths. So even for the
mirrored case, we still have to rewrite the .treeinfo data to look at
the new repos. Luckily it's not signed or checksummed so we aren't
prevented from doing this.
closes: #9098
https://pulp.plan.io/issues/9098
=> Fix mirrored repositories for repos with distribution trees

CHANGES/8972.misc, CHANGES/9107.bugfix, coverage.md, functest_requirements.txt, pulp_rpm/app/metadata_parsing.py, pulp_rpm/app/settings.py, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/api/test_publish.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/functional/content_handler/test_config_repo.py, pulp_rpm/tests/functional/utils.py
.findall() is not reliable in the face of namespaces. Don't use it
anymore.
closes: #9107
https://pulp.plan.io/issues/9107
=> Fix unreliable filelist parsing

CHANGES/8713.bugfix, pulp_rpm/app/tasks/publishing.py
Pulp 2 relies on the packagelist element being present, even if it's empty.
It also seems to be a mandatory element according to this unofficial spec
https://pagure.io/rpm-metadata/blob/master/f/fedora/comps-schema/comps.dtd#_6
Before this fix, the packagelist element would only be generated if there is
at least one package in a group.
closes #8713
https://pulp.plan.io/issues/8713
=> Configure libcomps to always generate `packagelist` element within a package group.

CHANGES/8875.bugfix, pulp_rpm/app/downloaders.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py
Amazon (for example) will reject RPMs with '+' in the filename
if it's not url-encoded.
fixes #8875.
=> Taught downloader to url-encode so odd backends can find content.

CHANGES/9253.bugfix, pulp_rpm/app/tasks/synchronizing.py
=> Runs all DB queries synchronously during a sync task.

CHANGES/9230.bugfix, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/api/test_publish.py
closes: #9230
https://pulp.plan.io/issues/9230
=> Fix mirror=True not including files declared in .treeinfo in publication

CHANGES/9096.bugfix
It was backported by accident, because 2 issues were associated with a single PR.
[noissue]
=> Exclude a changelog entry

CHANGES/9303.bugfix, coverage.md, pulp_rpm/app/models/package.py, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/api/test_character_encoding.py, pulp_rpm/tests/functional/api/test_consume_content.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py
This metadata feature is incompatible with metadata mirroring. Reject
repo syncs in this case and handle it more appropriately in other cases.
closes: #9303
https://pulp.plan.io/issues/9303
=> Fix handling of location_base / xml:base

CHANGES/9328.bugfix, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py
Some repos use location_href values that point outside of the
repository. We cannot support this in mirror mode because we cannot
write paths outside of the repository namespace.
closes: #9328
https://pulp.plan.io/issues/9328
=> Dealt with another situation incompatible with mirror syncing

CHANGES/9448.bugfix, pulp_rpm/app/tasks/publishing.py
closes #9448
[nocoverage]
[notest]
=> Use checksum type of a package for publication if it's not configured.

CHANGES/9472.bugfix, pulp_rpm/app/downloaders.py
backports #9464
[nocoverage]
fixes #9472
(cherry picked from commit 6cbae29b4a08e5452f3634c204a4266f344f8b6c)
=> Restore embedded-basic-auth-in-url functionality.

CHANGES.rst
[noissue]
(cherry picked from commit e758df9d3f09ffa8f4d52f63172769bda34ac224)
=> Cherry-pick 3.14.6 changelog and put releases in order by version

CHANGES/9551.bugfix, pulp_rpm/app/serializers/package.py, pulp_rpm/app/shared_utils.py, pulp_rpm/app/tasks/publishing.py, pulp_rpm/app/tasks/synchronizing.py
Also log the real traceback to make it possible to troubleshoot the failure.
closes #9551
https://pulp.plan.io/issues/9551
=> Ensure that /tmp is not used but the current worker working directory.

CHANGES/9565.bugfix, pulp_rpm/app/tasks/synchronizing.py
In case that only a subtree is synced, it can happen that the PRIMARY_REPO key does not exists in repo_sync_results and the sync failed with accessing a not existing key at the end.
closes: #9565
https://pulp.plan.io/issues/9565
=> Subtree only sync is failing 

plugins/pulp_rpm/plugins/distributors/yum/metadata/metadata.py, plugins/pulp_rpm/plugins/distributors/yum/metadata/repomd.py
Read the metadata file in chunk when calculating its checksum to
save memory.
closes: #9553
https://pulp.plan.io/issues/9553
=> Reduce the memory usage when calculating checksum

plugins/pulp_rpm/plugins/db/models.py
Some filenames in filelist.xml might contain special characters that might cause Django
template render error. They need to be escaped.
closes: #9559
https://pulp.plan.io/issues/9559
=> Escape django template syntax in xml when rendering filelist

CHANGES/9636.bugfix, pulp_rpm/app/tasks/publishing.py
It happens when a checksum is used as a filename for a custom repo metadata file.
All kudos for the fix go to @hao-yu.
closes #9636
https://pulp.plan.io/issues/9636
=> Fix FileNotFoundError during sync or pulp-2to3 migration

pulp_rpm/app/downloaders.py, pulp_rpm/tests/unit/test_uln_download.py, requirements.txt
Apparently, there was stuff wrong with the http-proxy support as well.
One of the main problems was that proxy-authentication has not been supported.
The changes required for aiohttp-xmlrpc > 1.3.2 are due to https://github.com/mosquito/aiohttp-xmlrpc/pull/48
RFC for whether I should open separate PRs and whether we need tickets for these changes.
Relates to https://github.com/pulp/pulp_rpm/pull/2200
=> Fix uln remotes http proxy

CHANGES/2326.bugfix, pulp_rpm/app/kickstart/treeinfo.py, pulp_rpm/app/tasks/synchronizing.py
Affects sync and pulp-2to3-migration(if the modified stage is used).
[noissue]
Mostly a cherry-pick from c6b97ca5598af73f7ad037a1a7b5d9a604b4d697.
Resolved conflicts + added handling of duplicates in one batch,
needed for pulp-2to3-migration.
=> [3.11.z fix] DistributionTree workaround

CHANGES/2356.bugfix, pulp_rpm/app/migrations/0039_disttree_digest.py
Users can't upgrade to pulp_rpm 3.17 without this fix, if they have
distribution tree content.
There is no harm or data problems in 3.17.0, just inability to upgrade to,
so one can safely rollback to 3.16.2.
closes #2356
=> Fix data migration for pulp_rpm 3.17.0

CHANGES/2363.bugfix, pulp_rpm/app/metadata_parsing.py
Small adjustments to changelog limiting
Sort the changelog entries by date first. I was hoping this wasn't
necessary since both legacy createrepo and createrepo_c use a specific
order, but I discovered that Oracle Linux used to use reverse
chronological order. I have no idea what tool they used but lets play
it safe for now
closes #2363
https://github.com/pulp/pulp_rpm/issues/2363
=> Apply a sort prior to the changelog limit

CHANGES/2379.bugfix, pulp_rpm/app/tasks/publishing.py
A backport of https://github.com/pulp/pulp_rpm/pull/2380.
(cherry picked from commit ecfdb826f1a337c68d4ce5ed8e15a4dae721691a)
=> [PR #2380/ecfdb826 backport][3.11] Make sure more file descriptors are closed properly

pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/performance/test_publish.py, pulp_rpm/tests/performance/test_pulp_to_pulp.py, pulp_rpm/tests/performance/test_sync.py
CentOS 8 has been archived, repo links are dead. We could use the vault repos but they are already underprovisioned according to some CentOS project members.
Switching to use 8stream instead.
[noissue]
=> Update CentOS URLs

pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/performance/test_sync.py
The CentOS 8 Stream kickstart repos appear to have been removed, but the
"normal" repos have all of the kickstart metadata, so we're exercising
all the correct codepaths.
[noissue]
=> Remove CentOS 8 Stream kickstart tests

CHANGES/2428.bugfix, pulp_rpm/app/serializers/repository.py
=> Username and password fields on ULN Remotes should be hidden

CHANGES/2430.bugfix, pulp_rpm/app/serializers/repository.py
Since a default value is provided on the publication serializer, it can't properly fall back to the repository settings: https://github.com/pulp/pulp_rpm/blob/main/pulp_rpm/app/viewsets.py#L272-L275
We need it to return `None` when not provided so that ^ line can work properly.
closes #2430
=> Fix a serializer viewset interaction issue

CHANGES/2243.bugfix, pulp_rpm/app/kickstart/treeinfo.py, pulp_rpm/tests/functional/api/test_distribution_tree.py
fixes #2243.
(cherry picked from commit 8500b924330a0338f4c315bc17c44bcd1322518b)
=> Fixed treeinfo,images to correctly handle rhel5 treeinfo format.

pulp_rpm/tests/functional/api/test_sync.py
to reflect expected error string from https://github.com/pulp/pulpcore/blob/main/pulpcore/download/base.py#L105
[noissue]
=> Test sync excepted string

CHANGES/2504.bugfix, pulp_rpm/app/serializers/__init__.py, pulp_rpm/app/viewsets/acs.py, pulp_rpm/tests/functional/api/test_acs.py
Introduce new serializer for ACS refresh to avoid
bidnings requires ACS name for refresh.
closes: #2504
https://github.com/pulp/pulp_rpm/issues/2504
=> ACS refresh for bindings

plugins/pulp_rpm/plugins/importers/yum/parse/rpm.py, plugins/pulp_rpm/plugins/importers/yum/upload.py
Currently, no changelog limits are applied either when the
packages are uploaded or the metadata is published. This
resulted in extreme growth of other.xml metadata over time.
It's causing a multitude of problems like consuming excessive
memory and causing OOM while running "yum repoquery --changelog",
sync failure with timeout to download other.xml etc.
Hence, added a changelog limit, that will be picked from the
config or default to 10, to limit the number of changelogs to
be included in the xml.
=> [Pulp 2] Add changelog limit to control the size of RPM metadata

CHANGES/2440.feature, docs/_scripts/package.sh, docs/_scripts/package_cli.sh, docs/workflows/upload.rst, pulp_rpm/app/models/package.py, pulp_rpm/app/serializers/package.py, pulp_rpm/app/shared_utils.py, pulp_rpm/tests/functional/api/test_upload.py
User doesn't have to specify ``relative_path``.
It is generated by NVRA info from package if not specified.
closes: #2440
https://github.com/pulp/pulp_rpm/issues/2440
=> Optional relative_path when upload

CHANGES/2667.bugfix, pulp_rpm/app/tasks/synchronizing.py
Improved error message for Alternate Content Source refresh when it has
insufficient permissions.
closes: #2667
https://github.com/pulp/pulp_rpm/issues/2667
=> Improved error message for ACS

CHANGES/2403.bugfix, pulp_rpm/app/shared_utils.py
Fix temporary package upload path to not contain slashes.
closes: #2403
https://github.com/pulp/pulp_rpm/issues/2403
=> [3.17] fix temp upload

plugins/pulp_rpm/plugins/importers/yum/repomd/metadata.py
This fixes a bug in sync where sync fails due to open-size tag being empty but existing in repomd file. It works fine if there is a value for size or if there is no value for open_size, but if it does exist but has no value.
I was trying to sync Rocky BaseOS repo which has the following value set for open-size tag:
`<open-size/>`
Repomd file link for reference: [https://download.rockylinux.org/pub/rocky/8/BaseOS/x86_64/os/repodata/repomd.xml](url)
Due to that, we get the following error when running sync.
>  file_info['open_size'] = int(open_size_element.text)\nTypeError: int() argument must be a string or a number, not 'NoneType'\n", 
That is why we should also check if open_size_element has a text attribute.
=> Check if open_size_element has text attribute

CHANGES/2407.bugfix, pulp_rpm/app/tasks/publishing.py
Some repos are incorrect up in such a way that they bypass our protections
against this scenario and Pulp ends up generating inappropriate
metadata, which then gets caught if (another) Pulp tries to sync those
repos.
closes #2407
=> Ensure that Pulp never publishes repos with duplicate NEVRA

CHANGES/2691.bugfix, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/api/test_retention_policy.py
For various reasons rejecting repos with duplicate NEVRA entirely in "mirror_complete" mode is probably not acceptable (there's just too many such repos, it's user-unfriendly) and yet permitting it in the "mirror_content_only" mode creates issues because the filenames overlap (when manually publishing the repo, only one package can be associated with a path e.g. `Packages/f/foo-1.2.3-4.noarch.rpm`, and if multiple packages exist for a given filename in the repo, it might not be the same one the Yum / DNF / Zypper client selects, resulting in checksum mismatches at the client)
You see this 2nd problem in repos with packages of the same NEVRA and filename in different directories.
We solve both these problems by:
* Only syncing one package per NEVRA, even if the metadata contains >1
* …
=> Allow syncing duplicate NEVRAs, pick the newest one

CHANGES/2691.bugfix, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/api/test_retention_policy.py
For various reasons rejecting repos with duplicate NEVRA entirely in
mirror_complete modes is probably not acceptable (there's just too
many, it's user-unfriendly) and yet permitting it as the
mirror_content_only mode creates issues because the location_href values
overlap (when manually publishing the repo, only one package can be
associated with a path e.g. Packages/f/foo-1.2.3-4.noarch.rpm, and it
might not be the same one the Yum / DNF / Zypper client selects,
resulting in checksum mismatches at the client)
We solve both these problems by:
* Only syncing one package per NEVRA, even if the metadata contains >1
* Matching the heuristics of Yum / DNF when picking which to skip so
that clients don't request the ones we don't sync (in mirror_complete
mode where the metadata contains all of …
=> [3.14] Allow syncing duplicate NEVRAs, pick the newest one

CHANGES/2733.bugfix, pulp_rpm/app/models/distribution.py
=> Fixed orphan cleanup task failing with `Repository matching query does

CHANGES/2620.misc, coverage.md, pulp_rpm/tests/functional/api/test_modular.py, pulp_rpm/tests/functional/conftest.py
Simple test to check that modular packages are marked as modular
package. Added missing pytest config to run the test.
closes: #2620
https://github.com/pulp/pulp_rpm/issues/2620
=> [3.17] Test ``is_modular``

CHANGES/2648.bugfix, pulp_rpm/app/modelresource.py
Deduplicate update collection packages at import export time.
To fix Alma linux repositories which has duplicated collection packages in advisories.
closes: #2648
https://github.com/pulp/pulp_rpm/issues/2648
=> Advisory package import/export fix

CHANGES/2777.bugfix, pulp_rpm/app/migrations/0044_noartifact_modules.py
fix migration from modular artifact snippet to db snippet
closes: #2777
https://github.com/pulp/pulp_rpm/issues/2777
=> [3.18] Fix migration

CHANGES/2786.bugfix, pulp_rpm/app/migrations/0045_modulemd_fields.py
if already run migration with ``3.18.1`` modular metadata are corrupted.
cannot use data repair command as modular Models are broken and django cannot work with them in usual way.
closes: #2786
https://github.com/pulp/pulp_rpm/issues/2786
=> Fix modular metadata

CHANGES/2795.bugfix, pulp_rpm/app/models/custom_metadata.py, pulp_rpm/app/tasks/publishing.py, pulp_rpm/app/tasks/synchronizing.py
closes #2795
We already ignore these metadata types during sync, but if they were synced before this functionality was available, we should ignore them during publish as well!
=> Do not publish unsupported metadata

CHANGES/2735.bugfix, pulp_rpm/app/modulemd.py, pulp_rpm/app/tasks/synchronizing.py
extend RpmQueryExisting stage to fix missing modular snippets.
closes: #2735
https://github.com/pulp/pulp_rpm/issues/2735
=> Modular data re-sync repair

CHANGES/2764.feature, pulp_rpm/app/serializers/package.py, pulp_rpm/tests/functional/api/test_crud_content_unit.py, pulp_rpm/tests/functional/api/test_upload.py
Pulpcore contains a new feature since version 3.22.0, which changes Pulp's behavior when there's an attempt to re-upload existing content. Instead of raising an exception, the pulp_href of the existing unit is returned, while this unit is possibly also added to the specified repository.
closes #2764
=> Added support for reusing duplicate content

CHANGES/2832.misc, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/performance/test_sync.py
Changed reliance on sonic-playground-epel8 to fedora36-server.
fixes #2832
=> Can't use an EPEL mirror for kickstart-tests anymore.

CHANGES/2278.bugfix, pulp_rpm/app/tasks/synchronizing.py
DistributionTree digest and subrepo-names now both end with the pulp-id of the "owning" Repository, making them unique to that repo and therefore protected from concurrent-updates against anything that is changing that Repository.
Addon/Variant/Image are transitively made unique by virtue of having their DistributionTree be part of their unique-together.
Sub-repo **content** (e.g. Packages et al) are de-duplicated via their existing uniqueness constraints.
The end result is a minor increase in Content objects (i.e., DistTrees/Addons/Images/Variants that used to have only one instance are now one-per-containing-repo), and a small impact on subrepo-syncing (since previously-unique subrepos will now have a first-sync that would have been skipped). Content will continue to only be sync'd …
=> Fixed concurrent-ks-tree-syncs by making disttree ID repo-specific.

CHANGES/2858.bugfix, pulp_rpm/app/models/package.py
These are rare but apparently exist. The metadata may omit the "epoch" attribute from the version tag, and createrepo_c will emit None. The RpmVersionField can't handle that.
closes #2858
=> Fix syncing repositories with missing epoch metadata

pulp_rpm/app/modulemd.py, pulp_rpm/app/schema/modulemd.json, pulp_rpm/app/tasks/synchronizing.py
There exists a modulemd whose license has no 'content', and which has no artifacts. Adapt the code that assumes modulemds all Make Sense.
Coverage is in the 'performance' tests - that's what uncovered the problems in the first place.
[noissue]
[nocoverage]
=> Fixes for centos8-appstream-modulemd problems.

CHANGES/2848.feature, docs/workflows/create_sync_publish.rst, pulp_rpm/app/constants.py, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/api/test_distribution_tree.py
Lets user sync only the parent repository, and not any of the treeinfo data or subrepos.
closes #2848.
=> Added 'treeinfo' to available skip-types at sync time.

CHANGES/2753.bugfix, pulp_rpm/app/modulemd.py, pulp_rpm/app/shared_utils.py, pulp_rpm/app/tasks/comps.py, pulp_rpm/app/tasks/synchronizing.py
DNF supports compressed comps metadata - compression type is determined by filename and happens transparently the same for comps as it does for any other file.
closes #2753
=> Allow "group" aka comps metadata to be compressed

CHANGES/2753.bugfix, pulp_rpm/app/shared_utils.py, pulp_rpm/app/tasks/comps.py, pulp_rpm/app/tasks/synchronizing.py
DNF supports compressed comps metadata - compression type is determined by filename and happens transparently the same for comps as it does for any other file.
closes #2753
=> [3.18] Allow "group" aka comps metadata to be compressed

CHANGES/2764.feature, pulp_rpm/app/serializers/package.py, pulp_rpm/tests/functional/api/test_crud_content_unit.py, pulp_rpm/tests/functional/api/test_upload.py
Reverting because there are a number of upload-related issues in pulp_rpm, and we don't want to make things worse in the released code until we've resolved what to do with/for them.
This reverts commit 54ec7c3f2e0a5a2263054a685ed68213a85b70f4.
=> Revert "Added support for reusing duplicate content"

CHANGES/2752.bugfix, CHANGES/2967.bugfix, pulp_rpm/app/tasks/publishing.py
This should reduce the amount of artifact churn when certain metadata files are published repeatedly unchanged. Also, it should make it easier to read and compare.
closes #2752
https://github.com/pulp/pulp_rpm/issues/2752
=> Publish all metadata with a total ordering

CHANGES/2961.bugfix, pulp_rpm/app/modulemd.py, pulp_rpm/app/tasks/publishing.py
Probably an actual yaml parser wouldn't care.
closes #2961
https://github.com/pulp/pulp_rpm/issues/2961
=> Fix a minor parsing bug that causes pulp-to-pulp sync to fail

CHANGES/2998.bugfix, pulp_rpm/app/modulemd.py, pulp_rpm/app/schema/modulemd.json
Trivial fix, allows modulemd version data to be of type string if that string represents a valid integer, matching very basic regex.
=> Allow string integers in modulemd version

pulp_rpm/tests/functional/api/test_sync.py
- test_mutated_packages
- test_sync_diff_checksum_packages
[noissue]
=> Remove the parallel mark from a few sync tests

pulp_rpm/tests/functional/api/test_pulpimport.py
This functionality will never run in parallel w/ syn(), against which it can occasionally deadlock.
[noissue]
=> Serialize pulpimport tests.

CHANGES/3039.bugfix, pulp_rpm/app/serializers/package.py
The location_href and relative_path will be mismatched causing 404 Not Found error on clients if user uploaded a rpm and provided a "relative_path" with non-standard rpm naming convention.
closes #3039
=> Fix client getting HTTP 404 Not Found when downloading rpm

pulp_rpm/app/serializers/package.py
Canonical package names don't generally include the epoch, ever.
[noissue]
=> Fix a small package name bug

CHANGES/3039.bugfix, pulp_rpm/app/serializers/package.py
The location_href and relative_path will be mismatched causing 404 Not Found error on clients if user uploaded a rpm and provided a "relative_path" with non-standard rpm naming convention.
closes #3039
(cherry picked from commit 949424d83aca0fbab3a13175fbfc8de8c40febf5)
=> [3.18] Fix client getting HTTP 404 Not Found when downloading rpm

CHANGES/3039.bugfix, pulp_rpm/app/serializers/package.py
The location_href and relative_path will be mismatched causing 404 Not Found error on clients if user uploaded a rpm and provided a "relative_path" with non-standard rpm naming convention.
closes #3039
(cherry picked from commit 408b59b3e603816c45c8b28f5cfc5251601c1bfa)
=> [3.19] Fix client getting HTTP 404 Not Found when downloading rpm

CHANGES/2880.misc, pulp_rpm/tests/functional/api/test_fips_workflow.py
This file was really large and I didn't want to re-write all of it, so instead I updated the class to get the client apis from the pytest fixtures & removed any dependencies on pulp_smash.
fixes: #2880
=> Refactor test_fips_workflow to use pytest

CHANGES/3095.misc, pulp_rpm/tests/conftest.py, pulp_rpm/tests/functional/conftest.py, pulp_rpm/tests/performance/test_publish.py, pulp_rpm/tests/performance/test_pulp_to_pulp.py, pulp_rpm/tests/performance/test_sync.py
Moved fixtures shared between 'functional' and 'performance' up one level.
Fixed some problems w/ the tests themselves as well.
fixes #3095
=> Fixed performance-tests.

CHANGES/3119.bugfix, pulp_rpm/app/depsolving.py, pulp_rpm/tests/functional/conftest.py
closes #3119
https://github.com/pulp/pulp_rpm/issues/3119
(cherry picked from commit 7b6ecfc72d32053923b7cbc9be72c79fcb28cd9b)
=> 3.18 backports

doc_requirements.txt
=> Pin Sphinx to <7.0 due to incompatibility in our docs-template.

CHANGES/3170.bugfix, pulp_rpm/app/models/repository.py
This fix just strips out the invalid characters in the repo id, which is probably preferable to failing the publication or adding a restriction on distro name which users may currently be relying on.
closes #3170
=> Don't write invalid characters to a repo id, even if the distro name contains them.

CHANGES/3215.feature, pulp_rpm/app/viewsets/package.py
=> Add package filename filter

pulp_rpm/tests/functional/api/test_pulpimport.py
I've seen pulp rpm nightly is broken for the same reason as pulp deb.
Recent change in pulpcore changes the export data from a gzipped file to just a tar archive. See https://github.com/pulp/pulpcore/pull/4477
The tests however are now looking for the wrong file type. This change should fix it.
=> Fix import tests using gzip files

CHANGES/3275.bugfix, pulp_rpm/app/tasks/synchronizing.py
=> Removed extraneous refs to UpdateReference/Collection.domain.

CHANGES/3286.bugfix
So that we can do a release and not have an empty changelog.
[noissue]
=> Add a changelog for the last PR

pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py
=> Add a test for syncing repos with zstd-compressed metadata

.github/workflows/scripts/post_before_script.sh, functest_requirements.txt, pulp_rpm/tests/functional/api/test_character_encoding.py, pulp_rpm/tests/functional/api/test_consume_content.py, pulp_rpm/tests/functional/api/test_crud_content_unit.py, pulp_rpm/tests/functional/api/test_download_content.py, pulp_rpm/tests/functional/api/test_fips_workflow.py, pulp_rpm/tests/functional/api/test_publish.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/api/test_upload.py, pulp_rpm/tests/functional/conftest.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/functional/content_handler/test_config_repo.py, pulp_rpm/tests/functional/utils.py, pulp_rpm/tests/performance/test_publish.py
* Skip test that uses DRPM fixture, for now. It's not worth maintaining the fixture, and in the future we ought to be able to do this test without it.
* Made metadata downloading util agnostic to compression type
* Ditch all usages of http_get and http_get_headers for requests
* Fix CI after working directory adjustment in the template
=> [3.22] Remove drpm test and fix borked CI (#3323)

.github/workflows/scripts/post_before_script.sh, functest_requirements.txt, pulp_rpm/tests/functional/api/test_advisory_upload.py, pulp_rpm/tests/functional/api/test_character_encoding.py, pulp_rpm/tests/functional/api/test_consume_content.py, pulp_rpm/tests/functional/api/test_crud_content_unit.py, pulp_rpm/tests/functional/api/test_download_content.py, pulp_rpm/tests/functional/api/test_fips_workflow.py, pulp_rpm/tests/functional/api/test_publish.py, pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/api/test_upload.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/functional/content_handler/test_config_repo.py, pulp_rpm/tests/functional/utils.py, pulp_rpm/tests/performance/test_publish.py, requirements.txt
* Skip test that uses DRPM fixture, for now. It's not worth maintaining the fixture, and in the future we ought to be able to do this test without it.
* Made metadata downloading util agnostic to compression type
* Ditch all usages of http_get and http_get_headers for requests
* Fix CI after working directory adjustment in the template
=> [3.19] Remove drpm test and fix borked CI (#3323)

.github/workflows/scripts/install.sh, CHANGES/2488.removal, pulp_rpm/app/constants.py, pulp_rpm/app/models/repository.py, pulp_rpm/app/serializers/repository.py, pulp_rpm/tests/functional/api/test_download_policies.py, pulp_rpm/tests/functional/api/test_publish.py, pulp_rpm/tests/functional/api/test_pulp_to_pulp.py, template_config.yml
Sha256 has been supported since at least RHEL 6.  We obviously still have to support syncing repos with md5, sha1, and sha224 checksums as they can theoretically exist in the wild (though less and less common over time) but there's really no reason to allow publishing with any weaker checksums.  Especially since Katello has never exposed it.
=> Removed the ability to select md5, sha1, or sha224 as the checksum type

CHANGES/3351.bugfix, pulp_rpm/app/tasks/publishing.py, pulp_rpm/tests/functional/api/test_publish.py
- Finish cleanup after sqlite-metadata support removal (#3328)
- Test publishing repo with custom metadata
fixes #3351
I've assured that the test would fail without the fix.
Also, I've manually tested the publish workflow w/ RHEL7
=> Fix leftovers from sqlite-removal

CHANGES/3285.bugfix, pulp_rpm/app/constants.py, pulp_rpm/app/modulemd.py, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/unit/test_modulemd.py
This PR adds support for reading the *literal value* (non-casted value) of an *unquoted number* from a YAML file in the `parse_modular` function.
This is a customization of the YAML spec, but is the expected behavior for this context (see #3285)
- Change yaml.safe_load to yaml.load(..., Loader=yaml.BaseLoader)
- Add unit test to `parse_modular` for the specific issue
- Small refactors
=> Sanitize NSVCA fields on YAML parser

CHANGES/3285.bugfix, pulp_rpm/app/constants.py, pulp_rpm/app/modulemd.py, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/unit/test_modulemd.py
- Replace yaml.safe_load by YAML loader that prevents unquoted numbers in NSVCA fields to loose trailing/heading zeros.
- Add unit test to `parse_modular` for the specific issue
- OBSOLETE_BY_STREAM attr was named as "obsoleted_by_module_name" instead of "obsoleted_by_name_stream". Fix tests accordingly.
- Refactor parse_modular, docstrings and small type annotations
closes #3285
=> [3.24 backport] Sanitize NSVCA values on modulemd YAML files

CHANGES/3357.bugfix, pulp_rpm/app/serializers/repository.py, pulp_rpm/tests/functional/api/test_crud_repository.py
https://github.com/pulp/pulp_rpm/pull/3298 moved gpg options to a single field called "repo_config", but the deprecated "gpgcheck" and "repo_gpgcheck" were still being passed to the models, which caused a TypeError when trying to use them.
closes #3357
=> Fix server error when using gpgcheck/repo_gpgcheck

CHANGES/3312.feature, pulp_rpm/app/models/repository.py, pulp_rpm/tests/functional/api/test_pulpimport.py, pulp_rpm/tests/functional/api/test_repo_sizes.py, pulp_rpm/tests/functional/constants.py
fixes: #3312
Is there an easy way to add tests for this (know repository sizes)?
=> Add support for `repository-size` command

pulp_rpm/app/models/advisory.py
Our data model allows null sum_types, but createrepo_c types don't allow setting such values. It defaults to a value of 0, or "unknown"
[noissue]
Resolves the issue reported here: https://discourse.pulpproject.org/t/invalid-errata-metadata-sum-type-in-rhel7-repo/1007/16
=> Fix a serialization issue

CHANGES/3380.bugfix, pulp_rpm/app/advisory.py, pulp_rpm/app/modelresource.py
fixes #3380.
Co-authored-by: Grant Gainey <ggainey@redhat.com>
(cherry picked from commit 47e61c91d28614eb26e178bc2df5bc992259106d)
=> Addressed an edge-case around advisory-collection name collisions.

CHANGES/3003.feature, pulp_rpm/app/management/commands/rpm-repository-storage-analysis.py, pulp_rpm/app/models/repository.py
closes #3003
Example output:
```
$ django-admin rpm-repository-storage-analysis --include-published-metadata --include-on-demand
{
"repositories": [
{
"name": "zoo",
"href": "/pulp/api/v3/repositories/rpm/rpm/018deb68-ac31-7df7-a8f1-bcb5412d6f77/",
"disk-size": 0,
"on-demand-size": 0,
"published-metadata-size": 3452
},
{
"name": "zoo1",
"href": "/pulp/api/v3/repositories/rpm/rpm/018def79-f55c-7b83-b2ed-cf106ceedbc1/",
"disk-size": 0,
"on-demand-size": 0,
"published-metadata-size": 0
}
]
}
```
=> Added django admin command to analyze repository disk size.

docs/Makefile
This fixes some deprecation warnings from test_docs action.
[noissue]
=> Fix Makefile to correctly find plugin-by-compoenent post-core/3.44.

CHANGES/3462.bugfix, pulp_rpm/app/tasks/synchronizing.py, pulp_rpm/tests/functional/api/test_sync.py
On publications created by `mirror_complete` sync.
closes #3462
=> Fixed an issue where the value of gpgcheck wasn't set appropriately

CHANGES/3495.bugfix, pulp_rpm/app/serializers/modulemd.py, pulp_rpm/tests/functional/api/test_crud_content_unit.py
https://github.com/pulp/pulp_rpm/pull/3503
ModulemdDefaults upload wouldn't set the digest field, so it was not possible to upload more than one ModulemdDefault due to uniquness constrains.
=> [backport][3.25]Fix modulemd_defaults not having digest set

CHANGES/3526.feature, pulp_rpm/app/tasks/publishing.py
Check to confirm signature files are not 0 bytes before publishing
#3526
=> Adding simple check for empty signature files. Closes #3526

CHANGES/2909.feature, pulp_rpm/app/serializers/__init__.py, pulp_rpm/app/serializers/prune.py, pulp_rpm/app/settings.py, pulp_rpm/app/tasks/__init__.py, pulp_rpm/app/tasks/prune.py, pulp_rpm/app/urls.py, pulp_rpm/app/viewsets/__init__.py, pulp_rpm/app/viewsets/prune.py, pulp_rpm/tests/conftest.py, pulp_rpm/tests/functional/api/test_prune.py, staging_docs/user/guides/06-prune.md, staging_docs/user/guides/modify.md
=> Added /prune/ endpoint to removing "old" RPMs from a Repository.

CHANGES/3587.bugfix, pulp_rpm/app/advisory.py
This fix (https://github.com/pulp/pulp_rpm/issues/2821) should make the duplicate advisories in a repository version impossible. However, the fix is not covering all the cases. In a rare case, the incoming duplicate advisories are not merged/removed.
Please refer to code below:
https://github.com/pulp/pulp_rpm/blob/main/pulp_rpm/app/advisory.py#L114-L117 
To meet the rare case, the following 2 conditions need to be met:
There are at least 3 incoming duplicate advisories.
The first duplicate advisory is always the one to be removed by resolve_advisory_conflict()
For example:
conflict_advisories = [dup1, dup2, dup3]
[], [dup1], []= resolve_advisory_conflict(dup1, dup2)
[], [dup1], [] = resolve_advisory_conflict(dup1, dup3)
then the end result of set "content_pks_to_remove" will be equal to …
=> Fix a flaw that allowing duplicate advisories in repo version

CHANGES/3599.bugfix, pulp_rpm/app/kickstart/treeinfo.py, pulp_rpm/app/tasks/synchronizing.py
Treeinfo download will ignore results that look like HTML. Some webservers return 200 with an HTML error page rather than 404.
closes #3599
=> Made sync more tolerant of poorly configured webservers

CHANGES/3614.feature, pulp_rpm/app/viewsets/repository.py
When publishing manually (i.e. without auto_publish) the compression_type must either be passed or defaults to "None", falling back to gz.
It was kind of confusing to me that even though I had a compression_type specified in the repository, my repo metadata was compressed with gz.
This PR takes the compression_type from the repository if not passed otherwise.
fixes #3614
=> suggestion: get compression_type from repository if not specified

CHANGES/3620.bugfix, pulp_rpm/tests/functional/api/test_character_encoding.py, pulp_rpm/tests/functional/api/test_consume_content.py, pulp_rpm/tests/functional/api/test_distribution_tree.py, pulp_rpm/tests/functional/api/test_domains.py, pulp_rpm/tests/functional/api/test_pulpimport.py, pulp_rpm/tests/functional/api/test_repo_sizes.py, pulp_rpm/tests/functional/api/test_upload.py, pulp_rpm/tests/functional/conftest.py, requirements.txt
fixes #3620.
(cherry picked from commit 1c36b39e2be24f87a97821370ee850cafefddbe6)
=> Allow core/<3.70.

pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/performance/test_publish.py, pulp_rpm/tests/performance/test_pulp_to_pulp.py, pulp_rpm/tests/performance/test_sync.py
CentOS 7 is EOL, and using the vault URLs is somewhat impolite as they aren't cached.
[noissue]
=> Remove CentOS 7 tests

pulp_rpm/tests/functional/api/test_sync.py, pulp_rpm/tests/functional/constants.py, pulp_rpm/tests/performance/test_publish.py, pulp_rpm/tests/performance/test_pulp_to_pulp.py, pulp_rpm/tests/performance/test_sync.py, setup.py
CentOS 7 is EOL, and using the vault URLs is somewhat impolite as they aren't cached.
[noissue]
=> [3.19 manual backport] Remove CentOS 7 tests

CHANGES/3639.bugfix, pulp_rpm/app/fields.py, pulp_rpm/app/serializers/advisory.py, pulp_rpm/app/serializers/comps.py, pulp_rpm/app/serializers/modulemd.py, pulp_rpm/app/serializers/package.py, pulp_rpm/app/serializers/repository.py
Quicker alternative to https://github.com/pulp/pulp_rpm/pull/3653 for fixing https://github.com/pulp/pulp_rpm/issues/3639
I must add that this is not the "correct way" of fixing it, but its quick and safe (in the sense that it leaves us in a similar state we had before, where all jsonfields were recognized as [Objects](https://swagger.io/docs/specification/data-models/data-types/#object)). Its not the correct way because:
- the schema type is misleading, which is not helpful for users. E.g, its says its an Object (openapi type) when its an Array [example](https://github.com/pulp/pulp_rpm/blob/6827e0406e7c88725598973f97561a33e51e2144/pulp_rpm/app/serializers/repository.py#L544-L546)
- its not doing basic structural validation (often we know exactly what the json structure is)
- Relevant …
=> Quick fix for AnyType ruby bindings

requirements.txt
It's the cleanest (though not ideal) solution to some CI issues, which fortunately should not impact our stakeholders.
[noissue]
=> Bump minimum supported pulpcore to 3.49

pulp_rpm/tests/functional/api/test_crud_content_unit.py
We were getting failed tests on ContentUnitRemoveTestCase because the delete was being made by the requests library client without any credentials.
Then, we would get 403 (forbidden) instead of 405 (method now allowed).
This assumes the delete requires auth in the first place.
[noissue]
=> [3.18] Add basic auth to content removal test

pulp_rpm/tests/functional/api/test_sync.py
The prn field is not RPM metadata, it is pulp specific metadata, so this can be safely ignored on this kind of data comparing test.
Prn was introduced in https://github.com/pulp/pulpcore/pull/5813
This fixes this nighly failure: https://github.com/pulp/pulp_rpm/actions/runs/11137124845/job/30950082576#step:15:3890
=> Ignore 'prn' field on metadata comparision tests

pulp_rpm/tests/functional/api/test_sync.py
The prn field is not RPM metadata, it is pulp specific metadata, so this can be safely ignored.
Prn was introduced in https://github.com/pulp/pulpcore/pull/5813
=> [3.26] Ignore 'prn' field on metadata comparing tests

pulp_rpm/tests/functional/api/test_sync.py
The prn field is not RPM metadata, it is pulp specific metadata, so this can be safely ignored.
Prn was introduced in https://github.com/pulp/pulpcore/pull/5813
=> [3.27] Ignore 'prn' field on metadata comparing tests

pulp_rpm/tests/functional/api/test_sync.py
The prn field is not RPM metadata, it is pulp specific metadata, so this can be safely ignored.
Prn was introduced in https://github.com/pulp/pulpcore/pull/5813
=> [3.25] Ignore 'prn' field on metadata comparing tests

CHANGES/3756.bugfix, pulp_rpm/app/modulemd.py
=> Fixed create_modulemd() stacktrace when handling malformed modulmd.

CHANGES/3639.bugfix, pulp_rpm/app/fields.py, pulp_rpm/app/serializers/advisory.py, pulp_rpm/app/serializers/comps.py, pulp_rpm/app/serializers/modulemd.py, pulp_rpm/app/serializers/package.py, pulp_rpm/app/serializers/repository.py
The JSONField was yielding an empty type on the schema, which broke bindings generation.
This replaces drf serializers.JSONField with a custom one that is an OpenApi 'object' type.
Closes: #3639
(cherry picked from commit 2e0c2933675c0ce41d8ac5c801f8d0dbc54349d8)
=> [3.26] Fix ruby bindings AnyType error

pulp_rpm/tests/functional/api/test_crud_content_unit.py, pulp_rpm/tests/functional/api/test_sync.py
The pytest-timeout plugin was introduced to catch hanging tests, but the global timeout value is too low for the "test_requires_urlencoded_paths", which uses an amazon mirror (see [here](https://github.com/pulp/pulp_rpm/actions/runs/11655593637/job/32450523943)).
Edit: also added backport fix we had for 3.18 where we would do a request without auth, getting a 403 instead of 405 (bc957d1c)
Bakported from: 500793f6
=> [3.19] Add highter test-timeout to sync-test w/ amazon mirror

pulp_rpm/tests/functional/api/test_domains.py
The error message comes from pulpcore and contained a typo. When it was fixed [0], our test failed to match.
Ideally we would want to have Error Codes, but at this point it would be too costly to implement that.
[0] https://github.com/pulp/pulpcore/pull/5935
=> Fix regression on error-msg matching on functests

CHANGES/3777.bugfix, pulp_rpm/app/tasks/synchronizing.py, requirements.txt
=> Enable syncing without filelists present

pulp_rpm/app/modelresource.py
This avoids a rare deadlock on import-time involving ks-trees.
=> At export, enforce content-order as a last-step.

CHANGES/3853.bugfix, pulp_rpm/app/serializers/distribution.py, pulp_rpm/app/serializers/repository.py, pulp_rpm/tests/functional/api/test_copy.py, pulp_rpm/tests/functional/api/test_prn.py, pulp_rpm/tests/functional/api/test_sync.py
Notes:
* The copy API used to check if objects belonged to the current domain. For PRN references, we'll have to do it in the task context to avoid response timeouts.
=> [PULP-276] Add support for prns

CHANGES/3891.bugfix, pulp_rpm/app/downloaders.py
=> Add retry for ULN authentication

CHANGES/3927.bugfix, pulp_rpm/app/serializers/package.py, pulp_rpm/app/tasks/signing.py, pulp_rpm/app/viewsets/package.py, pulp_rpm/tests/functional/api/test_package_signing.py
Currently chunked uploads are rejected when signing rpms with the following message: "To sign a package on upload, a file must be provided."  This is because the pulp cli sends the ID for the upload rather than a file.
To fix this, I've extended the serializer and viewset to handle both a file and an upload, and have updated the signing task to properly deal with an upload.
=> Handle chunked uploads when signing rpms

pulp_rpm/app/tasks/synchronizing.py
Because of how many times this is called (once per package), this ends up having an unreasonable performance impact / memory leaks compared to its value.
We don't really want gettext in errors/warnings much anyway, it makes things less searchable.
=> Remove gettext from one small warning message

CHANGES/+publish-perf.bugfix, pulp_rpm/app/models/package.py, pulp_rpm/app/serializers/repository.py, pulp_rpm/app/tasks/publishing.py, pulp_rpm/app/tasks/synchronizing.py
.only() is a tricky beast. MasterModel __init__() was using the pulp_type field, therefore failing to include it led to deferred attribute lookups.
Dynaconf caching is currently unreliable, so we lift usages of settings values out of any important loops and assign them to constants.
(cherry picked from commit eae35737fc318757792fbe20bcc355b9878e8252)
=> [3.29] Significantly improve publish performance

CHANGES/+publish-perf.bugfix, pulp_rpm/app/models/package.py, pulp_rpm/app/serializers/repository.py, pulp_rpm/app/tasks/publishing.py, pulp_rpm/app/tasks/synchronizing.py
.only() is a tricky beast. MasterModel __init__() was using the pulp_type field, therefore failing to include it led to deferred attribute lookups.
Dynaconf caching is currently unreliable, so we lift usages of settings values out of any important loops and assign them to constants.
(cherry picked from commit 7ea323918e510cd4f1716890c7fab44a2b4cff3c)
=> [3.26] Significantly improve publish performance

CHANGES/3985.misc, pulp_rpm/app/tasks/prune.py, pulp_rpm/app/viewsets/acs.py
This calls never worked as intended and removing it shouldn't cause any problem. See:
https://github.com/pulp/pulpcore/commit/e0d999a66b751fa5a88a099207ff2971997a62fe
Closes #3985
=> Remove deprecated TaskGroup.finish calls

CHANGES/3995.bugfix, pulp_rpm/app/serializers/repository.py
The serializer definition doesn't allow None for this field, but this is not enforced. Because of that, bindings generated from that spec with strict type checking will error if it receives a None.
The field shouldn't ever be set to None in the database, but this is happening in some migration paths.
Unfortunately, I was not able to track down the root cause.
Closes #3995
=> [PULP-604] Ensure Repository.package_signing_fingerprint doesnt return None

CHANGES/3995.bugfix, pulp_rpm/app/serializers/repository.py
The serializer definition doesn't allow None for this field, but this is not enforced. Because of that, bindings generated from that spec with strict type checking will error if it receives a None.
The field shouldn't ever be set to None in the database, but this is hapenning in some migration paths.
I did not was able to track the root cause.
Closes #3995
(cherry picked from commit 40d7891e8b0e78a7a4b5e2f01613b641c12c672d)
=> [backport 3.27] Ensure Repository.package_signing_fingerprint doesnt return None

CHANGES/+update-bindings.docs, docs/dev/guides/bindings.md
This was veery outdated. Now that pulp-openapi-generator has some decent docs, we are better off pointing there.
I would even prefer to redirect directly to there, but that 'component feature' is not yet implemented in pulp-docs.
=> Update docs about client bindings

CHANGES/4125.bugfix, pulp_rpm/app/settings.py
closes: #4125
This should only matter for rpm branches that uses pulpcore `>=3.85`.
Backports:
- https://github.com/pulp/pulp_rpm/pull/4134
=> Downgrade openapi-spec version to 3.0.1

CHANGES/+update-timezone.misc, pulp_rpm/app/tasks/prune.py
Django 4 derpecates and 5 removes django.utils.timezone.utc.
The recommended action is the stdlib directly.
Found about that one [this experiment PR](https://github.com/pulp/pulp_rpm/pull/4145).
=> Replace django.utils.timezone.utc by datetime.timezone.utc
