plugins/pulp_rpm/plugins/error_codes.py
plugins/pulp_rpm/plugins/importers/yum/upload.py
plugins/test/unit/plugins/importers/yum/test_upload.py
plugins/test/unit/yum_plugin/test_yumplugin_upload.py

https://bugzilla.redhat.com/show_bug.cgi?id=1146703

1146703 - Block uploading an RPM in as an SRPM and vice versa

---

plugins/types/rpm_support.json

https://bugzilla.redhat.com/show_bug.cgi?id=1175616

Do not index the erratum title fields

---

plugins/pulp_rpm/plugins/distributors/yum/metadata/filelists.py
plugins/pulp_rpm/plugins/distributors/yum/metadata/other.py
plugins/pulp_rpm/plugins/distributors/yum/metadata/primary.py

https://bugzilla.redhat.com/show_bug.cgi?id=1176698

Fix unicode encoding of metadata

---

plugins/test/unit/plugins/distributors/yum/test_publish.py
plugins/test/unit/plugins/importers/iso/test_importer.py
plugins/test/unit/plugins/importers/iso/test_sync.py
plugins/test/unit/plugins/importers/yum/test_sync.py
plugins/test/unit/plugins/importers/yum/test_upload.py

re #86 
https://pulp.plan.io/issues/86

Fix broken unit tests due to a change in platform.

---

plugins/pulp_rpm/plugins/importers/yum/purge.py
plugins/pulp_rpm/plugins/importers/yum/repomd/presto.py
plugins/pulp_rpm/plugins/importers/yum/sync.py
plugins/test/unit/plugins/importers/yum/test_purge.py
plugins/test/unit/plugins/importers/yum/test_sync.py

https://bugzilla.redhat.com/show_bug.cgi?id=1100838

1100838 - Check for deltainfo file to read drpm data

---

plugins/pulp_rpm/plugins/importers/yum/repomd/packages.py
plugins/pulp_rpm/plugins/migrations/0016_new_yum_distributor.py
plugins/test/unit/plugins/importers/yum/test_purge.py
plugins/test/unit/plugins/migrations/test_0016_new_yum_distributor.py

This migration was missing these methods after I removed some working directory code.

Added some helper methods which used to live in pulp server common utils

---

extensions_admin/pulp_rpm/extensions/admin/rpm_admin_consumer/consumer_group_bind.py
extensions_admin/test/unit/extensions/admin/rpm_admin_consumer/test_consumer_group_bind.py

closes [619] (https://pulp.plan.io/issues/619)

619 - wrong error message when unbinding consumer group with invalid repo-id

---

extensions_admin/pulp_rpm/extensions/admin/export.py
extensions_admin/pulp_rpm/extensions/admin/iso/create_update.py
extensions_admin/pulp_rpm/extensions/admin/repo_options.py
extensions_admin/pulp_rpm/extensions/admin/upload/group.py
extensions_admin/test/unit/extensions/admin/iso/test_create_update.py

This must be merged before https://github.com/pulp/pulp/pull/1703.

Fix some import errors due to a PEP-8 change in master.

---

docs/conf.py
docs/user-guide/release-notes/2.1.x.rst
docs/user-guide/release-notes/2.2.x.rst
docs/user-guide/release-notes/2.3.x.rst
docs/user-guide/release-notes/2.4.x.rst
docs/user-guide/release-notes/2.6.x.rst

Updates extlinks and its usages to use redmine.

---

extensions_admin/pulp_rpm/extensions/admin/contents.py
extensions_admin/pulp_rpm/extensions/admin/iso/contents.py
extensions_admin/test/unit/extensions/admin/iso/test_extension_admin_iso_contents.py
plugins/pulp_rpm/plugins/importers/yum/purge.py
plugins/test/unit/plugins/distributors/yum/metadata/test_updateinfo.py
plugins/test/unit/plugins/importers/yum/parse/test_treeinfo.py
plugins/test/unit/plugins/importers/yum/test_associate.py
plugins/test/unit/plugins/importers/yum/test_purge.py
plugins/test/unit/plugins/importers/yum/test_sync.py
plugins/test/unit/plugins/migrations/test_0004_migrate.py
plugins/test/unit/plugins/migrations/test_0017_merge_sha_sha1.py

https://pulp.plan.io/issues/849
Depends on https://github.com/pulp/pulp/pull/1783

Remove owner type and and owner_id from repo_content_units

---

plugins/pulp_rpm/plugins/distributors/yum/publish.py
plugins/test/unit/plugins/distributors/yum/test_publish.py

fixes #951
https://pulp.plan.io/issues/951

Use the correct checksum when generating sqlite files

---

extensions_admin/pulp_rpm/extensions/admin/structure.py

https://pulp.plan.io/issues/662

Issue 662: Minor Fix in Documentation

---

extensions_admin/pulp_rpm/extensions/admin/repo_list.py
extensions_admin/test/unit/extensions/admin/test_repo_list.py

https://pulp.plan.io/issues/751

Issue 751: Fixed --details failure if no importers present

---

common/pulp_rpm/common/constants.py
docs/tech-reference/export-distributor.rst
docs/user-guide/release-notes/2.7.x.rst
extensions_admin/pulp_rpm/extensions/admin/export.py
extensions_admin/test/unit/extensions/admin/test_export.py
plugins/pulp_rpm/plugins/distributors/export_distributor/export_utils.py
plugins/pulp_rpm/plugins/distributors/yum/publish.py
plugins/test/unit/plugins/distributors/export_distributor/test_export_utils.py
plugins/test/unit/plugins/distributors/yum/test_publish.py

https://pulp.plan.io/issues/304

ISO export now can optionally create a PULP_MANIFEST

---

docs/user-guide/recipes.rst
extensions_admin/pulp_rpm/extensions/admin/upload/group.py
extensions_admin/test/unit/extensions/admin/upload/test_group.py

closes #930
https://pulp.plan.io/issues/930

pulp-admin not copying package groups and categories

---

plugins/pulp_rpm/plugins/importers/yum/sync.py
plugins/test/unit/plugins/importers/yum/test_sync.py

closes #175
https://pulp.plan.io/issues/175

As a user, I can specify mirrorlists for rpm repository feeds.

---

devel/pulp_rpm/devel/importer_mocks.py

closes #1022
https://pulp.plan.io/issues/1022

Remove resolve_dependecies from pulp

---

plugins/pulp_rpm/plugins/distributors/yum/configuration.py
plugins/test/unit/plugins/distributors/yum/test_configuration.py

With settings both set to false no publish will occur.
closes #717
https://pulp.plan.io/issues/717

Adding validation that http and https cannot be set both to false.

---

common/test/unit/common/server/test_version_utils_db_sort.py
docs/user-guide/troubleshooting.rst
plugins/pulp_rpm/plugins/migrations/0001_rpm_add_export_distributor.py
plugins/pulp_rpm/plugins/migrations/0002_rpm_unit_repodata.py
plugins/pulp_rpm/plugins/migrations/0004_pkg_group_category_repoid.py
plugins/pulp_rpm/plugins/migrations/0005_rpm_changelog_files.py
plugins/pulp_rpm/plugins/migrations/0007_inventoried_custom_metadata.py
plugins/pulp_rpm/plugins/migrations/0008_version_sort_index.py
plugins/pulp_rpm/plugins/migrations/0009_iso_importer_config_keys.py
plugins/pulp_rpm/plugins/migrations/0010_yum_importer_config_keys.py
plugins/pulp_rpm/plugins/migrations/0011_new_importer.py
plugins/pulp_rpm/plugins/migrations/0012_conditional_package_names_v1_v2_upgrade.py
plugins/pulp_rpm/plugins/migrations/0013_errata_from_str.py
plugins/pulp_rpm/plugins/migrations/0014_add_consumer_profile_hash.py
plugins/pulp_rpm/plugins/migrations/0015_fix_distributor_units.py
plugins/pulp_rpm/plugins/migrations/0019_add_timestamp_to_distribution.py
plugins/test/unit/plugins/migrations/test_0004_migrate.py
plugins/test/unit/plugins/migrations/test_0008_version_sort_index.py
plugins/test/unit/plugins/migrations/test_0009_iso_importer_config_keys.py
plugins/test/unit/plugins/migrations/test_0010_migrate.py
plugins/test/unit/plugins/migrations/test_0013_errata_from_str.py
plugins/test/unit/plugins/migrations/test_0015_fix_distributor_units.py
plugins/test/unit/plugins/migrations/test_0019_add_timestamp_to_distribution.py

https://pulp.plan.io/issues/1065
https://github.com/pulp/pulp/pull/2044
re #1065

remove safe=true

---

handlers/pulp_rpm/handlers/rpmtools.py
handlers/test/unit/handlers/test_rpmtools.py

https://pulp.plan.io/issues/1243

Log package changes in both system log and /var/log/yum.log.

---

plugins/pulp_rpm/plugins/importers/yum/listener.py
plugins/test/unit/plugins/importers/yum/test_listener.py

closes #1253
https://pulp.plan.io/issues/1253

Wrong SElinux label prevents rpm installation.

---

docs/user-guide/configuration.rst

closes #1252
https://pulp.plan.io/issues/1252

Removing bad links from docs.

---

plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py
plugins/test/unit/plugins/importers/yum/test_sync.py

https://pulp.plan.io/issues/1312
closes #1312

Switches copy to copytree

---

plugins/pulp_rpm/plugins/importers/yum/repomd/alternate.py
plugins/test/unit/plugins/importers/yum/repomd/test_alternate.py

Minor changes for API compatibility with changes made to content sources in the platform related to support for twisted.

API compat with content sources.

---

plugins/pulp_rpm/plugins/distributors/yum/publish.py
plugins/test/unit/plugins/distributors/yum/test_publish.py

https://pulp.plan.io/issues/1157
fixes #1157

--local-sqlite for createrepo_c for better performance on nfs

---

plugins/test/unit/plugins/importers/yum/test_purge.py
plugins/test/unit/plugins/importers/yum/test_sync.py

An additional required argument has been added in platform.

Update unit tests that instantiate RepoSyncConduit.

---

docs/user-guide/release-notes/2.8.x.rst
plugins/etc/httpd/conf.d/pulp_rpm.conf
plugins/etc/pulp/vhosts80/rpm.conf

Add Apache config to support lazy content.

---

plugins/pulp_rpm/plugins/distributors/yum/configuration.py
plugins/pulp_rpm/plugins/migrations/0001_rpm_add_export_distributor.py
plugins/pulp_rpm/plugins/migrations/0016_new_yum_distributor.py
plugins/test/unit/plugins/distributors/yum/test_configuration.py
plugins/test/unit/plugins/distributors/yum/test_publish.py
plugins/test/unit/plugins/migrations/test_0016_new_yum_distributor.py

Tests should pass after pulp master gets rebuilt tonight (12-16-2015)

Update to reflect repo_distributors conversion to mongoengine

---

plugins/pulp_rpm/plugins/db/models.py
plugins/pulp_rpm/plugins/importers/iso/importer.py
plugins/pulp_rpm/plugins/importers/iso/sync.py
plugins/pulp_rpm/plugins/importers/yum/associate.py
plugins/pulp_rpm/plugins/importers/yum/upload.py

https://pulp.plan.io/issues/1427
closes #1427
The tests associated with this code is @skip_broken. No test changes, all tests pass.

Fixes Erratum, ISO, and YumMetadataFile uploads

---

plugins/pulp_rpm/plugins/db/models.py

The model objects need to have correct super classes to ensure that _storage_path is set (and not set) as expected by platform logic.  Personally, I don't like *mixins* like this because they are classes make assumptions about how they are used as a *superclass* (which a class should never do).  But, seems they are acceptable in the python community and certainly a convenient mechanism to resolve this issue. 
I also renamed *Pacakge* -> *UnitMixin* since *Package* was semantically inappropriate to be a *superclass* for things like *Errata*,  *PackageGroup* and *Distribution*.  Especially in the RPM/YUM content of this plugin.

ref #1487 - adjust model superclasses.

---

plugins/pulp_rpm/plugins/importers/yum/sync.py

https://pulp.plan.io/issues/1540

closes #1540 - Using download_path instead of relative_path.

---

plugins/pulp_rpm/plugins/distributors/export_distributor/groupdistributor.py
plugins/test/unit/plugins/distributors/export_distributor/test_groupdistributor.py

closes #1518
https://pulp.plan.io/issues/1518

Pulp exception during repo group removal call

---

plugins/etc/httpd/conf.d/pulp_rpm.conf

https://pulp.plan.io/issues/1496
re #1496

Use /usr/share/pulp/wsgi instead of /srv/pulp.

---

plugins/pulp_rpm/plugins/distributors/yum/publish.py

Have the repo group exporter honor the repo export distributor's
relative_url value for the repo export
fixes #[1398](https://pulp.plan.io/issues/1398)
https://pulp.plan.io/issues/1398

Honor repo relative_url on group export

---

extensions_admin/pulp_rpm/extensions/admin/status.py

Instead of rendering a download bar at 100% when downloading hasn't
started yet, render a lowly spinner until there's enough information
to render a bar, while still accounting for the download task to
show 100% when the state is complete even if nothing needed to be
downloaded.
I don't fully understand the condition that the removed code was trying to deal with. Seeing the download bar start out at 100% before dropping to 0% and incrementing is the normal behavior I see with an rpm repo sync, which was bugging me enough to hack on it for a few minutes.

don't render a download bar until data is available

---

plugins/test/unit/plugins/importers/yum/repomd/test_alternate.py
plugins/test/unit/test_nectar_factory.py

Fix tests that were throwing exceptions inside nectar.

Fix broken unit tests

---

plugins/etc/httpd/conf.d/pulp_rpm.conf

This is to allow the content WSGI app a change to render the directory
index.
This is for https://pulp.plan.io/issues/1512

Rewrite requests that are simply to /pulp/repos/.

---

plugins/pulp_rpm/plugins/importers/yum/purge.py

closes #1624
https://pulp.plan.io/issues/1624

1624 - Repo sync with --retain-old-count is failing

---

plugins/pulp_rpm/plugins/importers/yum/sync.py

https://pulp.plan.io/issues/1643

RPM importer needs to handle when unit already exists.

---

plugins/pulp_rpm/plugins/importers/iso/sync.py

https://pulp.plan.io/issues/1643

ISO importer handle when unit already exists.

---

plugins/pulp_rpm/plugins/importers/iso/configuration.py
plugins/test/unit/plugins/importers/iso/test_configuration.py

closes #1660
https://pulp.plan.io/issues/1660

1660 - Cannot create/update ISO repo without feed.

---

plugins/pulp_rpm/plugins/importers/yum/upload.py

closes #1570
https://pulp.plan.io/issues/1570

Fix rpm_unit_counts, handle upload of the existing rpm unit

---

plugins/pulp_rpm/plugins/importers/yum/upload.py
plugins/test/unit/plugins/importers/yum/test_upload.py

https://pulp.plan.io/issues/1620
Fixed a few tests while I was in there.

associate uploaded erratum after upload and save

---

plugins/pulp_rpm/plugins/importers/yum/depsolve.py
plugins/test/unit/plugins/importers/yum/test_depsolve.py

minor tweaks to depsolve and depsolve tests to function better
in a mongoengine world
re #1432
https://pulp.plan.io/issues/1432

modernize yum depsolve tests

---

docs/user-guide/release-notes/2.8.x.rst

https://pulp.plan.io/issues/1431
closes #1431

Issue 1431: Release Notes for new commands in pulp-admin

---

docs/user-guide/release-notes/2.8.x.rst

This commit does a minor layout change in the release notes.

Minor layout change in docs

---

plugins/pulp_rpm/plugins/importers/iso/importer.py
plugins/pulp_rpm/plugins/importers/yum/upload.py

Adds a check for duplicate unit keys

---

plugins/pulp_rpm/plugins/distributors/yum/publish.py
plugins/test/unit/plugins/distributors/yum/test_publish.py

https://pulp.plan.io/issues/1725
fixes #1725

Fixes unit count in pulished metadata on publish of unchanged repo

---

plugins/pulp_rpm/plugins/importers/yum/sync.py
plugins/test/unit/plugins/importers/yum/test_sync.py

fixes #1749
https://pulp.plan.io/issues/1749

DRPM sync is fixed

---

plugins/pulp_rpm/plugins/importers/iso/sync.py
plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py
plugins/pulp_rpm/plugins/importers/yum/sync.py

Add the checksum and checksum type to the lazy catalog.

---

docs/tech-reference/yum-plugins.rst

There is very little developer documentation. I had no idea what a
distribution was, so I spent some time reading documentation from other
projects in order to discover what they were. I have added my current
understanding of distributions to our developer documentation. My hope
is that eventually we will have comprehensive documentation on
distributions and our other types so future developers are not in the
position I am currently in.

Add my understanding of a `distribution` to our docs.

---

plugins/pulp_rpm/plugins/importers/yum/listener.py
plugins/test/unit/plugins/importers/yum/test_listener.py

https://pulp.plan.io/issues/1789
fixes #1789

RPMs and DRPMs get removed from /var/cache/pulp immediately after import

---

plugins/pulp_rpm/plugins/importers/yum/repomd/metadata.py
plugins/test/unit/plugins/importers/yum/repomd/test_metadata.py

Check for failed download in metadata downloader
closes #1732
https://pulp.plan.io/issues/1732

Check for failed download in metadata downloader

---

plugins/pulp_rpm/plugins/importers/yum/listener.py
plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py
plugins/pulp_rpm/plugins/importers/yum/sync.py
plugins/test/unit/plugins/importers/yum/test_listener.py

closes #1778
https://pulp.plan.io/issues/1778

Handle correctly the download policy switch.

---

plugins/pulp_rpm/plugins/importers/yum/upload.py

re #1747
https://pulp.plan.io/issues/1747

Add error message to the upload report

---

plugins/pulp_rpm/plugins/importers/yum/upload.py

closes #1812
https://pulp.plan.io/issues/1812

Comps.xml upload succeeds but units are not associated to the repo.

---

docs/user-guide/release-notes/2.8.x.rst

adding release notes for 2.8.1

---

plugins/pulp_rpm/plugins/importers/yum/upload.py

https://github.com/pulp/pulp_rpm/pull/831 needs to be merged together

1813 - Handle duplicate key error in comps.xml upload.

---

plugins/pulp_rpm/plugins/db/models.py
plugins/test/unit/plugins/db/test_models.py

This is very much a short-term workaround. The model has many problems
and should be fixed in the near future.
closes #1768

The ``Distribution`` model no longer requires ``variant``

---

plugins/pulp_rpm/plugins/migrations/0028_standard_storage_path.py
plugins/test/unit/plugins/migrations/test_0028_standard_storage_path.py

standard storage path migration.

---

plugins/pulp_rpm/plugins/importers/yum/repomd/updateinfo.py

https://pulp.plan.io/issues/1828
fixes #1828

- fixed sync for reference title

---

plugins/pulp_rpm/plugins/distributors/export_distributor/distributor.py
plugins/pulp_rpm/plugins/distributors/export_distributor/groupdistributor.py
plugins/test/unit/plugins/distributors/export_distributor/test_distributor.py
plugins/test/unit/plugins/distributors/export_distributor/test_groupdistributor.py

https://pulp.plan.io/issues/1835
fixes #1835

Export distributors now fail gracefully when files have not been downloaded

---

docs/user-guide/recipes.rst
docs/user-guide/release-notes/2.9.x.rst
extensions_admin/pulp_rpm/extensions/admin/rpm_repo/pulp_cli.py
extensions_admin/pulp_rpm/extensions/admin/upload/environment.py
extensions_admin/test/unit/extensions/admin/upload/test_environment.py
plugins/pulp_rpm/plugins/importers/yum/upload.py

closes #1003
https://pulp.plan.io/issues/1003

As a user, I can use pulp-admin to upload of package_environment.

---

plugins/pulp_rpm/plugins/importers/yum/depsolve.py
plugins/test/unit/plugins/importers/yum/test_depsolve.py

https://pulp.plan.io/issues/1895
fixes #1895
The change in ``depsolv.py`` is really just reverting a previous change, and adding comments.

fixes recursive copy of rpms

---

docs/tech-reference/yum-plugins.rst
extensions_admin/pulp_rpm/extensions/admin/upload/category.py
extensions_admin/pulp_rpm/extensions/admin/upload/environment.py
extensions_admin/pulp_rpm/extensions/admin/upload/group.py
plugins/pulp_rpm/plugins/distributors/yum/metadata/package.py
plugins/test/unit/plugins/distributors/yum/metadata/test_package.py

closes #1787
https://pulp.plan.io/issues/1787

Assign a default value to display_order.

---

docs/user-guide/installation.rst
docs/user-guide/release-notes/2.1.x.rst
docs/user-guide/release-notes/2.4.x.rst
docs/user-guide/release-notes/2.5.x.rst

https://pulp.plan.io/issues/950
re #950

Fixes pulp_rpm sphinx build errors and warnings.

---

plugins/pulp_rpm/plugins/db/models.py
plugins/pulp_rpm/plugins/error_codes.py
plugins/pulp_rpm/yum_plugin/util.py
plugins/test/unit/plugins/db/test_models.py

closes #1901
https://pulp.plan.io/issues/1901

Fix error handling for errata update

---

plugins/pulp_rpm/plugins/importers/yum/associate.py

closes #1944
https://pulp.plan.io/issues/1944

YumMetadataFile copy does not save its new storage_path.

---

common/pulp_rpm/common/constants.py
plugins/pulp_rpm/plugins/distributors/yum/publish.py

closes #1938
https://pulp.plan.io/issues/1938

Fix force_full option for export distributor

---

plugins/pulp_rpm/plugins/distributors/yum/metadata/package.py
plugins/pulp_rpm/plugins/distributors/yum/metadata/updateinfo.py
plugins/test/unit/plugins/distributors/yum/metadata/test_package.py
plugins/test/unit/plugins/distributors/yum/metadata/test_updateinfo.py

closes #1716
https://pulp.plan.io/issues/1716

Generate updateinfo.xml and comps.xml using SAX instead of etree

---

docs/user-guide/release-notes/2.9.x.rst
extensions_admin/pulp_rpm/extensions/admin/repo_create_update.py
plugins/pulp_rpm/plugins/distributors/yum/configuration.py
plugins/pulp_rpm/plugins/distributors/yum/publish.py

PR for https://pulp.plan.io/issues/1976

- added packages_directory option for yum_distributor

---

plugins/pulp_rpm/plugins/migrations/0028_standard_storage_path.py
plugins/test/unit/plugins/migrations/test_0028_standard_storage_path.py

closes #1944
first this PR needs to be merged https://github.com/pulp/pulp/pull/2595

Update 28_storage_path migration for yum_metadata_file units.

---

plugins/test/unit/plugins/migrations/test_0028_standard_storage_path.py

The test mocked `YumMetadataFile.migrate()`, called it, then asserted that it was called just as the test called it.  Updated to test the `migrate()` method itself.

Improved code coverage.

---

plugins/pulp_rpm/plugins/migrations/0028_standard_storage_path.py
plugins/test/unit/plugins/migrations/test_0028_standard_storage_path.py

https://pulp.plan.io/issues/1972
The specialized distribution `Unit` overrides the `files` property.  This tells the core migration in platform about files contained within the `_storage_path` that may be linked during publishing.
Based on what the publisher does here:
- https://github.com/pulp/pulp_rpm/blob/master/plugins/pulp_rpm/plugins/distributors/yum/publish.py#L779
- https://github.com/pulp/pulp_rpm/blob/master/plugins/pulp_rpm/plugins/distributors/yum/publish.py#L805

Fix migration 0028, distribution links to files within storage path.

---

handlers/pulp_rpm/handlers/rpm.py

https://pulp.plan.io/issues/2007
closes #2007

Updates erratum handler to expect 'id' key in the unit dict

---

plugins/pulp_rpm/plugins/catalogers/yum.py
plugins/test/unit/plugins/catalogers/test_yum.py

https://pulp.plan.io/issues/2012
fixes #2012

fixes json serialization error when adding catalog entries

---

plugins/pulp_rpm/plugins/distributors/yum/publish.py
plugins/test/unit/plugins/distributors/yum/test_publish.py

closes #2035
https://pulp.plan.io/issues/2035

Apply filters to errata publish step only during incremental export

---

common/pulp_rpm/common/constants.py
docs/tech-reference/yum-plugins.rst
docs/user-guide/release-notes/2.10.x.rst
docs/user-guide/release-notes/index.rst
extensions_admin/pulp_rpm/extensions/admin/export.py
extensions_admin/pulp_rpm/extensions/admin/repo_create_update.py
extensions_admin/pulp_rpm/extensions/admin/repo_options.py
extensions_admin/test/unit/extensions/admin/test_export.py
extensions_admin/test/unit/extensions/admin/test_repo_create_update.py
plugins/pulp_rpm/plugins/distributors/yum/configuration.py
plugins/pulp_rpm/plugins/distributors/yum/metadata/updateinfo.py
plugins/pulp_rpm/plugins/distributors/yum/publish.py
plugins/test/unit/plugins/distributors/yum/metadata/test_updateinfo.py

closes #1878
https://pulp.plan.io/issues/1878

Add support for choosing the checksum type in updateinfo.xml

---

plugins/pulp_rpm/plugins/distributors/yum/publish.py

fixes #2051
https://pulp.plan.io/issues/2051

removing a log statement that was probably left in by accident

---

docs/user-guide/release-notes/2.9.x.rst

https://pulp.plan.io/issues/2048

Add #2048 known issue to 2.9.0 release notes.

---

.travis.yml
test_requirements.txt

https://pulp.plan.io/issues/2106

pin to flake8-2.6.2 for py2.6 support

---

plugins/pulp_rpm/plugins/distributors/yum/metadata/updateinfo.py
plugins/pulp_rpm/plugins/error_codes.py
plugins/test/unit/plugins/distributors/yum/metadata/test_updateinfo.py

closes #2042
https://pulp.plan.io/issues/2042

Raise exception if updateinfo_checksum_type is not available

---

docs/tech-reference/iso-rsync-distributor.rst
docs/tech-reference/rsync-distributor.rst

re #1963
https://pulp.plan.io/issues/1963
re #1759
https://pulp.plan.io/issues/1759

Removes docs about password authentication for rsync publishes

---

docs/tech-reference/iso-rsync-distributor.rst

fixes  #2120
https://pulp.plan.io/issues/2120

JSON lexer not supported on el7

---

plugins/pulp_rpm/plugins/importers/yum/utils.py
plugins/test/unit/test_util.py

closes #2093
https://pulp.plan.io/issues/2093

Fixes unicode encoding issue for non-ASCII characters in the metadata

---

docs/tech-reference/rsync-distributor.rst

Removed another json code-block that breaks on el7

---

plugins/pulp_rpm/plugins/db/models.py
plugins/test/unit/plugins/db/test_models.py

closes #2077
https://pulp.plan.io/issues/2077

Escape Django template variables in metadata during publish

---

plugins/pulp_rpm/plugins/importers/yum/listener.py

closes #2197
https://pulp.plan.io/issues/2197

Fix error report for file size verification

---

plugins/pulp_rpm/plugins/distributors/yum/metadata/updateinfo.py
plugins/test/unit/plugins/distributors/yum/metadata/test_metadata.py

closes #1926
https://pulp.plan.io/issues/1926

Fix package filtering for errata when no epoch is specified

---

plugins/pulp_rpm/plugins/importers/yum/listener.py
plugins/pulp_rpm/plugins/importers/yum/sync.py
plugins/test/unit/plugins/importers/yum/test_sync.py

closes #2190
https://pulp.plan.io/issues/2190

Associate unit after it is placed to its final location

---

docs/tech-reference/iso-rsync-distributor.rst
docs/tech-reference/rsync-distributor.rst

re #2199
https://pulp.plan.io/issues/2199

Additional documentation for rsync distributors

---

plugins/pulp_rpm/plugins/importers/yum/repomd/updateinfo.py
plugins/test/unit/plugins/importers/yum/repomd/test_updateinfo.py

closes #2227
https://pulp.plan.io/issues/2227

Import all errata pkglists and their collections

---

plugins/pulp_rpm/plugins/importers/yum/sync.py
plugins/test/unit/plugins/importers/yum/test_sync.py

https://pulp.plan.io/issues/2224
fixes #2224

Fixes a bug that broke mirrorlist sync support.

---

plugins/pulp_rpm/plugins/migrations/0034_remove_srpm_drpm_filelist_field.py
plugins/test/unit/plugins/migrations/test_0034_remove_srpm_drpm_filelist_field.py

closes #2234
https://pulp.plan.io/issues/2234

Remove no longer used filelist filed from srpm/drpm collections.

---

plugins/pulp_rpm/plugins/migrations/0035_remove_drpm_relativepath_field.py
plugins/test/unit/plugins/migrations/test_0035_remove_drpm_relativepath_field.py

closes #2236
https://pulp.plan.io/issues/2236

Remove no longer used relativepath field from drpm collection.

---

plugins/pulp_rpm/plugins/importers/yum/listener.py
plugins/pulp_rpm/plugins/importers/yum/sync.py
plugins/test/unit/plugins/importers/yum/test_sync.py

closes #2242
https://pulp.plan.io/issues/2242

Do not associate unit if it does not pass signature filter

---

plugins/pulp_rpm/plugins/db/models.py
plugins/pulp_rpm/plugins/importers/yum/associate.py

closes #2212
https://pulp.plan.io/issues/2212

Add units which did not pass signature filter to the task report.

---

extensions_admin/test/unit/extensions/admin/rpm_admin_consumer/test_rpm_admin_consumer_extension.py
playpen/errata_applicable/display_results.py
playpen/errata_applicable/populate_database.py
playpen/yum_distributor/generate_distribution_manifest.py
plugins/setup.py
pulp-dev.py
run-tests.py

closes #2293
https://pulp.plan.io/issues/2293

Pulp3: Rewrite shebangs to python3

---

plugins/pulp_rpm/plugins/importers/yum/existing.py

closes #2328
https://pulp.plan.io/issues/2328

Repository syncs show all units updated even when there are no changes.

---

plugins/pulp_rpm/plugins/importers/yum/sync.py

closes #2321
https://pulp.plan.io/issues/2321

Pulp can't handle mirrorlists with invalid entries

---

plugins/pulp_rpm/plugins/importers/yum/sync.py

closes #2363
https://pulp.plan.io/issues/2363

Show error on sync failure if the was no metadata or treeinfo found

---

plugins/pulp_rpm/plugins/importers/yum/sync.py

closes #2374
https://pulp.plan.io/issues/2374

Can't skip distribution content during sync.

---

plugins/pulp_rpm/plugins/db/models.py
plugins/pulp_rpm/plugins/importers/yum/listener.py
plugins/test/unit/plugins/db/test_models.py
plugins/test/unit/plugins/importers/yum/test_listener.py

closes #1823
https://pulp.plan.io/issues/1823

Verify RPM/SRPM/DRPM unit at its final location

---

plugins/pulp_rpm/plugins/importers/yum/repomd/primary.py

closes #2466
https://pulp.plan.io/issues/2466

Stop using deepcopy in primary.xml processing to speed up sync

---

plugins/pulp_rpm/plugins/importers/yum/upload.py
plugins/test/unit/plugins/importers/yum/test_upload.py

closes #2365
https://pulp.plan.io/issues/2365

Set the files field on rpm units during upload

---

plugins/pulp_rpm/plugins/distributors/yum/metadata/updateinfo.py

closes #2096
https://pulp.plan.io/issues/2096

Do not keep the original updateinfo file after incremental publish

---

plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py
plugins/test/data/pulp_distribution/distribution_good.xml

closes #1086
https://pulp.plan.io/issues/1086

Ignore repodata/* when syncing from pulp_distribution.xml

---

plugins/pulp_rpm/plugins/migrations/0020_nested_drpm_directory.py
plugins/test/unit/plugins/migrations/test_0020_nested_drpm_directory.py

fixes #2575
https://pulp.plan.io/issues/2575

Skip the drpm migration if no drpms

---

docs/conf.py
docs/user-guide/release-notes/2.6.x.rst
docs/user-guide/release-notes/2.8.x.rst
docs/user-guide/release-notes/2.9.x.rst

re #2585
https://pulp.plan.io/issues/2585

Modify directive name to generate docs correctly using platfrom config

---

plugins/pulp_rpm/plugins/migrations/0038_errata_pkglist_duplicates_cleanup.py
plugins/test/unit/plugins/migrations/test_0038_errata_pkglist_duplicates_cleanup.py

closes #2599
https://pulp.plan.io/issues/2599

Eliminate deprecation warning for errata cleanup migration

---

extensions_admin/pulp_rpm/extensions/admin/upload/package.py

closes #2543
https://pulp.plan.io/issues/2543

2543 - upload isn't showing whole error

---

plugins/pulp_rpm/plugins/profilers/yum.py

https://pulp.plan.io/issues/1414
I don't normally like using Logger.isEnabledFor() but wanted to prevent (nearly) identical log messages when in DEBUG.

Adjust profiler logging.

---

plugins/pulp_rpm/plugins/distributors/yum/publish.py
plugins/test/unit/plugins/distributors/yum/test_publish.py

This made errata publish very slow.
closes #2623
https://pulp.plan.io/issues/2623

Don't rebuild repo_unit_nevra for every unit

---

plugins/pulp_rpm/plugins/serializers.py

re #2620
https://pulp.plan.io/issues/2620

Implement serialize interface in RpmBase Serializer

---

plugins/pulp_rpm/plugins/importers/yum/existing.py

https://pulp.plan.io/issues/2621
Need to create catalog entries when unit already associated.

Fix catalog management with unit already associated.

---

extensions_admin/pulp_rpm/extensions/admin/upload/package.py
extensions_admin/test/unit/extensions/admin/upload/test_package.py

closes 2627
https://pulp.plan.io/issues/2627

Fix admin extension checksum-type

---

plugins/pulp_rpm/plugins/importers/yum/repomd/nectar_factory.py

https://pulp.plan.io/issues/1376
Improved error message.

Better error message for invalid URL.

---

pulp-rpm.spec

re #2679
https://pulp.plan.io/issues/2679

Don't build unsupported packages in el6 by default

---

plugins/pulp_rpm/plugins/importers/iso/importer.py

closes #2655
https://pulp.plan.io/issues/2655

Units_successful is empty for successful ISO assocaiting task.

---

plugins/pulp_rpm/plugins/distributors/iso_rsync_distributor/distributor.py
plugins/pulp_rpm/plugins/distributors/iso_rsync_distributor/publish.py

closes #2657
https://pulp.plan.io/issues/2657

Fix iso distributor option config name.

---

plugins/pulp_rpm/plugins/importers/iso/sync.py

fixes #2720
https://pulp.plan.io/issues/2720

Fix file syncs that require basic auth

---

pulp-rpm.spec

Add obsolete to spec file
refs #[2639](https://pulp.plan.io/issues/2639)

Add obsoletes to spec file

---

plugins/pulp_rpm/plugins/controllers/errata.py
plugins/pulp_rpm/plugins/db/models.py
plugins/pulp_rpm/plugins/distributors/yum/publish.py
plugins/pulp_rpm/plugins/importers/yum/sync.py
plugins/pulp_rpm/plugins/importers/yum/upload.py
plugins/pulp_rpm/plugins/migrations/0040_errata_pkglist_collection.py
plugins/pulp_rpm/plugins/serializers.py
plugins/setup.py
plugins/test/unit/plugins/controllers/test_errata.py
plugins/test/unit/plugins/db/test_models.py
plugins/test/unit/plugins/distributors/yum/test_publish.py
plugins/test/unit/plugins/importers/yum/test_upload.py
plugins/test/unit/plugins/migrations/test_0040_errata_pkglist_collection.py

closes #2681
https://pulp.plan.io/issues/2681

Store erratum pkglist in a separate collection

---

plugins/pulp_rpm/plugins/importers/yum/upload.py
plugins/pulp_rpm/plugins/importers/yum/utils.py
plugins/pulp_rpm/plugins/migrations/0041_metadata_rpm_srpm_upload_fix.py
plugins/test/unit/plugins/importers/yum/test_upload.py
plugins/test/unit/plugins/migrations/test_0041_metadata_rpm_srpm_upload_fix.py

fixes #2754
https://pulp.plan.io/issues/2754

Fix extracting metadata for rpm/srpm upload

---

docs/user-guide/release-notes/2.14.x.rst
docs/user-guide/release-notes/2.15.x.rst
docs/user-guide/release-notes/index.rst

re #2788
https://pulp.plan.io/issues/2788

Fix release notes for 2.14 and 2.15 releases

---

plugins/pulp_rpm/plugins/db/models.py
plugins/test/unit/plugins/db/test_models.py
plugins/test/unit/plugins/importers/yum/repomd/test_updateinfo.py

closes #3004
https://pulp.plan.io/issues/3004

Errata copy should copy RPMs

---

plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py

closes #3120
https://pulp.plan.io/issues/3120

Eliminate race condition during sync of a distribution unit

---

plugins/pulp_rpm/plugins/distributors/yum/configuration.py

re #2788
https://pulp.plan.io/issues/2788

Add remote_old_repodata and remove_old_repodata_threshold to optional config

---

docs/user-guide/isos.rst
docs/user-guide/release-notes/2.16.x.rst
pulp_manifest/pulp_manifest/build_manifest.py
pulp_manifest/setup.py
pulp_manifest/test/data/a.txt
pulp_manifest/test/data/b/c.txt
pulp_manifest/test/unit/test_build_manifest.py

closes #3091
https://pulp.plan.io/issues/3091

Add tool to create PULP_MANIFEST for files in a directory

---

docs/user-guide/release-notes/index.rst

This fixes a doc build error.
re #3091

Add 2.16 release notes to index

---

plugins/pulp_rpm/plugins/importers/yum/sync.py
plugins/test/unit/plugins/importers/yum/test_sync.py

closes #3306
https://pulp.plan.io/issues/3306

Ensure trailing slash is always added to the feed

---

plugins/pulp_rpm/plugins/importers/yum/sync.py

closes #3310
https://pulp.plan.io/issues/3310

No trailing slash for mirrorlist case

---

common/pulp_rpm/common/file_utils.py

https://pulp.plan.io/issues/3342

Python 2.4 compat.

---

docs/user-guide/features.rst

https://pulp.plan.io/issues/3411
closes #3411

Adds metalink clarification

---

docs/user-guide/features.rst

https://pulp.plan.io/issues/3411
re #3411

Metalink clarification

---

docs/tech-reference/yum-plugins.rst
extensions_admin/pulp_rpm/extensions/admin/repo_options.py
plugins/pulp_rpm/plugins/importers/yum/sync.py

closes #3440
https://pulp.plan.io/issues/3440

Respect SRPM skip option during sync

---

plugins/pulp_rpm/yum_plugin/util.py

fixes #3564
https://pulp.plan.io/issues/3564

Switch version comparison cast from int to float.

---

plugins/pulp_rpm/plugins/migrations/0033_checksums_and_templates.py
plugins/test/unit/plugins/migrations/test_0033_checksums_and_templates.py

closes #3654
https://pulp.plan.io/issues/3654

Set batch size to avoid cursor timeout during migration

---

plugins/pulp_rpm/plugins/serializers.py

Serializer should not add a pkglist to an erratum if it was excluded from
fields in search criteria.
Serializer handles the case when errata_id is absent in fields in search
criteria while pkglist is not.
re #3172
https://pulp.plan.io/issues/3172

Respect search criteria in the erratum serializer

---

handlers/test/unit/handlers/test_rpmtools.py

https://pulp.plan.io/issues/3714

Fix unit tests.

---

plugins/pulp_rpm/plugins/profilers/yum.py

closes #3795
https://pulp.plan.io/issues/3795

Set epoch to 0 to properly define applicable errata

---

plugins/pulp_rpm/plugins/importers/yum/associate.py

You'll run into this when [recursively copying RPM content categories](https://pulp.plan.io/issues/3787).

fix the list--set conversion in associate

---

plugins/pulp_rpm/plugins/error_codes.py

https://pulp.plan.io/issues/3090
QE thought this description would be clearer.

Updated upload exception description.

---

plugins/pulp_rpm/plugins/db/models.py
plugins/pulp_rpm/plugins/importers/yum/repomd/modules.py
plugins/pulp_rpm/plugins/serializers.py
plugins/setup.py
plugins/test/data/django-module.yaml
plugins/test/unit/plugins/db/test_models.py
plugins/test/unit/plugins/importers/yum/repomd/test_modules.py

This is the PR from @ipanova https://github.com/pulp/pulp_rpm/pull/1123 only it includes a flake8 fix also.

Add modulemd ipanova work

---

plugins/pulp_rpm/plugins/distributors/yum/configuration.py
plugins/test/unit/plugins/distributors/yum/test_configuration.py

We were exposing checksum_type via the distributor config which required automatically setting it. However, we began exposing the repo scratchpad with #1172 which contains the repo's checksum type. Setting the distributor checksum_type automatically is no longer required and causes problems for on-demand repos when the checksum type changes upstream. Therefore, stop automatically setting it.
fixes #3736
https://pulp.plan.io/issues/3736

No longer automatically set the checksum_type on distributors

---

plugins/pulp_rpm/plugins/db/models.py
plugins/pulp_rpm/plugins/importers/yum/repomd/modules.py
plugins/pulp_rpm/plugins/serializers.py
plugins/setup.py
plugins/test/data/modulemd-defaults-examples.yaml
plugins/test/unit/plugins/db/test_models.py
plugins/test/unit/plugins/importers/yum/repomd/test_modules.py

closes #3708
https://pulp.plan.io/issues/3708

Add modulemd-defaults model

---

pulp-integrity/README.md
pulp-integrity/pulp_integrity/generic.py
pulp-integrity/pulp_integrity/integrity.py
pulp-integrity/pulp_integrity/rpm.py
pulp-integrity/pulp_integrity/validator.py
pulp-integrity/setup.py

Introducing pulp-integrity

---

plugins/pulp_rpm/plugins/importers/iso/sync.py

When synced ISO fails validation, error message is not on the nectar
report. Rather than trying to put this on the nector report pass
the exception to the progress report and display it there.
closes #3845
https://pulp.plan.io/issues/3845

Display validation sync error failure message for ISO

---

plugins/pulp_rpm/plugins/importers/yum/associate.py

closes #3875
https://pulp.plan.io/issues/3875

Fix iterator modification during iteration

---

docs/user-guide/release-notes/2.16.x.rst
plugins/pulp_rpm/plugins/distributors/yum/configuration.py
plugins/test/unit/plugins/distributors/yum/test_configuration.py

2.16.4 Cherrypicks

---

plugins/pulp_rpm/plugins/importers/yum/upload.py

fixes #3873
https://pulp.plan.io/issues/3873

Support uploading modules.yaml files for rpm repos

---

plugins/pulp_rpm/plugins/db/models.py
plugins/pulp_rpm/plugins/importers/yum/associate.py

fixes #3865
https://pulp.plan.io/issues/3865

As a user i can copy modulemd-defaults

---

pulp_rpm/app/models.py
pulp_rpm/app/tasks/synchronizing.py

ref #3202
https://pulp.plan.io/issues/3202

Parsing erratum relationships and storing them on the model

---

docs/user-guide/release-notes/2.17.x.rst
handlers/pulp_rpm/handlers/repo_file.py
handlers/test/unit/handlers/test_repo_file.py

Fixed the broken unittests from https://github.com/pulp/pulp_rpm/pull/1095

Issue 3256

---

pulp_rpm/app/tasks/synchronizing.py

The ErrataRelatedModelSaver stage is instead repurposed as a subclass of
the ContentUnitSaver stage. This is currently the best way for
related objects to be saved within the same transaction.
Required PR: https://github.com/pulp/pulp/pull/3621
https://pulp.plan.io/issues/3952
closes #3952

Use ContentUnitSaver post_save hook

---

pulp_rpm/tests/functional/api/test_crd_publications.py
pulp_rpm/tests/functional/api/test_crud_content_unit.py
pulp_rpm/tests/functional/api/test_download_content.py
pulp_rpm/tests/functional/api/test_publish.py
pulp_rpm/tests/functional/api/test_sync.py
pulp_rpm/tests/functional/constants.py

Sort importers, reduce line length, and  add messaget to few assertions.

Add minor changes to the functional tests

---

plugins/pulp_rpm/plugins/migrations/0045_populate_vendor.py

closes #3924
https://pulp.plan.io/issues/3924

Add a migration for the "vendor" field

---

pulp_rpm/tests/functional/Makefile

Add a makefile to the functional tests to ease the linters execution.

Add a makefile to functional tests

---

plugins/pulp_rpm/plugins/importers/yum/importer.py

closes #3985
https://pulp.plan.io/issues/3985

Remove modular RPMs if a module is getting removed

---

pulp_rpm/app/tasks/publishing.py

Fixing bad indentation in publishing code

---

pulp_rpm/app/models.py

closes #4013
https://pulp.plan.io/issues/4013

Use digest for uniqueness constraint for UpdateRecord

---

pulp_rpm/app/models.py

closes #4014
https://pulp.plan.io/issues/4014

Store temporary data for UpdateRecord at the instance level

---

README.rst

Minor README fix

---

.travis.yml
setup.py

Adding deployment job to Travis

---

README.rst

Update README with instructions on installing createrepo_c

---

.travis/install.sh

Remove old logic to install pulp common

---

plugins/pulp_rpm/plugins/serializers.py

The Errata serializer used Errata.get_unique_pkglists() that wouldn't
provide module data due to aggregation.
This patch introduces a custom aggregation in the Errata serializer that
provides the module data.
Fixes: 4056
https://pulp.plan.io/issues/4056

Expose module info thru the Errata serializer

---

README.rst

Fix link to the docs

---

pulp_rpm/app/models.py

Fix filename gen code

---

docs/user-guide/release-notes/2.17.x.rst

(cherry picked from commit cdac2c86f85744b327081610b95d36fd431cc88d)

2.17.1 release notes cherry-pick

---

plugins/pulp_rpm/plugins/importers/yum/repomd/modules.py
plugins/pulp_rpm/plugins/migrations/0047_add_modulemd_dependencies_field.py

closes #4144
https://pulp.plan.io/issues/4144

Fix duplicit dependnecy entries.

---

.travis.yml

fixes #417
https://pulp.plan.io/issues/4147

Requiring redis-server service in travis

---

setup.py

Setting beta tag to 3.0.0b1

---

README.rst

Adding TravisCI badge

---

.travis/install.sh

ref #4192
https://pulp.plan.io/issues/4192

Install pulpcore-plugin from the new repo

---

.travis/install.sh

Fix the path to pulpcore

---

pulp_rpm/app/viewsets.py

re #3784
https://pulp.plan.io/issues/3784

Use ContentFilter instead of BaseFilterSet

---

plugins/pulp_rpm/plugins/importers/yum/repomd/metadata.py
plugins/test/unit/plugins/importers/yum/repomd/test_metadata.py

fixes #4262
https://pulp.plan.io/issues/4262

Improve the error message for missing metadata files

---

pulp_rpm/app/tasks/synchronizing.py
setup.py

Make pulp_rpm compatible with the pulpcore-plugin 0.1.0b14

---

common/pulp_rpm/common/constants.py
docs/tech-reference/yum-plugins.rst
docs/user-guide/release-notes/2.18.x.rst
extensions_admin/pulp_rpm/extensions/admin/copy_commands.py
plugins/pulp_rpm/plugins/importers/yum/associate.py
plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py

This patch allows automatically retrying the dependency solving during
recursive copy if missing dependencies were detected.

Fake missing dependencies with dummy solvables

---

.travis/install.sh
pulp_rpm/tests/functional/api/test_publish.py
pulp_rpm/tests/functional/api/test_sync.py
pulp_rpm/tests/functional/constants.py
pulp_rpm/tests/functional/utils.py

Required PR: pulp/pulp#3774
Required PR: PulpQE/pulp-smash#1154
[noissue]

API changes

---

pulp_rpm/tests/functional/api/test_crud_content_unit.py
pulp_rpm/tests/functional/api/test_crud_remotes.py

Remove unnecessary repo creation as part of the CRUD remotes tests.
[noissue]

Simplify test CRUD remotes

---

plugins/pulp_rpm/plugins/migrations/0045_populate_vendor.py

closes #4309
https://pulp.plan.io/issues/4309

Fix migration for cases in which no vendor field is provided

---

pulp_rpm/tests/functional/api/test_crud_content_unit.py

Add test to create content duplicate content units.
https://pulp.plan.io/issues/4125
ref:#4125

Add test to create duplicate content units

---

.travis/script.sh
docs/installation.rst
docs/workflows/create_sync_publish.rst
pulp_rpm/app/__init__.py
pulp_rpm/app/viewsets.py
pulp_rpm/tests/functional/constants.py

re #4279
https://pulp.plan.io/issues/4279
Required PR: https://github.com/pulp/pulp/pull/3836

Change Django app label and adjust `endpoint_name`s

---

extensions_admin/pulp_rpm/extensions/admin/copy_commands.py
plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py

closes: #4375
https://pulp.plan.io/issues/4375

Fix: Recursive copy doesn't solve rich dependencies

---

docs/workflows/upload.rst
docs/workflows/use_pulp_repo.rst
pulp_rpm/app/models.py
pulp_rpm/app/serializers.py
pulp_rpm/app/viewsets.py
pulp_rpm/tests/functional/api/test_character_encoding.py
pulp_rpm/tests/functional/api/test_crud_content_unit.py

re: #4366
https://pulp.plan.io/issues/4366

Use new specialized serializers

---

pulp_rpm/app/tasks/synchronizing.py
setup.py

Adapt to changes in the stages API

---

pulp_rpm/tests/functional/api/test_character_encoding.py

Add test to assert that HTTP excecption is raised when uploading a
non-utf8 RPM.
https://pulp.plan.io/issues/4210
closes: #4210
https://pulp.plan.io/issues/4215
ref: #4215

Verify HTTP exception when uploading nonutf8 rpm

---

pulp_rpm/tests/functional/api/test_sync.py

Modify the test layout for BasicSyncTestCase and add a dedicated class
to test related to file descriptors. Necessary change to add the sync of
DRPM, SRPM in the first one. Split tests with different concerns.
'[noissue]'

Modify test layout BasicSyncTestCase

---

pulp_rpm/tests/functional/api/test_publish.py
pulp_rpm/tests/functional/constants.py

Add test to sync/publish DRPM/SRPM content.
https://pulp.plan.io/issues/4108
ref: #4108

Add test to sync/publish DRPM/SRPM

---

pulp_rpm/app/tasks/synchronizing.py

Also use package filename as a relative_path to avoid issues
with different upstream directory structures. All packages are
published at a root of a repo now.
closes #4291
https://pulp.plan.io/issues/4291

Customize and use DeclarativeVersion provided by pulpcore-plugin

---

pulp_rpm/app/tasks/synchronizing.py

The changes to the plugin API have changed the DeclarativeVersion
interface. We now set deferred_download on the DeclarativeArtifact
directly.
https://pulp.plan.io/issues/4209
re #4209

Updating lazy for pulp_rpm

---

.travis/script.sh
docs/installation.rst

closes #4187
https://pulp.plan.io/issues/4187

Use Hyphens for Pulp3 systemd units name.

---

.travis/before_script.sh
.travis/install.sh
.travis/script.sh

re: #4444
https://pulp.plan.io/issues/4444

Switches Travis to use the new pulpcore repo

---

pulp_rpm/tests/functional/api/test_download_policies.py

Add tests to verify that a lazy synced repository can be published.
https://pulp.plan.io/issues/4418
ref: #4418

Add test to publish a lazy synced repo

---

.travis/install.sh

Install pulpcore with postgres extra packages

---

plugins/pulp_rpm/plugins/distributors/yum/publish.py

closes #4477
https://pulp.plan.io/issues/4477

Handle duplicated modular collections in errata at publish time

---

docs/user-guide/release-notes/2.19.x.rst
docs/user-guide/release-notes/index.rst

Add release notes for 2.19.0

---

.travis/script.sh
docs/installation.rst

Remove calls to pulp-manager

---

docs/workflows/create_sync_publish.rst
docs/workflows/upload.rst

closes #4511
https://pulp.plan.io/issues/4511

Update docs to use UUIDs

---

docs/release-notes/3.0.z.rst
setup.py

Bump version, add release notes, pin pulpcore-plugin
[noissue]

Prepare for beta 2

---

plugins/pulp_rpm/plugins/migrations/0043_add_modulemd_modulemd-defaults.py

Solution: handle IOError and read the uncompressed file
fixes: #4617
https://pulp.plan.io/issues/4617

Problem: migration fails for uncompressed modules files

---

pulp_rpm/tests/functional/api/test_upload.py
pulp_rpm/tests/functional/constants.py

Add test to single request upload for file already present in Pulp.
https://pulp.plan.io/issues/4536
closes #4536

Add test for duplicate files single request upload

---

.travis/script.sh
docs/Makefile
docs/installation.rst
docs/workflows/create_sync_publish.rst
docs/workflows/upload.rst
docs/workflows/use_pulp_repo.rst

Change Pulp 3 Default Ports
https://pulp.plan.io/issues/4556
docs updates too:
https://pulp.plan.io/issues/4594
Content: 8080 -> 24816
API: 8000 -> 24817
[noissue]
Required PR: https://github.com/pulp/pulpcore/pull/75

Change Pulp 3 Default Ports

---

plugins/pulp_rpm/plugins/distributors/yum/publish.py

Solution: add a check to see if this is incremental publish or not
fixes: #4692
https://pulp.plan.io/issues/4692

Problem: syncing of RedHat repos is broken

---

pulp_rpm/tests/functional/api/test_sync.py

This commit adds a test for adding the same NEVRA content with different
checksums and ensuring only the latest content is present( the old
contents are removed)
https://pulp.plan.io/issues/4297
closes #4297

Adding duplicate NEVRA with different checksum testcase

---

docs/user-guide/features.rst

closes #4644
https://pulp.plan.io/issues/4644

Add exapmles to clarify errata advanced copy cases

---

docs/user-guide/features.rst
docs/user-guide/release-notes/2.19.x.rst
plugins/pulp_rpm/plugins/importers/yum/associate.py

closes #4718
https://pulp.plan.io/issues/4718

Always copy module with its artifacts

---

docs/workflows/create_sync_publish.rst
pulp_rpm/app/models.py
pulp_rpm/app/serializers.py
pulp_rpm/app/viewsets.py
pulp_rpm/tests/functional/api/test_consume_content.py
pulp_rpm/tests/functional/api/test_download_content.py
pulp_rpm/tests/functional/api/test_publish.py
pulp_rpm/tests/functional/constants.py

add rpm distribution to match master-detail change in pulpcore
closes: #4816
https://pulp.plan.io/issues/4816

Add RPM distribution

---

pulp_rpm/tests/functional/api/test_sync.py

Add test to verify checksum constraint error when syncing a package.
https://pulp.plan.io/issues/4255
ref:#4255

Add checksum constraint test case

---

pulp_rpm/tests/functional/api/test_consume_content.py

Add test to consume content lazy synced from Pulp.
https://pulp.plan.io/issues/4496
ref:#4496

Add test to consume content lazy synced

---

docs/installation.rst
docs/release-notes/3.0.z.rst
setup.py

Bump the version, add release notes
[noissue]

Prepare for beta 3

---

setup.py

Bump pulpcore-plugin version

---

pulp_rpm/app/tasks/publishing.py

fixes #4591
https://pulp.plan.io/issues/4591

Speed up publishing using prefetching and bulk create

---

docs/workflows/create_sync_publish.rst

Fix docs for how to get a publication href

---

plugins/pulp_rpm/plugins/importers/yum/upload.py

closes #4818
https://pulp.plan.io/issues/4818

Problem: yum_repo_metadata_file cannot be updated.

---

pulp_rpm/app/tasks/synchronizing.py

Previously the user didn't have a good idea of two things:
1. How many packages and erratum are there?
2. How far into those counts are we?
This add two new progress bars that users can see the total counts on.
https://pulp.plan.io/issues/4503
closes #4503

Add total counts to pulp_rpm

---

extensions_admin/pulp_rpm/extensions/admin/contents.py

re #4868
https://pulp.plan.io/issues/4868

Rename "modulemd" in repo content options to "module" for consistency

---

.travis.yml
.travis/before_install.sh
.travis/before_script.sh
.travis/install.sh
.travis/mariadb.yml
.travis/playbook.yml
.travis/post_before_install.sh
.travis/postgres.yml
.travis/publish_client_gem.sh
.travis/publish_client_pypi.sh
.travis/publish_plugin_pypi.sh
.travis/rpm_playbook.yml
.travis/script.sh
doc_requirements.txt
pulp_rpm/app/models.py

Solution: use Travis config generator to add the installer
fixes: #4574
https://pulp.plan.io/issues/4574

Problem: ansible installer not being used on Travis

---

plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py

I'm working on the actual fix on top of these changes, but it made sense to make separate PRs to keep the actual bugfix patch relatively clear and straightforwards.
In summary, this change removes some violations of encapsulation that would become more cumbersome to deal with once I add the "considered" subset behavior to the solver.
re: #4962
https://pulp.plan.io/issues/4962

Refactor depsolving part 2 (part of bugfix)

---

docs/workflows/index.rst

the provided admin password does not work, it works with `password`

Change admin password in index.rst

---

.travis.yml
.travis/publish_client_pypi.sh
.travis/script.sh

Solution: drop the extra .dev from the version string
This change adops the latest Travis config from plugin_template repo
[noissue]

Problem: client package fails to publish to PyPI

---

pulp_rpm/app/tasks/copy.py
pulp_rpm/app/tasks/upload.py

Import only from Plugin API

---

docs/user-guide/release-notes/2.20.x.rst
docs/user-guide/release-notes/index.rst

Add 2.20.0 release notes

---

CHANGES/4117.misc
CHANGES/4503.feature
CHANGES/4567.misc
CHANGES/4574.misc
CHANGES/4591.feature
CHANGES/4716.feature
CHANGES/4835.bugfix
CHANGES/4909.bugfix
CHANGES/4916.bugfix

Add missing release notes

---

.travis/playbook.yml
.travis/rpm_playbook.yml

Use the template to update travis config

---

docs/index.rst
docs/quickstart.rst

Remove "lazy" terminology from the docs

---

plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py

Kill the decorator swamp (inline all the checks)
Simplify the serialization code
Add a bunch of comments

Refactor part 3

---

docs/conf.py
pulp_rpm/__init__.py
setup.py

Version bump to 3.0.0b4

---

pulp_rpm/__init__.py
setup.py

Version bump to 3.0.0b5.dev for the master branch after release

---

plugins/pulp_rpm/plugins/importers/yum/associate.py
plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py

I've made all these commits refer to https://pulp.plan.io/issues/5068 which is already set to modified, but so long as they are associated, it should be fine.

Refactor 4 + Fix KeyError

---

plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py

The version of mongoengine we're using is broken, and I accidentally
removed a workaround. Re-introduce the workaround and document it as
such.
re: #5131
https://pulp.plan.io/issues/5131

Re-introduce workaround for mongoengine bug

---

pulp_rpm/app/viewsets.py

Support DRF 3.10

---

plugins/pulp_rpm/yum_plugin/util.py
plugins/test/unit/plugins/db/test_models.py

closes #4979
https://pulp.plan.io/issues/4979

Teach Pulp about Amazon errata-data-format

---

.travis/rpm_playbook.yml

Solution: set the pulp_group to 'travis'
[noissue]

Problem: travis user is added to 'pulp' group

---

docs/installation.rst

closes: #5240
https://pulp.plan.io/issues/5240

Update createrepo_c installation docs

---

pulp_rpm/app/models.py

uniqness field for modulemd models
closes #4873
https://pulp.plan.io/issues/4873

Modulemd models uniqness

---

pulp_rpm/tests/functional/api/test_consume_content.py

Solution: use sudo when executing dnf
[noissue]

Problem: dnf command fails when executed on a VM

---

plugins/pulp_rpm/plugins/importers/yum/upload.py

closes #4059
https://pulp.plan.io/issues/4059

Teach upload to use RPM filename instead of upload-id

---

plugins/pulp_rpm/plugins/importers/yum/upload.py

PR#1421 introduced a problem when uploading DRPMs - this fixes it.
closes #5419
https://pulp.plan.io/issues/5419

Fix issue with uploading DRPMs

---

CHANGES/5184.feature
CHANGES/5438.misc
docs/workflows/upload.rst
pulp_rpm/app/serializers.py
pulp_rpm/app/tasks/synchronizing.py
pulp_rpm/app/viewsets.py
pulp_rpm/tests/functional/api/test_character_encoding.py
pulp_rpm/tests/functional/api/test_consume_content.py
pulp_rpm/tests/functional/api/test_crud_content_unit.py

Updating relative_path and artifact fields caused by change in SingleArtifactContentSerializer
[noissue]
**Note that I combined other PRs here to get Travis green. I am happy to remove them though.**

Updating relative_path field

---

CHANGES/5184.feature
pulp_rpm/app/tasks/synchronizing.py

ref #5184
https://pulp.plan.io/issues/5184
Required PR: https://github.com/pulp/pulpcore-plugin/pull/123
Required PR: https://github.com/pulp/pulpcore/pull/289

adding code on progress bar

---

CHANGES/5206.feature
pulp_rpm/app/tasks/publishing.py
pulp_rpm/app/tasks/utils.py

closes #5206
https://pulp.plan.io/issues/5206
Required PR: https://github.com/pulp/pulp_rpm/pull/1418
Required PR: https://github.com/pulp/pulp_rpm/pull/1427

Publishing kickstarts

---

CHANGES.rst
CHANGES/4681.misc
CHANGES/4987.bugfix
CHANGES/5184.feature
CHANGES/5201.misc
CHANGES/5202.misc
CHANGES/5206.feature
CHANGES/5285.bugfix
CHANGES/5331.misc
CHANGES/5430.misc
CHANGES/5431.misc
CHANGES/5432.feature
CHANGES/5438.misc
pulp_rpm/__init__.py
setup.py

3.0.0b5 release

---

CHANGES.rst
pulp_rpm/__init__.py
setup.py

Bumping to 3.0.0b6.dev

---

CHANGES/5421.misc
pulp_rpm/app/tasks/synchronizing.py

closes #5421
Required PR: https://github.com/pulp/pulpcore/pull/300
https://pulp.plan.io/issues/5421

marking sub repository

---

CHANGES/5469.misc
pulp_rpm/app/tasks/synchronizing.py

closes #5469
https://pulp.plan.io/issues/5469
Required PR: https://github.com/pulp/pulpcore/pull/293
Required PR: https://github.com/pulp/pulpcore-plugin/pull/127
Required PR: https://github.com/pulp/pulp_file/pull/277

Replace ProgressBar with ProgressReport

---

CHANGES/5330.bugfix
pulp_rpm/app/urls.py

closes #5330
https://pulp.plan.io/issues/5330

Add url prefix to plugin custom urls.

---

CHANGES/5493.feature
CHANGES/5493.misc
pulp_rpm/app/tasks/publishing.py

able to publish modularity content
closes #5493
https://pulp.plan.io/issues/5493

Publish modularity

---

docs/user-guide/release-notes/2.21.x.rst
docs/user-guide/release-notes/index.rst

Add 2.21 release notes

---

CHANGES/5408.misc
pulp_rpm/tests/functional/api/test_sync.py
pulp_rpm/tests/functional/constants.py

Add test to sync modular RPM content.
https://pulp.plan.io/issues/5408
ref:#5408

Add test sync modular RPM

---

CHANGES/5304.misc
pulp_rpm/app/tasks/publishing.py
pulp_rpm/tests/functional/api/test_publish.py

Required PR: https://github.com/pulp/pulpcore/pull/303/
re: #5304
https://pulp.plan.io/issues/5304

Switch to using PublishedMetada.create_from_file()

---

CHANGES/5453.feature
CHANGES/5453.removal
pulp_rpm/app/serializers.py
pulp_rpm/app/urls.py
pulp_rpm/app/viewsets.py
pulp_rpm/tests/functional/api/test_character_encoding.py
pulp_rpm/tests/functional/api/test_crud_content_unit.py
pulp_rpm/tests/functional/api/test_upload.py
pulp_rpm/tests/functional/constants.py

Required PR: https://github.com/pulp/pulpcore-plugin/pull/122
closes #5453
https://pulp.plan.io/issues/5453

add new upload serializer

---

CHANGES.rst
CHANGES/5172.misc
CHANGES/5304.misc
CHANGES/5330.bugfix
CHANGES/5408.misc
CHANGES/5421.misc
CHANGES/5453.feature
CHANGES/5453.removal
CHANGES/5469.misc
CHANGES/5493.feature
CHANGES/5493.misc
pulp_rpm/__init__.py
setup.py

3.0.0b6 release

---

pulp_rpm/__init__.py
setup.py

Version bump to the next .dev

---

CHANGES/5535.removal
pulp_rpm/app/viewsets.py

re #5535
https://pulp.plan.io/issues/5535
Required PR: https://github.com/pulp/pulpcore/pull/322
Required PR: https://github.com/pulp/pulpcore-plugin/pull/140

Fix endpoint names for distribution trees and custom metadata viewsets.

---

.travis.yml
.travis/before_install.sh
.travis/before_script.sh
.travis/install.sh
.travis/script.sh
template_config.yml

Mainly wanted to change how the unit tests are run.
[noissue]

Update travis config

---

CHANGES/5516.removal
pulp_rpm/app/serializers.py

ref #5516
https://pulp.plan.io/issues/5516

Removing repository from Addon/Variant serializers

---

CHANGES/5548.removal
pulp_rpm/tests/functional/api/test_character_encoding.py
pulp_rpm/tests/functional/api/test_download_policies.py
pulp_rpm/tests/functional/api/test_publish.py
pulp_rpm/tests/functional/api/test_sync.py
pulp_rpm/tests/functional/api/test_upload.py

_versions_href to pulp_versions_href
_latest_version_href to pulp_latest_version_href
ref #5548
https://pulp.plan.io/issues/5548
Required PR: https://github.com/pulp/pulpcore/pull/329
Required PR: https://github.com/PulpQE/pulp-smash/pull/1221

Renaming RepositoryVersion fields

---

.travis.yml

Skip steps which are not needed for deploying to PyPI

---

pulp_rpm/app/tasks/synchronizing.py

Fixing sync for multi-variants

---

.travis.yml
.travis/script.sh
CHANGES/5506.misc
pulp_rpm/tests/functional/constants.py
pulp_rpm/tests/performance/test_sync.py
template_config.yml

related to: https://github.com/pulp/plugin_template/pull/113
closes #5506
https://pulp.plan.io/issues/5506

Adding performance tests

---

pulp_rpm/tests/performance/test_sync.py

```
(pulp) [vagrant@pulp3-source-fedora30 pulp_rpm]$ pytest -vv -r sx --color=yes --pyargs --capture=no --durations=0 pulp_rpm.tests.performance || show_logs_and_return_non_zero
===================================== test session starts =====================================
platform linux -- Python 3.7.3, pytest-5.2.1, py-1.8.0, pluggy-0.13.0 -- /usr/local/lib/pulp/bin/python3
cachedir: .pytest_cache
rootdir: /home/vagrant/devel/pulp_rpm
collected 5 items                                                                             
pulp_rpm/tests/performance/test_sync.py::SyncTestCase::test_centos7_on_demand 
->     Sync => Waiting time (s): 0.084152 | Service time (s): 118.819651
->  Re-sync => Waiting time (s): 0.08805 | Service time (s): 79.639323
PASSED
```

Adding re-sync on performance tests

---

.travis.yml
.travis/before_install.sh
.travis/install.sh
CHANGES/5580.misc
README.md
pulp_rpm/app/settings.py

Required PR: https://github.com/pulp/pulpcore/pull/347
re: #5580
https://pulp.plan.io/issues/5580

Depend on pulpcore directly instead of pulpcore-plugin

---

CHANGES/5630.bugfix
pulp_rpm/app/tasks/publishing.py
pulp_rpm/tests/functional/constants.py
pulp_rpm/tests/performance/test_publish.py

Publication was raising errors for sub repos, because it couldn't find
the file due to wrong path
https://pulp.plan.io/issues/5630
closes #5630

Fixing publication for sub repos

---

CHANGES/5650.bugfix
pulp_rpm/app/fields.py
pulp_rpm/app/serializers.py

https://pulp.plan.io/issues/5650
closes #5650

Fix ruby bindings for UpdateRecord

---

CHANGES/5671.bugfix
pulp_rpm/app/models.py

https://pulp.plan.io/issues/5671
closes #5671

Stopping to save JSONFields as String

---

CHANGES/5461.misc
pulp_rpm/app/tasks/synchronizing.py

https://pulp.plan.io/issues/5461
closes #5461

Improve performance at content relation time

---

.travis.yml
.travis/script.sh
template_config.yml

Using changes from https://github.com/pulp/plugin_template/pull/139
[noissue]

Split up performance tests in separate stages

---

CHANGES/5672.misc
pulp_rpm/app/serializers.py

https://pulp.plan.io/issues/5672
closes #5672

Not check for empty strings in UpdateRecord

---

pulp_rpm/app/tasks/publishing.py
pulp_rpm/app/tasks/utils.py

Fix publication broken tests

---

CHANGES/4295.misc
pulp_rpm/app/models.py

re #4295
https://pulp.plan.io/issues/4295

Identify previous repo version to use in finalization steps

---

CHANGES/5526.feature
pulp_rpm/app/models.py
pulp_rpm/app/modulemd.py

fixes #5526
https://pulp.plan.io/issues/5526

Add/remove RPMs when modulemd changes

---

CHANGES/5729.bugfix
pulp_rpm/app/kickstart/treeinfo.py
pulp_rpm/app/tasks/publishing.py
pulp_rpm/app/tasks/synchronizing.py

https://pulp.plan.io/issues/5729
closes #5729

Refactor treeinfo handling and fix publication

---

CHANGES/5495.feature
CHANGES/5495.misc
pulp_rpm/app/comps.py
pulp_rpm/app/models.py
pulp_rpm/app/tasks/publishing.py

Adds publish for comps
closes #5495
https://pulp.plan.io/issues/5495

Add publish support for content types from comps.xml

---

pulp_rpm/__init__.py
setup.py

3.0.0rc1 release

---

pulp_rpm/__init__.py
setup.py

Version bump to 3.1.0b1.dev

---

CHANGES/5732.bugfix
pulp_rpm/app/kickstart/treeinfo.py
pulp_rpm/app/tasks/synchronizing.py

https://pulp.plan.io/issues/5732
closes #5732

Handling syncing when there is no treeinfo file

---

CHANGES/5761.bugfix
pulp_rpm/app/tasks/synchronizing.py

https://pulp.plan.io/issues/5761
closes #5761

Splitting content between repo and sub-repo

---

pulp_rpm/tests/performance/test_sync.py

Fix sync performance tests

---

CHANGES/5709.bugfix
pulp_rpm/app/kickstart/treeinfo.py

https://pulp.plan.io/issues/5709
closes #5709

Descriptive error for invalid treeinfo files

---

CHANGES/5757.misc
pulp_rpm/tests/functional/api/test_character_encoding.py
pulp_rpm/tests/functional/api/test_download_policies.py
pulp_rpm/tests/functional/api/test_sync.py
pulp_rpm/tests/performance/test_sync.py

ref #5757
Required PR: https://github.com/pulp/pulpcore/pull/399

Fix tests for initial repo version

---

pulp_rpm/__init__.py
setup.py

Version bump to 3.0.0rc2.dev

---

CHANGES/5747.doc
docs/index.rst
docs/quickstart.rst
docs/workflows/upload.rst

Remove one-shot upload references and info
closes #5747
https://pulp.plan.io/issues/5747

Remove one-shot from docs

---

CHANGES/5752.doc
docs/index.rst

Add modularity and comps support to features list.
Add core-provided browseable distributions to features list.
fixes #5752
https://pulp.plan.io/issues/5752

Bring list of features up to date

---

.travis/before_install.sh
.travis/check_commit.sh
.travis/install.sh
.travis/publish_client_pypi.sh
.travis/publish_plugin_pypi.sh
.travis/script.sh
.travis/validate_commit_message.py
template_config.yml

Also update config to use 3.0 branch for pulpcore.
[noissue]

Travis update for 3.0 branch

---

.travis/before_install.sh
.travis/check_commit.sh
.travis/install.sh
.travis/publish_client_pypi.sh
.travis/publish_plugin_pypi.sh
.travis/script.sh
.travis/validate_commit_message.py
template_config.yml

Travis config update

---

CHANGES/5701.misc
pulp_rpm/app/models/repository.py

re: #5701
https://pulp.plan.io/issues/5701

Add CONTENT_TYPES to repo definition

---

CHANGES/5758.doc
docs/workflows/index.rst
docs/workflows/manage.rst
docs/workflows/upload.rst

closes #5758
https://pulp.plan.io/issues/5758

Rearrange workflows section to add menu items for different content

---

CHANGES/5741.bugfix
pulp_rpm/app/comps.py
pulp_rpm/app/models/comps.py
pulp_rpm/app/tasks/publishing.py

Output lacked desc_by_lang, name_by_lang, and default, now corrected.
closes #5741
https://pulp.plan.io/issues/5741

Fix comps group attrs missing at publish time

---

CHANGES/5750.doc
docs/_scripts/add_remove.sh
docs/_scripts/advisory.sh
docs/_scripts/artifact.sh
docs/_scripts/base.sh
docs/_scripts/copy.sh
docs/_scripts/distribution.sh
docs/_scripts/docs_check_sync.sh
docs/_scripts/docs_check_upload.sh
docs/_scripts/download.sh
docs/_scripts/package.sh
docs/_scripts/publication.sh
docs/_scripts/remote.sh
docs/_scripts/repo.sh
docs/_scripts/sync.sh
docs/workflows/copy.rst
docs/workflows/create_sync_publish.rst
docs/workflows/index.rst
docs/workflows/scripting.rst
docs/workflows/upload.rst
docs/workflows/use_pulp_repo.rst

Refactor commands to small scripts to better readability and to reproduce them easily.
closes #5750
https://pulp.plan.io/issues/5750

[Docs] Commands to scripts

---

CHANGES/5861.bugfix
pulp_rpm/app/tasks/publishing.py
pulp_rpm/app/tasks/synchronizing.py

https://pulp.plan.io/issues/5861
closes #5861

Assuring uniqueness on publishing

---

pulp_rpm/app/tasks/synchronizing.py

And other small improvements
[noissue]

Fix miscounting progress bars

---

CHANGES/5856.bugfix
pulp_rpm/app/serializers.py

closes #5856
https://pulp.plan.io/issues/5856

Allow empty values for some comps content fields

---

CHANGES/5759.doc
docs/workflows/manage.rst

closes #5959
https://pulp.plan.io/issues/5759

Add content type descriptions and their specific.

---

docs/workflows/manage.rst

re #5759
https://pulp.plan.io/issues/5759

Add descritpion for distribution trees and advisories

---

pulp_rpm/app/serializers.py

Fix a check for mandatory fields at upload time.

---

.travis/before_install.sh
setup.py
template_config.yml

This reverts commit 37b3ccfefb7b028accd4d099a0621714e359b72a.

Revert temporary config

---

pulp_rpm/__init__.py
setup.py

Version bump to 3.0.1.dev

---

.travis/before_install.sh
CHANGES/5867.misc
functest_requirements.txt
pulp_rpm/tests/functional/api/test_crud_content_unit.py
pulp_rpm/tests/functional/api/test_crud_remotes.py
pulp_rpm/tests/functional/api/test_download_content.py
pulp_rpm/tests/functional/api/test_publish.py

Update refs to pulpqe repos

---

pulp_rpm/app/models/repository.py

Fix call to Task.current

---

.travis.yml
.travis/before_install.sh
.travis/cherrypick.py
.travis/cherrypick.sh
.travis/script.sh
template_config.yml

Enable cherry pick automation and update travis config

---

plugins/pulp_rpm/plugins/db/models.py
plugins/pulp_rpm/plugins/importers/yum/upload.py
plugins/test/unit/plugins/importers/yum/test_upload.py

When we update an erratum, this affects not only the repo
for which the update was requested, but also every other repo
containing the same erratum.
Therefore, rather than letting the controller only set
last_unit_added on the specific repo used for the import,
we should ensure the field is set for all repos containing
the unit - otherwise, publish of those repos may wrongly be
skipped.
closes #5951
https://pulp.plan.io/issues/5951

Ensure updating erratum sets last_unit_added on *all* repos

---

CHANGES/6009.feature
pulp_rpm/app/tasks/copy.py
pulp_rpm/tests/functional/api/test_copy.py

Allow content to be filtered during copy

---

CHANGES/6034.feature

Left by accident after the last release.
[noissue]

Remove old changelog file

---

.travis/before_script.sh
CHANGES/6030.misc
pulp_rpm/tests/functional/constants.py
template_config.yml

Required PR: https://github.com/pulp/pulp-fixtures/pull/137
https://pulp.plan.io/issues/6030
closes #6030

Update travis to use local fixtures

---

pulp_rpm/app/schema/__init__.py
pulp_rpm/app/schema/copy_criteria.json
pulp_rpm/app/serializers.py
pulp_rpm/app/viewsets.py
pulp_rpm/tests/functional/api/test_copy.py
pulp_rpm/tests/functional/utils.py

refs #6009
https://pulp.plan.io/issues/6009

Validate criteria for the copy API

---

CHANGES/6152.bugfix
pulp_rpm/app/models/repository.py
pulp_rpm/tests/functional/api/test_crud_content_unit.py
pulp_rpm/tests/functional/constants.py

https://pulp.plan.io/issues/6152
closes #6152

Raise error when content has overlapping path

---

CHANGES/5904.bugfix
docs/_scripts/download.sh
pulp_rpm/app/serializers.py
pulp_rpm/app/shared_utils.py

https://pulp.plan.io/issues/5904
closes #5904

Dealing with Packages from S3

---

docs/user-guide/release-notes/2.21.x.rst

Add release notes for 2.21.1 release.

---

CHANGES/6147.misc
CHANGES/6147.removal

Update changelog message and make it misc since it doesn't impact users

---

setup.py

Bump pulpcore

---

pulp_rpm/__init__.py
setup.py

Version bump to 3.3.0b1.dev

---

.travis/script.sh

https://travis-ci.com/fabricio-aguiar/pulp_rpm/jobs/296045655#L2827

Introducing TRAVIS_WAIT on performance tests

---

CHANGES/6229.bugfix
pulp_rpm/app/advisory.py
pulp_rpm/app/models/repository.py
pulp_rpm/app/modulemd.py

closes #6229
https://pulp.plan.io/issues/6229

Properly compare modular content between the versions.

---

pyproject.toml

see: https://github.com/pypa/setuptools/issues/1694#issuecomment-466010982
[noissue]

Handle setuptools error

---

.travis.yml
.travis/before_install.sh
.travis/before_script.sh
.travis/cherrypick.py
.travis/install.sh
.travis/publish_client_gem.sh
.travis/publish_client_pypi.sh
.travis/script.sh
CHANGES/6155.misc
template_config.yml

https://pulp.plan.io/issues/6155
ref #6455

Running tests on minio

---

template_config.yml

Bump latest stable_branch in template config

---

.travis/script.sh

Bump travis wait time for performance tests

---

docs/tech-preview.rst

Add copy API to the tech preview list

---

docs/workflows/metadata_signing.rst

Adds link to docs for creating a signing service

---

pulp_rpm/app/tasks/publishing.py

Minor publish performance improvment

---

pulp_rpm/app/tasks/publishing.py

https://github.com/pulp/pulp_rpm/pull/1624/files#diff-31bb7266e48ec01d56b9d6c903badad0R167
[noissue]

Revert change to public plugin API

---

pulp_rpm/__init__.py
setup.py

Version bump to 3.3.0b2.dev

---

plugins/pulp_rpm/plugins/profilers/yum.py

The patch from Pavel Moravec.
re #6334
https://pulp.plan.io/issues/6334

Query only required set of fields for calculating applicability.

---

plugins/pulp_rpm/plugins/profilers/yum.py

Improve the performance of calculating applicable errata for the consumer.

Improve the performance of calculating applicable errata

---

CHANGES/6339.misc
pulp_rpm/tests/functional/utils.py

https://pulp.plan.io/issues/6339
closes #6339

Get bindings host from pulp-smash

---

CHANGES/6303.bugfix
pulp_rpm/app/modulemd.py

https://pulp.plan.io/issues/6303
closes #6303

Properly compare modular content between versions

---

pulp_rpm/app/serializers.py

Deleting commented code from CopySerializer

---

CHANGES/6367.bugfix
pulp_rpm/app/migrations/0005_optimize_sync.py
pulp_rpm/app/models/repository.py
pulp_rpm/app/shared_utils.py
pulp_rpm/app/tasks/synchronizing.py

https://pulp.plan.io/issues/6367
closes #6367

Applied optimization to sub-repos

---

CHANGES/6395.doc
docs/bindings.rst

https://pulp.plan.io/issues/6221
ref #6221

Bindings installation on dev environment

---

setup.py

Updating productmd requirement

---

CHANGES/6441.bugfix
pulp_rpm/app/models/advisory.py

closes #6441
https://pulp.plan.io/issues/6441

Add missing advisory fields to the publication.

---

CHANGES/5455.misc
pulp_rpm/app/tasks/synchronizing.py

closes: #5455
https://pulp.plan.io/issues/5455

Adds RpmInterrelateContent stage

---

docs/bindings.rst
docs/installation.rst
docs/quickstart.rst

[noissue]
re: #6406
Rename ansible-pulp to pulp_installer
https://pulp.plan.io/issues/6406

Rename ansible-pulp to pulp_installer

---

CHANGES/6440.bugfix
pulp_rpm/app/models/advisory.py

closes #6440
https://pulp.plan.io/issues/6440

Add module info to an advisory for a publication

---

CHANGES/5207.misc
pulp_rpm/tests/functional/api/test_copy.py
pulp_rpm/tests/functional/constants.py

https://pulp.plan.io/issues/5207
closes #5207

Added functional tests for copying kickstarts

---

setup.py

re #6440
https://pulp.plan.io/issues/6440

Bump createrepo_c verison requirement

---

CHANGES/6312.misc
docs/_scripts/artifact.sh
docs/_scripts/distribution.sh
docs/_scripts/docs_check_sync.sh
docs/_scripts/docs_check_upload.sh
docs/_scripts/download.sh
docs/_scripts/repo.sh
docs/workflows/scripting.rst

Docs check scripts can be run together.
closes #6312
https://pulp.plan.io/issues/6312

Independent docs script

---

plugins/pulp_rpm/plugins/importers/yum/listener.py

closes #6453
https://pulp.plan.io/issues/6453

Add sha512 support for verification upon package download

---

CHANGES/6530.bugfix
pulp_rpm/app/tasks/publishing.py

closes #6530
https://pulp.plan.io/issues/6530

Do not publish repodata that has artifacts in the root directory.

---

pulp_rpm/tests/functional/api/test_consume_content.py

Fixes tests that relied on base_path not ending with '/'

---

pulp_rpm/tests/functional/api/test_consume_content.py

Fixes one more test that relied on base_path ending in '/'

---

CHANGES/6560.misc
pulp_rpm/app/models/repository.py

closes #6560
https://pulp.plan.io/issues/6560

Added validate_repo_version method during finalize_new_version.

---

CHANGES.rst
CHANGES/6560.misc

Fix changelog

---

CHANGES/6514.misc
pulp_rpm/app/modelresource.py

ref #6514
Required PR: https://github.com/pulp/pulpcore/pull/670

Rehome QueryModelResource to pulpcore.plugin.importexport

---

plugins/pulp_rpm/plugins/importers/yum/sync.py

closes #6355
https://pulp.plan.io/issues/6355

Update other repos' last_unit_added if an erratum is updated during sync

---

plugins/pulp_rpm/plugins/importers/yum/modularity.py

closes #6354
https://pulp.plan.io/issues/6354

Use `save` instead of `update` so _last_updated is set properly

---

CHANGES/6665.misc
pulp_rpm/app/models/advisory.py

closes #6665
https://pulp.plan.io/issues/6665

Make model definition match the db state

---

template_config.yml

Set stable branch to 3.3 for correct cherry-picking

---

CHANGES.rst
CHANGES/6519.bugfix
CHANGES/6662.bugfix
CHANGES/6665.misc

[noissue]
(cherry picked from commit 90806d0304ff4b4a9e2e37a7548ed922887b1fe3)

Changelog for 3.3.1

---

.travis/cherrypick.py
pulp_rpm/app/models/package.py
pulp_rpm/tests/functional/api/test_consume_content.py
pulp_rpm/tests/functional/content_handler/test_config_repo.py

Fix flake8 lints

---

CHANGES/6693.bugfix
pulp_rpm/app/tasks/copy.py
pulp_rpm/app/viewsets.py

closes: #6693
https://pulp.plan.io/issues/6693

Fix an edge case with 'dest_base_version'

---

CHANGES/6759.doc
docs/installation.rst

https://pulp.plan.io/issues/6759
closes #6759

Updated the required roles names

---

CHANGES/6536.misc
coverage.md
pulp_rpm/tests/functional/api/test_publish.py
pulp_rpm/tests/functional/constants.py

Test Pulp3 publish directory layout with repositories contain modularity
and kickstarters.
closes: #6536
https://pulp.plan.io/issues/6536

Test publish directory layout

---

CHANGES/6777.misc
coverage.md
pulp_rpm/tests/functional/api/test_sync.py
pulp_rpm/tests/functional/constants.py

Added test for additivie mode sync.
closes: #6777
https://pulp.plan.io/issues/6777

Test sync additive mode

---

CHANGES/6786.misc
coverage.md
pulp_rpm/tests/functional/api/test_sync.py

Test mirror mode sync.
closes: #6786
https://pulp.plan.io/issues/6786

Test sync mirror mode

---

CHANGES/6801.misc
pulp_rpm/app/serializers.py

https://pulp.plan.io/issues/6801
closes #6801

Added view_name on ModulemdSerializer

---

CHANGES/6789.misc
coverage.md
pulp_rpm/tests/functional/api/test_copy.py

Test case for sctrict copy of RPM packages with its dependencies.
closes: #6789
https://pulp.plan.io/issues/6789

Test - rpm copy package

---

.travis/install.sh

Until https://github.com/minio/minio/issues/9736 is released
[noissue]

Temporary minio fix

---

.bumpversion.cfg
.travis/release.py
CHANGES/6839.misc
CHANGES/6841.misc
pulp_rpm/__init__.py
requirements.txt
setup.py

- Move requirements out of setup.py
- Introduce release script

Release script

---

.travis/pre_before_install.sh

Skip coverage check if no code changes

---

CHANGES/6892.bugfix
MANIFEST.in

https://pulp.plan.io/issues/6892
closes #6892

Including requirements.txt on MANIFEST.in

---

.bumpversion.cfg
pulp_rpm/__init__.py
setup.py

Bumping the version to 3.4.1.dev

---

.bumpversion.cfg
CHANGES.rst
CHANGES/6892.bugfix
pulp_rpm/__init__.py
setup.py

Redmine query of issues to close:
https://pulp.plan.io/issues?set_filter=1&status_id=*&issue_id=6892
Release commit == bf6bd84

Release 3.4.1

---

CHANGES.rst
CHANGES/6892.bugfix

[noissue]
(cherry picked from commit d0de711d4058fb545172b9f91e3ad24d906b8e36)

Building changelog for 3.4.1

---

CHANGES/6974.bugfix
pulp_rpm/app/viewsets.py

Hide publications that aren't complete

---

pulp_rpm/app/tasks/synchronizing.py

In this commit, there were extracted multiple classes and methods from the method run() in order to improve the readability. The introduced classes RepositoryMetadataParser, ModulesMetadataParser, and PackagesComponentsParser are used for parsing the associated content within a repository. These classes alter data stored in the data class FirstStageData step by step, while parsing the content. In the end, this data class contains all necessary data required for downloading and processing the actual content.
[noissue]

Refactor the method run()

---

pulp_rpm/app/advisory.py

Add clarification in the doc string about how advisories are processed.

---

CODEOWNERS

Remove QE as codeowner

---

plugins/pulp_rpm/plugins/distributors/yum/distributor.py

closes #2826
https://pulp.plan.io/issues/2826
(cherry picked from commit f54315cd41cbc6944d56d07136db38b89ae5061f)

Ensure repo deletion doesn't fail due to the absence of listing files

---

docs/user-guide/release-notes/2.21.x.rst

Add release notes for 2.21.2 and 2.21.3

---

plugins/pulp_rpm/plugins/importers/yum/purge.py
plugins/test/unit/plugins/importers/yum/test_purge.py

closes #7047
https://pulp.plan.io/issues/7047

Remove missing should also remove missing srpms

---

CHANGES/7103.bugfix
pulp_rpm/app/viewsets.py

Remove non-model-fields from Meta.fields of filters

---

CHANGES/6316.feature
coverage.md
pulp_rpm/app/tasks/copy.py
pulp_rpm/tests/functional/api/test_copy.py
pulp_rpm/tests/functional/constants.py

Depsolving for PackageGroups, PackageEnvironment and PackageCategory.
closes: #6316
https://pulp.plan.io/issues/6316

Copy for comps types

---

CHANGES.rst
CHANGES/6568.bugfix
CHANGES/6656.doc
CHANGES/6778.misc
CHANGES/6974.bugfix

[noissue]
(cherry picked from commit 70d913c348c16dc547b1ec69a109fc2e4da8efa4)

Building changelog for 3.4.2

---

pulp_rpm/tests/performance/test_sync.py

unescape spaces in CDN test
[noissue]

Unescape spaces in CDN test

---

.bumpversion.cfg
pulp_rpm/__init__.py
setup.py

Bump to 3.6.0.dev

---

template_config.yml

Set the stable branch to 3.5 for cherry-picks

---

CHANGES/6937.misc
pulp_rpm/app/modelresource.py

ref #6807
Required PR: https://github.com/pulp/pulpcore/pull/745

Rebase all Resources to subclass from BaseContentResource

---

pulp_rpm/tests/performance/test_sync.py

add on_demand policy to remotes
[noissue]
[nocoverage]

Performance sync cdn test

---

CHANGES.rst
CHANGES/5367.feature
CHANGES/5402.feature
CHANGES/5847.bugfix
CHANGES/6225.feature
CHANGES/6316.feature
CHANGES/6410.removal
CHANGES/6554.removal
CHANGES/6729.feature
CHANGES/7046.bugfix
CHANGES/7072.misc
CHANGES/7096.bugfix
CHANGES/7103.bugfix
CHANGES/7115.bugfix
CHANGES/7116.bugfix
CHANGES/7134.misc
CHANGES/7150.misc

[noissue]
(cherry picked from commit 2896d1b79a228c081eb05af7551e8d95f49668b3)

Building changelog for 3.5.0

---

CHANGES/7159.feature
pulp_rpm/app/models/repository.py
pulp_rpm/app/viewsets.py

Allow Remotes to be associated with a Repository

---

CHANGES/7095.misc
pulp_rpm/app/downloaders.py
pulp_rpm/app/kickstart/treeinfo.py

https://pulp.plan.io/issues/7095
closes #7095
[nocoverage]

Silence 404 errors for treeinfo files

---

CHANGES/7228.bugfix
coverage.md
pulp_rpm/app/tasks/synchronizing.py
pulp_rpm/tests/functional/api/test_sync.py

Sub_repo sync is now also optimized when possible.
closes #7228
https://pulp.plan.io/issues/7228

Handle mirror=True and optimize=True correctly.

---

CHANGES/7284.bugfix
pulp_rpm/app/tasks/copy.py
pulp_rpm/app/viewsets.py
pulp_rpm/tests/functional/api/test_copy.py

Added test_copy_none to suite of copy-tests.
fixes #7284
[nocoverage]

Fixed copy to check for empty-content correctly.

---

CHANGES/7289.feature
pulp_rpm/app/models/package.py
pulp_rpm/app/tasks/publishing.py

[nocoverage]
closes: #7289
https://pulp.plan.io/issues/7289

Publishing performance improvement

---

pulp_rpm/tests/functional/api/test_character_encoding.py
pulp_rpm/tests/functional/api/test_consume_content.py
pulp_rpm/tests/functional/api/test_copy.py
pulp_rpm/tests/functional/api/test_crud_content_unit.py
pulp_rpm/tests/functional/api/test_crud_remotes.py
pulp_rpm/tests/functional/api/test_download_content.py
pulp_rpm/tests/functional/api/test_download_policies.py
pulp_rpm/tests/functional/api/test_publish.py
pulp_rpm/tests/functional/api/test_pulp_to_pulp.py
pulp_rpm/tests/functional/api/test_retention_policy.py
pulp_rpm/tests/functional/api/test_sync.py
pulp_rpm/tests/functional/api/test_upload.py
pulp_rpm/tests/functional/content_handler/test_config_repo.py
pulp_rpm/tests/functional/utils.py
pulp_rpm/tests/performance/test_pulp_to_pulp.py
pulp_rpm/tests/performance/test_sync.py

Updating pulp_smash

---

.bumpversion.cfg
pulp_rpm/__init__.py
setup.py

Bump version to 3.5.1.dev

---

CHANGES/6739.feature
pulp_rpm/app/modelresource.py
pulp_rpm/app/models/distribution.py
pulp_rpm/app/models/repository.py

fixes #6739
Required PR: https://github.com/pulp/pulpcore/pull/819

Allow users to import and export distribution trees

---

template_config.yml

Set stable branch to 3.6

---

CHANGES/7342.bugfix
pulp_rpm/app/downloaders.py
pulp_rpm/app/models/repository.py

closes: #7342
https://pulp.plan.io/issues/7342

Fix sync from local (on-disk) repository

---

pulp_rpm/app/models/comps.py
pulp_rpm/app/models/package.py

Fix some inaccurate docstrings

---

docs/workflows/create_sync_publish.rst

Add a note about mirror list support.

---

CHANGES.rst
CHANGES/7176.doc
CHANGES/7332.bugfix
CHANGES/7342.bugfix

[noissue]
(cherry picked from commit 6354690352c40c1b13314c4b44444367468b02a3)

Building changelog for 3.6.1

---

CHANGES/7394.bugfix
pulp_rpm/app/serializers/distribution.py
pulp_rpm/tests/functional/api/test_sync.py

https://pulp.plan.io/issues/7394
closes #7394

Matched DistributionTree serializers with the models

---

.travis/install.sh
template_config.yml

https://travis-ci.com/github/pulp/pulp_rpm/jobs/381309463#L795
[noissue]
[nocoverage]

Upper and lower bond breaks the job

---

.bumpversion.cfg
CHANGES.rst
CHANGES/7202.bugfix
CHANGES/7290.bugfix
CHANGES/7321.bugfix
CHANGES/7354.bugfix
CHANGES/7369.bugfix
CHANGES/7394.bugfix
pulp_rpm/__init__.py
setup.py

Revert "Release 3.6.2"

---

CHANGES.rst
CHANGES/7202.bugfix
CHANGES/7290.bugfix
CHANGES/7321.bugfix
CHANGES/7354.bugfix
CHANGES/7369.bugfix
CHANGES/7394.bugfix

Cherrypicking 3.6.2 changelog 

---

plugins/pulp_rpm/plugins/distributors/yum/metadata/repomd.py
plugins/test/unit/plugins/distributors/yum/metadata/test_metadata.py

closes #7480
https://pulp.plan.io/issues/7480

Fix high memory issue when calculating metadata open checksum

---

CHANGES/7422.misc
coverage.md
pulp_rpm/tests/functional/api/test_pulpimport.py

Add kickstart export/import tests

---

pulp_rpm/app/models/repository.py

Required PR: https://github.com/pulp/pulpcore/pull/902/
re: #6463
https://pulp.plan.io/issues/6463

Remove duplicated Repository.new_version() method

---

CHANGES/7483.bugfix
pulp_rpm/app/viewsets.py

Required PR: https://github.com/pulp/pulpcore/pull/927
closes: #7483
https://pulp.plan.io/issues/7483

Fix requests timing out with large copy operations

---

.travis/Containerfile.j2
.travis/docs-builder.py
.travis/publish_docs.sh
.travis/release.py
.travis/update_redmine.sh
.travis/validate_commit_message.py
template_config.yml

Travis update

---

.travis.yml
.travis/before_install.sh
.travis/install.sh
.travis/start_container.yaml
template_config.yml

Update travis and set pulpocre versions for z releases

---

template_config.yml

Set the stable branch to 3.7

---

CHANGES/7494.doc
docs/_scripts/copy_basic.sh
docs/_static/api.json
docs/workflows/copy.rst

[nocoverage]
closes #7494
https://pulp.plan.io/projects/pulp_rpm

Added examples how to copy all content.

---

CHANGES/7650.misc
pulp_rpm/tests/functional/api/test_sync.py

closes #7650
https://pulp.plan.io/issues/7650

Removes the ``test_file_decriptors`` test

---

CHANGES/7705.doc
docs/workflows/copy.rst

Clarified the commentary around advanced-copy.

---

CHANGES.rst
CHANGES/6981.doc
docs/_static/api.json
docs/bindings.rst
docs/index.rst
docs/installation.rst
docs/restapi.rst
pulp_rpm/app/settings.py

closes #6981
https://pulp.plan.io/issues/6981

Fixed broken documentation links.

---

pulp_rpm/app/migrations/0027_checksum_null.py

Fixed conflicting migrations.

---

docs/user-guide/release-notes/2.21.x.rst

Added release notes for pulp-2.21.4 release.

---

CHANGES.rst

Changelog for 3.6.3

---

.ci/scripts/release.py
.ci/scripts/validate_commit_message.py
functest_requirements.txt
pulp_rpm/tests/functional/api/test_consume_content.py
requirements.txt
template_config.yml

Resolve CI issues

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/scripts/before_install.sh
README.rst

Updating GHA scripts

---

.ci/scripts/publish_docs.sh
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/scripts/post_before_script.sh
.github/workflows/scripts/post_docs_test.sh
.github/workflows/scripts/pre_before_install.sh

Updating GHA

---

pulp_rpm/tests/functional/api/test_pulpimport.py

The import task group now includes the parent group.
[noissue]

Fix broken import tests

---

template_config.yml

Set 3.8 as stable branch for cherry-picking

---

.github/workflows/nightly.yml
.github/workflows/scripts/script.sh

Fix performance tests

---

.github/workflows/nightly.yml

Fix nightly indentation

---

.github/workflows/nightly.yml

Parallelize performance tests

---

CHANGES/7978.doc
docs/workflows/copy.rst

closes: #7978
https://pulp.plan.io/issues/7978

Fix a mistake in the RPM copy documentation

---

CHANGES/8050.bugfix
pulp_rpm/app/serializers/distribution.py

https://pulp.plan.io/issues/8050
closes #8050
[nocoverage]

Fixing OpenAPI schema for on demand Distribution Trees

---

CHANGES/8009.doc
docs/workflows/copy.rst

closes: #8009
https://pulp.plan.io/issues/8009

Fix documentation mistake for copy API

---

CHANGES/8091.bugfix
coverage.md
pulp_rpm/app/tasks/copy.py
pulp_rpm/tests/functional/api/test_copy.py

[nocoverage]
closes: #8091
https://pulp.plan.io/issues/8091

Fix all modules accidentally being copied

---

docs/user-guide/release-notes/2.21.x.rst

Added release notes for pulp-2.21.5 release.

---

docs/user-guide/release-notes/2.21.x.rst

[noissue]
(cherry picked from commit 922fe5c6eead35ff72730976d7138734fdd255be)

[cp] Added release notes for pulp-2.21.5 release.

---

plugins/pulp_rpm/plugins/importers/yum/pulp_solv.py

closes: #8110
https://pulp.plan.io/issues/8110

Fix typo in the debug message

---

.ci/ansible/Containerfile.j2
.github/workflows/scripts/script.sh

Run CI against the pulp/pulp-ci-centos image

---

.github/workflows/scripts/post_before_script.sh
.github/workflows/scripts/sign.py

update metadata sign in workflow scripts
[noissue]
[nocoverage]

Update GHW sign

---

.ci/ansible/smash-config.json

Update pulp-fixtures port

---

.github/workflows/scripts/install.sh

Fix base_url for pulp-fixtures

---

CHANGES/7537.misc
pulp_rpm/tests/functional/api/test_fips_workflow.py

Added repo-workflow tests for MANY repositories.

---

CHANGES/8245.bugfix
pulp_rpm/app/kickstart/treeinfo.py

closes #8245
https://pulp.plan.io/issues/8245

Fix parsing of is_layered configuration parameter for Distribution Trees

---

CHANGES/8301.misc
pulp_rpm/tests/functional/api/test_pulp_to_pulp.py

Taught test_pulp_to_pulp to not rely on SHA1.

---

CHANGES/8380.bugfix
pulp_rpm/app/serializers/advisory.py
pulp_rpm/tests/functional/api/test_advisory_upload.py

Fixed a regression in uploading advisories with pkglists.

---

CHANGES/8422.bugfix
pulp_rpm/app/tasks/publishing.py

closes #8422
https://pulp.plan.io/issues/8422

Fix the case when package checksum type configuration is not provided.

---

pulp_rpm/tests/functional/api/test_publish.py
pulp_rpm/tests/functional/api/test_sync.py

Not really a publish test if it doesn't publish.
[noissue]

Move sync test

---

pulp_rpm/tests/functional/api/test_fips_workflow.py

Make new flake8_docstrings-1.6 happy

---

pulp_rpm/app/tasks/synchronizing.py

Parts of it are a bit more complicated than necessary. This should help.
[noissue]
[nocoverage]

Clean up sync code slightly

---

pulp_rpm/tests/functional/api/test_sync.py

Adjust the md5 test according to the changes in pulpcore.

---

pulp_rpm/app/tasks/publishing.py
pulp_rpm/app/tasks/synchronizing.py

Replace working directory w/ Python stdlib

---

CHANGES/8546.bugfix
pulp_rpm/app/serializers/repository.py

Fix 500 error when updating a repository.

---

pulp_rpm/app/migrations/0032_new_distribution_model.py

This allows the migration to be reverted.
[noissue]
@dralley I am not sure those are all the fields we need to move.

Refactor distribution migration 0032

---

CHANGES/8426.doc
docs/index.rst
docs/workflows/create_sync_publish.rst

closes #8426
https://pulp.plan.io/issues/8426

Add ULN remote workflow documentation

---

pulp_rpm/app/models/repository.py

[noissue]
Should have been part of https://pulp.plan.io/issues/7905

Also accept UlnRemotes on RpmRepository

---

.ci/ansible/settings.py.j2
.ci/scripts/publish_client_gem.sh
.ci/scripts/publish_client_pypi.sh
.ci/scripts/publish_plugin_pypi.sh
.ci/scripts/release.py
.ci/scripts/validate_commit_message.py
.github/workflows/release.yml
.github/workflows/scripts/before_install.sh
.github/workflows/scripts/check_commit.sh
.github/workflows/scripts/script.sh
template_config.yml

plugin_template updates, including test-cli: True.

---

CHANGES/8700.bugfix
pulp_rpm/app/tasks/synchronizing.py

I believe mine is the same issue as https://pulp.plan.io/issues/8700.

Allow .xz modules.yaml

---

pulp_rpm/app/tasks/synchronizing.py

Libmodulemd can auto-detect compression
[noissue]

Use libmodulemd to open module metadata files

---

pulp_rpm/app/viewsets.py

Switch to new task queuing methods

---

.github/workflows/scripts/before_install.sh
requirements.txt
template_config.yml

Back to using pulpcore master branch for CI

---

CHANGES/8616.misc
pulp_rpm/app/advisory.py
pulp_rpm/tests/functional/api/test_advisory_upload.py
pulp_rpm/tests/functional/api/test_sync.py

Taught unsafe-advisory-merge error to point out ALLOW-UNSAFE cfg.

---

CHANGES/8759.feature
pulp_rpm/app/migrations/0035_fix_auto_publish.py
pulp_rpm/app/models/repository.py
pulp_rpm/app/serializers/repository.py
pulp_rpm/tests/functional/api/test_auto_publish.py
requirements.txt

fixes: #8759
https://pulp.plan.io/issues/8759

Auto-publish doesn't update distributions

---

requirements.txt

Pin productmd on 3.11 branch

---

CHANGES/8812.bugfix
coverage.md
pulp_rpm/app/tasks/synchronizing.py
pulp_rpm/tests/functional/api/test_sync.py

closes #8812
https://pulp.plan.io/issues/8812

Fix sync when skip otpion is used for SRPMs

---

CHANGES/8681.misc
pulp_rpm/app/tasks/publishing.py
pulp_rpm/app/tasks/synchronizing.py
pulp_rpm/tests/functional/api/test_sync.py

closes: #8681
https://pulp.plan.io/issues/8681

Improve progress reporting during sync and publish

---

pulp_rpm/app/tasks/synchronizing.py

Fix an oversight in mirrored metadata publishing

---

CHANGES/8816.bugfix
pulp_rpm/app/downloaders.py

closes: #8816
https://pulp.plan.io/issues/8816

Don't add a trailing slash every time that sles_auth_token is present

---

plugins/pulp_rpm/plugins/distributors/yum/publish.py

closes: #8890
https://pulp.plan.io/issues/8890

Fix slow publish when errata are associated to many repos

---

CHANGES/8864.feature
pulp_rpm/app/metadata_parsing.py
pulp_rpm/app/tasks/synchronizing.py

Port Pulp 2 code to iteratively parse other.xml and filelists.xml

---

.github/workflows/scripts/install.sh
template_config.yml

Updates pulpcore version specifier to ~=3.13.0

---

CHANGES.rst
CHANGES/8944.bugfix
CHANGES/8952.bugfix
CHANGES/8955.bugfix

Rebuild changelog after z-releases

---

CHANGES/9055.bugfix
pulp_rpm/app/tasks/copy.py

closes: #9055
https://pulp.plan.io/issues/9055

Only add package from package group if not already selected

---

.github/workflows/scripts/before_install.sh

Fix CLI test after setting file change

---

plugins/pulp_rpm/plugins/importers/yum/repomd/modules.py

https://bugzilla.redhat.com/show_bug.cgi?id=1920511
closes: #8982
https://pulp.plan.io/issues/8982

Fix saving BSON-encoded data in the database

---

.github/workflows/ci.yml
.github/workflows/create-branch.yml
.github/workflows/nightly.yml
.github/workflows/release.yml

Update the python version in CI

---

CHANGES/9071.bugfix
pulp_rpm/app/models/repository.py
pulp_rpm/tests/functional/content_handler/test_config_repo.py

fixes: #9071
https://pulp.plan.io/issues/9071

Fix auto-distribute for config.repo

---

pulp_rpm/tests/functional/api/test_consume_content.py

Add test that checks artifact save after client consumption

---

CHANGES/9033.removal
setup.py

Drop support for Python 3.6 and 3.7

---

CHANGES/7208.bugfix
pulp_rpm/app/models/repository.py
pulp_rpm/app/tasks/publishing.py
pulp_rpm/tests/functional/api/test_crud_content_unit.py
pulp_rpm/tests/functional/api/test_sync.py
pulp_rpm/tests/functional/constants.py

Handles the case of "same name, multiple locations, diff content".
fixes #7208

Make "is this version valid" checks more lenient.

---

CHANGES/9176.feature
pulp_rpm/app/models/package.py

Enable reclaim disk space feature provided by pulpcore.

---

CHANGES/9176.feature

Updated changelog for the reclaim disk space feature.

---

.ci/ansible/Containerfile.j2
.github/workflows/ci.yml
functest_requirements.txt
pulp_rpm/tests/upgrade/pre/test_publish.py
requirements.txt

Adding pre upgrade test

---

CHANGES/8622.bugfix
coverage.md
pulp_rpm/app/kickstart/treeinfo.py
pulp_rpm/app/tasks/publishing.py
pulp_rpm/app/tasks/synchronizing.py
pulp_rpm/tests/functional/api/test_publish.py
pulp_rpm/tests/functional/api/test_sync.py
pulp_rpm/tests/functional/constants.py

Committing some progress on tests - will resolve multiple issues in this PR

Fixes for distribution tree metadata

---

pulp_rpm/tests/upgrade/pre/test_publish.py

Fix pre upgrade test

---

pulp_rpm/tests/functional/api/test_advisory_upload.py
pulp_rpm/tests/functional/api/test_character_encoding.py
pulp_rpm/tests/functional/api/test_copy.py
pulp_rpm/tests/functional/api/test_crud_content_unit.py
pulp_rpm/tests/functional/api/test_distribution_tree.py
pulp_rpm/tests/functional/api/test_publish.py
pulp_rpm/tests/functional/api/test_pulpexport.py
pulp_rpm/tests/functional/api/test_pulpimport.py
pulp_rpm/tests/functional/api/test_retention_policy.py
pulp_rpm/tests/functional/api/test_sync.py
pulp_rpm/tests/functional/api/test_upload.py
pulp_rpm/tests/functional/content_handler/test_config_repo.py
pulp_rpm/tests/performance/test_publish.py
pulp_rpm/tests/performance/test_sync.py

Use bindings delete_orphans() in tests.

---

CHANGES/9223.bugfix
pulp_rpm/app/models/repository.py
requirements.txt

Unpublished content is no longer available for consumption.

---

requirements.txt

Bump pulpcore requirement to 3.15.0.dev

---

CHANGES/9029.bugfix
pulp_rpm/app/tasks/synchronizing.py

closes: #9029
https://pulp.plan.io/issues/9029

Fix some errors when identical content is synced simultaneously

---

CHANGES/9279.misc
pulp_rpm/app/models/package.py

Required PR: https://github.com/pulp/pulpcore/pull/1565
[noissue]

Package model custom manager needs to inherit core functionality

---

requirements.txt

Needed for ContentManager fix.
[noissue]

Require pulpcore 3.14.5 for 3.14 branch

---

requirements.txt

Needed for the relative path fix.
[noissue]

Require pulpcore 3.7.8 for 3.11 branch

---

CHANGES.rst

[noissue]
(cherry picked from commit fe3f6ec93c9c3758e088f6f932f3f9104f58e3f7)

Building changelog for 3.11.2

---

CHANGES/9308.bugfix
pulp_rpm/app/metadata_parsing.py
pulp_rpm/app/tasks/synchronizing.py

Fix a parser bug and refactor in preparation for new createrepo_c parsing API

---

CHANGES/9135.misc
pulp_rpm/app/tasks/synchronizing.py

closes: #9135
https://pulp.plan.io/issues/9135

Suppress download errors for optional (likely to fail) downloads

---

CHANGES/9147.doc
docs/workflows/create_sync_publish.rst

Add a note about scheduling tasks.

---

pulp_rpm/app/viewsets.py

Make repo during publish a shared resource.

---

CHANGES/8571.bugfix
pulp_rpm/app/tasks/publishing.py

closes: #8571
https://pulp.plan.io/issues/8571

Fix publishing raises forbidden checksum error when it shouldn't

---

CHANGES/9387.bugfix
pulp_rpm/app/depsolving.py

Fix depsolving perf-issues by doing repoclosure once.

---

CHANGES/9407.bugfix
pulp_rpm/app/tasks/synchronizing.py
pulp_rpm/tests/functional/api/test_sync.py

closes: #9407
https://pulp.plan.io/issues/9407

Reject repositories that contain delta metadata in mirror mode

---

CHANGES/9350.bugfix
pulp_rpm/app/shared_utils.py
pulp_rpm/tests/functional/api/test_publish.py
pulp_rpm/tests/functional/api/test_pulp_to_pulp.py
pulp_rpm/tests/unit/test_shared_utils.py

closes: #9350
https://pulp.plan.io/issues/9350

Fixes edge case where gpg key location in .repo file is invalid

---

CHANGES/9329.bugfix
pulp_rpm/app/downloaders.py
pulp_rpm/app/tasks/synchronizing.py
pulp_rpm/tests/functional/api/test_sync.py

closes: #9329
https://pulp.plan.io/issues/9329

Fix a regression in mirrorlist sync support

---

CHANGES/9402.misc
pulp_rpm/app/tasks/publishing.py

closes: #9402
https://pulp.plan.io/issues/9402

Set the "revision" of empty repositories to 0

---

requirements.txt

Fixes some memory leaks, and includes the new parsing API
[noissue]

Bump createrepo_c requirement to the latest version

---

CHANGES/9467.misc
pulp_rpm/app/urls.py

Use newer urlpattern style

---

CHANGES/9464.bugfix
pulp_rpm/app/downloaders.py

Restore embedded-basic-auth-in-url functionality.

---

CHANGES/9486.bugfix
pulp_rpm/app/tasks/synchronizing.py
pulp_rpm/tests/functional/constants.py
pulp_rpm/tests/performance/test_sync.py

closes: #9486
https://pulp.plan.io/issues/9486

Avoid preventing some repositories from using mirror sync incorrectly

---

CHANGES/9225.feature
pulp_rpm/app/serializers/__init__.py
pulp_rpm/app/serializers/comps.py
pulp_rpm/app/tasks/__init__.py
pulp_rpm/app/tasks/comps.py
pulp_rpm/app/urls.py
pulp_rpm/app/viewsets.py
pulp_rpm/tests/functional/api/test_comps.py
pulp_rpm/tests/functional/constants.py

Added comps.xml upload API.

---

CHANGES/9626.misc
pulp_rpm/tests/functional/api/test_sync.py
pulp_rpm/tests/functional/constants.py

Required PR: https://github.com/pulp/pulp-fixtures/pull/228
closes #9626

Added test for repos-using-sha.

---

CHANGES/9259.doc
docs/_scripts/add_remove_cli.sh
docs/_scripts/advisory_cli.sh
docs/_scripts/artifact_cli.sh
docs/_scripts/base_cli.sh
docs/_scripts/copy_basic_cli.sh
docs/_scripts/distribution_cli.sh
docs/_scripts/docs_check_copy_cli.sh
docs/_scripts/docs_check_install_with_signed_repodata_cli.sh
docs/_scripts/docs_check_reset.sh
docs/_scripts/docs_check_sync_cli.sh
docs/_scripts/docs_check_upload_cli.sh
docs/_scripts/download_cli.sh
docs/_scripts/install_from_signed_repository_cli.sh
docs/_scripts/package_cli.sh
docs/_scripts/publication_cli.sh
docs/_scripts/remote_cli.sh
docs/_scripts/repo_cli.sh
docs/_scripts/repo_with_signing_service_cli.sh
docs/_scripts/sync_cli.sh
docs/bindings.rst
docs/workflows/copy.rst
docs/workflows/create_sync_publish.rst
docs/workflows/index.rst
docs/workflows/metadata_signing.rst
docs/workflows/scripting.rst
docs/workflows/upload.rst
docs/workflows/use_pulp_repo.rst

Added pulp-cli examples to docs.

---

CHANGES/9647.bugfix
pulp_rpm/app/downloaders.py
pulp_rpm/tests/unit/test_uln_download.py

closes #9647
https://pulp.plan.io/issues/9647

Fix HTTP-proxy in ULN-remotes

---

plugins/pulp_rpm/plugins/distributors/yum/metadata/repomd.py

Fix for publishing MD5 repos in FIPS env.

---

.github/workflows/ci.yml
.github/workflows/create-branch.yml
.github/workflows/release.yml
.github/workflows/scripts/before_install.sh
.github/workflows/scripts/stage-changelog-for-default-branch.py
template_config.yml

Fixup one last master->main

---

CHANGES/2331.bugfix
pulp_rpm/app/migrations/0003_DATA_incorrect_json.py
pulp_rpm/app/shared_utils.py
pulp_rpm/app/tasks/publishing.py

Close opened files.

---

.ci/scripts/validate_commit_message.py

Enable patchback on 3.11

---

.ci/scripts/validate_commit_message.py

Enable patchback on 3.14

---

CHANGES/2327.bugfix
pulp_rpm/app/kickstart/treeinfo.py
pulp_rpm/app/tasks/synchronizing.py

Affects sync and pulp-2to3-migration(if the modified stage is used).
[noissue]

[3.14.z fix] DistributionTree workaround

---

CHANGES.rst

Cherry-pick missed changelogs

---

CHANGES/2323.misc
pulp_rpm/app/kickstart/treeinfo.py

Parse dist tree timestamps consistently

---

pulp_rpm/app/metadata_parsing.py

Adjust changelog limit logic - always keep one changelog entry

---

CHANGES.rst

Update main branch changelogs manually

---

CHANGES/2373.bugfix
pulp_rpm/app/kickstart/treeinfo.py

* Make properties execute code only once
* Some naming refactor for readability
* Rewrite paths for addons, they never worked for downloading
* Change the subrepo name (still under question)
[noissue]

Fix paths for addons

---

pulp_rpm/app/serializers/repository.py
requirements.txt

Removed distribution validation which is handled in core.

---

CHANGES/2379.bugfix
pulp_rpm/app/tasks/publishing.py

Make sure more file descriptors are closed properly

---

CHANGES/2398.bugfix
pulp_rpm/app/metadata_parsing.py
pulp_rpm/app/tasks/synchronizing.py

Warn / error when repositories with duplicate pkgid / nevra are synced

---

CHANGES.rst
requirements.txt
template_config.yml

Misc fixes

---

CHANGES/2422.bugfix
pulp_rpm/app/advisory.py
pulp_rpm/tests/functional/test_advisory.py

Added advisory-conflict testcases.
fixes #2422

Taught resolve_advisory_conflict to handle just EVR differences.

---

pulp_rpm/tests/functional/api/test_distribution_tree.py

Fix leftover remote in tests

---

docs/Makefile

Fix makefile for changelog building

---

.github/workflows/scripts/install.sh
.github/workflows/scripts/script.sh
pyproject.toml
template_config.yml

Update 3.17 CI

---

CHANGES/2296.bugfix
pulp_rpm/app/metadata_parsing.py
pulp_rpm/app/models/package.py
pulp_rpm/app/settings.py
pulp_rpm/app/tasks/synchronizing.py
requirements.txt

Use new createrepo_c parsing API for less memory consumption

---

CHANGES/2395.bugfix
pulp_rpm/app/tasks/synchronizing.py
pulp_rpm/tests/performance/test_pulp_to_pulp.py

Improved error reporting when repomd.xml is not valid

---

CHANGES/2457.removal
pulp_rpm/app/models/repository.py
pulp_rpm/app/serializers/repository.py
pulp_rpm/app/viewsets.py

Deprecate sqlite_metadata fields on various API endpoints.

---

CHANGES/2475.bugfix
pulp_rpm/app/tasks/publishing.py
pulp_rpm/app/tasks/synchronizing.py

[3.14] Fix instances of /tmp/ being used instead of worker working dir

---

CHANGES/2243.bugfix
pulp_rpm/app/kickstart/treeinfo.py
pulp_rpm/tests/functional/api/test_distribution_tree.py

Fixed treeinfo,images to correctly handle rhel5 treeinfo format.

---

pulp_rpm/tests/functional/api/test_publish.py

Fixing test_publish.

---

CHANGES/2528.bugfix
pulp_rpm/app/models/advisory.py
pulp_rpm/app/shared_utils.py
pulp_rpm/tests/unit/test_shared_utils.py

Add timestamp date parsing for Advisory models

---

pulp_rpm/app/models/advisory.py

WIP: Remove display of empty summary tag in Advisory

---

CHANGES/2560.misc
pulp_rpm/app/viewsets/acs.py
pulp_rpm/app/viewsets/advisory.py
pulp_rpm/app/viewsets/comps.py
pulp_rpm/app/viewsets/custom_metadata.py
pulp_rpm/app/viewsets/distribution.py
pulp_rpm/app/viewsets/modulemd.py
pulp_rpm/app/viewsets/package.py
pulp_rpm/app/viewsets/repository.py
pulp_rpm/tests/functional/api/test_rbac_crud.py
pulp_rpm/tests/functional/conftest.py

Add RBAC queryset scoping for RPM content.
closes #2560

RBAC query scoping

---

CHANGES/2293.bugfix
pulp_rpm/app/tasks/synchronizing.py
pulp_rpm/app/viewsets/repository.py
pulp_rpm/tests/functional/api/test_sync.py

Disallow skip_types while using a mirror sync mode

---

pulp_rpm/app/__init__.py

Add python_package_name for 3.20 compat

---

CHANGES/2274.feature
pulp_rpm/app/tasks/publishing.py

Helps improve compression efficiency a bit
closes #2274

Sort packages in published RPM metadata

---

.github/workflows/scripts/post_docs_test.sh
CHANGES/2303.doc
docs/_scripts/docs_check_delete.sh
docs/_scripts/docs_check_reset.sh
docs/_scripts/remove_content.sh
docs/_scripts/remove_content_cli.sh
docs/workflows/index.rst
docs/workflows/remove_content.rst

Document steps to delete content

---

CHANGES/2588.feature
docs/rbac.rst
pulp_rpm/app/viewsets/advisory.py
pulp_rpm/app/viewsets/comps.py
pulp_rpm/app/viewsets/modulemd.py
pulp_rpm/app/viewsets/package.py

Enforce users to upload content directly into the destination repo.

---

pulp_rpm/tests/functional/constants.py

Changes the CentOS mirror URL to http://mirror.centos.org

---

pulp_rpm/app/models/package.py
pulp_rpm/app/serializers/package.py

Fix is_modular detection, regressed by #2537

---

CHANGES/2276.misc
pulp_rpm/app/modulemd.py
pulp_rpm/tests/functional/api/test_copy.py

Require libmodulemd 2.12

---

requirements.txt

Fixes a small memory leak
[noissue]

Bump createrepo_c version

---

CHANGES/2624.bugfix
pulp_rpm/app/tasks/synchronizing.py

Fix a small FD leak

---

pulp_rpm/tests/performance/test_sync.py

Fix CDN test

---

CHANGES/2479.bugfix
pulp_rpm/app/metadata_parsing.py
pulp_rpm/app/rpm_version.py
pulp_rpm/app/tasks/synchronizing.py
pulp_rpm/tests/functional/api/test_retention_policy.py
pulp_rpm/tests/functional/api/test_sync.py

[3.17] Use retain_package_versions to filter out older pkgs at sync time

---

pulp_rpm/tests/functional/api/test_sync.py

Make error message test less sensitive to change

---

CHANGES/2686.bugfix
pulp_rpm/app/tasks/synchronizing.py

Don't raise a fatal error when encountering unexpected metadata

---

CHANGES/2704.bugfix
pulp_rpm/app/tasks/synchronizing.py

Do not sync optimize if retain-package-versions was set/changed

---

CHANGES/2620.misc
coverage.md
pulp_rpm/tests/functional/api/test_modular.py

Simple test to check that modular packages are marked as modular
package.
closes: #2620
https://github.com/pulp/pulp_rpm/issues/2620

Test ``is_modular``

---

CHANGES/2620.misc
coverage.md
functest_requirements.txt
pulp_rpm/tests/functional/api/test_modular.py
pulp_rpm/tests/functional/conftest.py

backport of `is_modular` test with fix (missing pytest fixtures)

[3.14] Test `is_modular`

---

CHANGES/2585.feature
pulp_rpm/app/modelresource.py
pulp_rpm/tests/functional/api/test_pulpimport.py

fixes #2585.
Require PR: https://github.com/pulp/pulpcore/pull/2713

Taught import to be able to take advantage of "create_repositories".

---

CHANGES/2289.bugfix
docs/installation.rst

Update installation dependencies.
closes: #2289
https://github.com/pulp/pulp_rpm/issues/2289

Installation dependencies

---

pulp_rpm/app/tasks/synchronizing.py

I got impatient about merging it while waiting on an EXD update to do the testing, since it was potentially blocking work for Pavel and Fabricio - and of course that backfired, as it tends to do.
[noissue]

Fix previous PR

---

.github/workflows/scripts/post_before_script.sh

Fix CI signing service

---

CHANGES/2719.bugfix
pulp_rpm/app/models/package.py
pulp_rpm/app/tasks/synchronizing.py

Deduplicate file entries

---

CHANGES/2791.misc
pulp_rpm/app/tasks/synchronizing.py

Consider .treeinfo checksum when optimizing sync

---

CHANGES/2905.misc
functest_requirements.txt
pulp_rpm/tests/functional/api/test_publish.py

Fixed two tests that incorrectly assume HTML can be treated like XML.

---

CHANGES/2821.bugfix
docs/workflows/manage.rst
pulp_rpm/app/advisory.py
pulp_rpm/tests/functional/api/test_advisory_conflict.py

Resolve duplicate-advisory-ids at new-version-create time.

---

requirements.txt

Fix lowerbound check

---

CHANGES/2886.misc
pulp_rpm/tests/functional/api/test_acs.py
pulp_rpm/tests/functional/api/test_sync.py
pulp_rpm/tests/functional/conftest.py
pulp_rpm/tests/functional/constants.py

Refactor test_sync tests

---

pulp_rpm/tests/functional/api/test_sync.py

Sync content with the mirror_content_only policy

---

pulp_rpm/app/advisory.py
pulp_rpm/app/depsolving.py
pulp_rpm/app/shared_utils.py
pulp_rpm/app/tasks/publishing.py
pulp_rpm/app/tasks/synchronizing.py

Update to respond to black-23.1.0 opinions.

---

CHANGES/2585.feature

Restore 2585 changelog so it shows up in 3.19 release.

---

doc_requirements.txt

Pinned sphinx-rtd-theme to < 1.2.0 to fix the search.

---

.github/workflows/update_ci.yml
template_config.yml

Set up automatic ci-updates for 3.18 and 3.19 branches.

---

CHANGES/2874.misc
pulp_rpm/tests/functional/api/test_copy.py
pulp_rpm/tests/functional/conftest.py

Refactor copy tests to follow the pytest standard

---

CHANGES/2988.bugfix
pulp_rpm/app/migrations/0044_noartifact_modules.py

default_storage.exists takes file referenced by name

---

pulp_rpm/tests/functional/api/test_rbac_crud.py

Required PR: https://github.com/pulp/pulpcore/pull/3642
[noissue]
[nocoverage]

Run test_rbac_crud tests in parallel

---

pulp_rpm/app/viewsets/repository.py
requirements.txt

Fixes deprecation-warnings starting w/ core/3.23.

---

CHANGES/2876.misc
pulp_rpm/tests/functional/api/test_crud_remotes.py

Rewrite crud_remote tests

---

CHANGES/2887.misc
pulp_rpm/tests/functional/api/test_upload.py
pulp_rpm/tests/functional/conftest.py

Rewrite upload tests

---

pulp_rpm/tests/functional/api/test_rbac_crud.py

Wait until the ACS delete task finishes

---

pulp_rpm/app/modelresource.py

Needed to teach import to handle domains.
[noissue]

Taught modelresource to call super().before_row_import().

---

CHANGES/2995.feature
pulp_rpm/app/replica.py

Adds RpmReplicator

---

CHANGES/2867.misc
pulp_rpm/tests/functional/api/test_acs.py

Use pytest style for test_acs

---

CHANGES/2868.misc
pulp_rpm/tests/functional/api/test_advisory_conflict.py

Refactor test_advisory_conflict to use pytest

---

CHANGES/2870.misc
pulp_rpm/tests/functional/api/test_auto_publish.py

Refactor test_auto_publish to use pytest

---

CHANGES/2871.misc
pulp_rpm/tests/functional/api/test_character_encoding.py

Refactor test_character_encoding to use pytest

---

CHANGES/2878.misc
pulp_rpm/tests/functional/api/test_download_content.py

Refactor test_download_content to use pytest

---

CHANGES/2882.misc
pulp_rpm/tests/functional/api/test_pulp_to_pulp.py

Refactor test_pulp_to_pulp to use pytest

---

CHANGES/2877.misc
pulp_rpm/tests/functional/api/test_distribution_tree.py
pulp_rpm/tests/functional/conftest.py

Refactor test_distribution_tree to use pytest

---

CHANGES/2869.misc
pulp_rpm/tests/functional/api/test_advisory_upload.py

Refactory test_advisory_upload to use pytest

---

CHANGES/3076.misc
pulp_rpm/tests/functional/conftest.py
pulp_rpm/tests/functional/content_handler/test_config_repo.py

Refactor test_config_repo to use pytest

---

CHANGES/3079.misc
pulp_rpm/tests/functional/conftest.py
pulp_rpm/tests/performance/test_sync.py

Not sure how long these sync tests run for, so I haven't tested this.
fixes: #3079

Refactor performance/test_sync to use pytest

---

pulp_rpm/tests/performance/test_sync.py

Just noticed I was using the wrong fixture name. (Twice!)
[noissue]

Small fixture name fix for performance/test_sync

---

CHANGES/3078.misc
pulp_rpm/tests/performance/test_pulp_to_pulp.py

Another one I haven't test yet.
fixes: #3078

Refactor performance/test_pulp_to_pulp to use pytest

---

CHANGES/3077.misc
pulp_rpm/tests/performance/test_publish.py

The last performance test (still haven't tested it)
fixes: #3077

Refactor performance/test_publish to use pytest

---

CHANGES/2873.misc
pulp_rpm/tests/functional/api/test_consume_content.py
pulp_rpm/tests/functional/conftest.py
pulp_rpm/tests/functional/utils.py

Refactor test_consume_content to use pytest

---

CHANGES/2885.misc
pulp_rpm/tests/functional/api/test_retention_policy.py
pulp_rpm/tests/functional/conftest.py

closes #2885
(cherry picked from commit 5e5936829d1f18a16a96985af49762bc1b24c1ae)

Rewrite retention policy tests

---

CHANGES/3119.bugfix
pulp_rpm/app/depsolving.py
pulp_rpm/tests/functional/api/test_copy.py
pulp_rpm/tests/functional/conftest.py

closes #3119
https://github.com/pulp/pulp_rpm/issues/3119

Fix module depsolving

---

CHANGES/3121.bugfix
pulp_rpm/app/modulemd.py

Fix a bug for syncing and publishing a mercurial RPM repo

---

pulp_rpm/app/modulemd.py

Revised module splitting

---

CHANGES/3135.feature
pulp_rpm/app/viewsets/package.py

Add more filter options on various fields

---

CHANGES/3150.doc
doc_requirements.txt
docs/conf.py

closes #3150
Since I just copied the fix for `pulp_deb`  I figured I could just do it quickly here as well.

Fix infinite loading in the docs search bar

---

CHANGES/2980.bugfix
pulp_rpm/app/tasks/synchronizing.py

Fixed data-fixup-during-sync deadlock.

---

CHANGES/3177.bugfix
pulp_rpm/app/migrations/0048_artifacts_dependencies_fix.py

Made migration more robust when there are "broken" modulemds.

---

CHANGES/3183.bugfix
pulp_rpm/app/serializers/package.py

Fix retrieve

---

CHANGES/3195.bugfix
pulp_rpm/app/serializers/advisory.py

Remove broken retrieve for advisories

---

CHANGES/3196.bugfix
pulp_rpm/app/migrations/0049_profiles_fix.py

Made another migration more robust when there are "broken" modulemds.

---

CHANGES/3217.misc
pulp_rpm/tests/functional/constants.py
pulp_rpm/tests/performance/test_sync.py

Taught perf-test to use rawhide instead of F36 repo.

---

CHANGES/3234.misc
pulp_rpm/app/tasks/synchronizing.py

Remove content mutability / sync-time data fixups

---

CHANGES/3243.feature
pulp_rpm/app/viewsets/repository.py

Adjust access policies for labels

---

pulp_rpm/tests/functional/conftest.py

Make signed_artifact fixture idempotent

---

CHANGES/3259.bugfix
pulp_rpm/app/models/repository.py

Optimize a query to improve export performance

---

CHANGES/+pulpcore-3.40.feature
pulp_rpm/app/serializers/advisory.py
pulp_rpm/tests/functional/api/test_advisory_upload.py
requirements.txt

[noissue]
I hope this will comply to one of the breaking changes in 3.40.

Update for pulpcore 3.40 compatibility

---

docs/workflows/create_sync_publish.rst

Added mention of autopublish and retain_repo_versions to the docs.

---

CHANGES/3381.bugfix
CHANGES/3381.feature
pulp_rpm/app/viewsets/repository.py
pulp_rpm/tests/functional/api/test_rbac_crud.py
requirements.txt

Fixes default access policies for Publications and Distributions.

---

template_config.yml

Update supported version

---

functest_requirements.txt
unittest_requirements.txt

Pinning pytest<8 for unit/functional tests.

---

CHANGES/2821.bugfix
docs/workflows/manage.rst
functest_requirements.txt
lint_requirements.txt
pulp_rpm/app/advisory.py
pulp_rpm/tests/functional/api/test_advisory_conflict.py

Resolve duplicate-advisory-ids at repo-version-create time.

---

CHANGES/3380.bugfix
pulp_rpm/app/advisory.py
pulp_rpm/app/modelresource.py

Addressed an edge-case around advisory-collection name collisions.

---

.github/workflows/scripts/publish_client_pypi.sh
.github/workflows/scripts/publish_plugin_pypi.sh

Fix PyPI upload

---

CHANGES/3445.misc
pyproject.toml
staging_docs/admin/guides/01-rbac.md
staging_docs/admin/learn/01-settings.md
staging_docs/dev/guides/01-bindings.md
staging_docs/user/guides/01-use_pulp_repo.md
staging_docs/user/guides/02-upload.md
staging_docs/user/guides/03-copy.md
staging_docs/user/guides/04-alternate-content-source.md
staging_docs/user/guides/05-metadata_signing.mdB
staging_docs/user/guides/06-remove_content.md
staging_docs/user/learn/01-manage.md
staging_docs/user/tutorials/00-overview.md
staging_docs/user/tutorials/01-create_sync_publish.md

Convert docs to new stack.

---

CHANGES/3427.bugfix
pulp_rpm/app/serializers/modulemd.py
pulp_rpm/tests/functional/api/test_crud_content_unit.py

Backported from: https://github.com/pulp/pulp_rpm/pull/3508

Backport 3.23/fix modulemd upload

---

CHANGES/3427.bugfix
pulp_rpm/app/serializers/modulemd.py
pulp_rpm/tests/functional/api/test_crud_content_unit.py

Backport 3.25/fix modulemd upload

---

requirements.txt

Bump min supported libcomps

---

CHANGES/3520.misc
pulp_rpm/app/serializers/repository.py
pulp_rpm/tests/functional/api/test_crud_remotes.py

Add url validaton for Rpm and Uln remote creation

---

pulp_rpm/tests/functional/api/test_distribution_tree.py

Fix test to be pulpcore-3.55 compatible

---

staging_docs/admin/guides/add-signing-services.md
staging_docs/admin/index.md
staging_docs/dev/guides/bindings.md
staging_docs/dev/index.md
staging_docs/user/guides/_SUMMARY.md
staging_docs/user/guides/alternate-content-source.md
staging_docs/user/guides/metadata_signing.md
staging_docs/user/guides/modify.md
staging_docs/user/guides/sign-packages.md
staging_docs/user/guides/upload.md
staging_docs/user/index.md
staging_docs/user/tutorials/create_sync_publish.md

Fix some docs broken links

---

template_config.yml

Drop 3.18 and 3.19 from supported branches

---

CHANGES/3854.misc
template_config.yml

Add django-storage compat test to CI

---

CHANGES/3910.bugfix
pulp_rpm/app/viewsets/advisory.py
pulp_rpm/app/viewsets/modulemd.py
pulp_rpm/app/viewsets/package.py
pulp_rpm/tests/functional/api/test_crud_content_unit.py

Fixed set/unset_label API RBAC - now comes with a new permission.

---

pyproject.toml

Improve FIPS compliance for images built from Pulp

Bump createrepo_c requirement

---

CHANGES/3311.bugfix
pulp_rpm/app/modulemd.py

Fix a sync memory consumption issue w/ modular repos

---

template_config.yml

Branches should explicitly set their storage configs. See: https://github.com/pulp/plugin_template/pull/977

Add storage settings to template_config.yml

---

CHANGES/4117.bugfix
pulp_rpm/app/tasks/publishing.py
pulp_rpm/app/tasks/synchronizing.py

Make synchronize() return a serializable object.
